import { createClient } from 'npm:@supabase/supabase-js@2';

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const slug=(s:string)=>String(s||'location').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,72)||'location';
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v??{}));
const arr=(v:any)=>Array.isArray(v)?v:[];
const cap=(v:any,n:number)=>arr(v).slice(0,n);
function defaultSpec(name:string,key:string){return{version:3,name,widthCells:30,heightCells:22,cellSizeFt:5,northAngle:0,theme:'deep-forest',regions:[{id:'room-1',type:'room',name:'Entry',shape:'rect',x:4,y:7,w:9,h:8,properties:{elevationFt:0}}],walls:[{id:'room-1-n',x1:4,y1:7,x2:13,y2:7,blocksMovement:true,blocksVision:true},{id:'room-1-e',x1:13,y1:7,x2:13,y2:15,blocksMovement:true,blocksVision:true},{id:'room-1-s',x1:4,y1:15,x2:13,y2:15,blocksMovement:true,blocksVision:true},{id:'room-1-w',x1:4,y1:7,x2:4,y2:15,blocksMovement:true,blocksVision:true}],doors:[{id:'entry-door',x:8.5,y:15,orientation:0,isOpen:true,isLocked:false}],objects:[{id:'entry-light',type:'light',x:8.5,y:11,cover:0}],effects:[],lighting:{mode:'dark',sources:[{id:'entry-light',x:8.5,y:11,brightFt:20,dimFt:40}]},meta:{locationKey:key}};}
function sanitizeSpec(spec:any,name:string,key:string){const s=clone(spec||defaultSpec(name,key));s.version=3;s.name=String(s.name||name).slice(0,120);s.widthCells=clamp(Number(s.widthCells)||30,8,80);s.heightCells=clamp(Number(s.heightCells)||22,8,80);s.cellSizeFt=[5,10].includes(Number(s.cellSizeFt))?Number(s.cellSizeFt):5;s.northAngle=((Number(s.northAngle)||0)%360+360)%360;s.theme=String(s.theme||'deep-forest').slice(0,40);s.regions=cap(s.regions,120);s.walls=cap(s.walls,220);s.doors=cap(s.doors,80);s.objects=cap(s.objects,120);s.effects=cap(s.effects,60);s.lighting={mode:['bright','dim','dark'].includes(String(s.lighting?.mode))?String(s.lighting.mode):'bright',sources:cap(s.lighting?.sources,80)};s.meta={...(s.meta||{}),locationKey:key};return s;}
function applyOps(spec:any,ops:any[]){const s=clone(spec);for(const raw of cap(ops,40)){const op=String(raw?.op||'');if(op==='add_region'&&raw.region){s.regions=cap([...(s.regions||[]),raw.region],120);}else if(op==='add_wall'&&raw.wall){s.walls=cap([...(s.walls||[]),raw.wall],220);}else if(op==='add_door'&&raw.door){s.doors=cap([...(s.doors||[]),raw.door],80);}else if(op==='set_door'){const d=(s.doors||[]).find((x:any)=>x.id===raw.id);if(d){if(typeof raw.isOpen==='boolean')d.isOpen=raw.isOpen;if(typeof raw.isLocked==='boolean')d.isLocked=raw.isLocked;}}else if(op==='add_object'&&raw.object){s.objects=cap([...(s.objects||[]),raw.object],120);}else if(op==='remove_object'){s.objects=(s.objects||[]).filter((x:any)=>x.id!==raw.id);}else if(op==='add_effect'&&raw.effect){s.effects=cap([...(s.effects||[]),raw.effect],60);}else if(op==='remove_effect'){s.effects=(s.effects||[]).filter((x:any)=>x.id!==raw.id);}else if(op==='set_lighting'){s.lighting={mode:['bright','dim','dark'].includes(String(raw.mode))?String(raw.mode):s.lighting?.mode||'bright',sources:cap(raw.sources??s.lighting?.sources,80)};}else if(op==='set_north'){s.northAngle=((Number(raw.angle)||0)%360+360)%360;}}return s;}
function sanitizeWorld(state:any){const w=clone(state||{});w.version=1;w.northAngle=((Number(w.northAngle)||0)%360+360)%360;w.locations=cap(w.locations,120);w.routes=cap(w.routes,180);return w;}

Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 if(req.method!=='POST')return json({ok:false,error:'POST required'},405);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,worker=Deno.env.get('DUNGEON_AI_WORKER_URL')||'https://dungeon-dwellers-ai.jesse-datema08.workers.dev',auth=req.headers.get('Authorization')||'';
 const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service);
 const {data:ud,error:ue}=await userClient.auth.getUser();const user=ud?.user;if(ue||!user)return json({ok:false,error:'Authentication required'},401);
 const p=await req.json().catch(()=>({}));const campaignId=String(p.campaignId||'');if(!campaignId)return json({ok:false,error:'campaignId is required'},400);
 const {data:member}=await admin.from('campaign_members').select('role').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle(),{data:campaign}=await admin.from('campaigns').select('id,name,owner_id,state,current_scene').eq('id',campaignId).maybeSingle();if(!campaign||(!member&&campaign.owner_id!==user.id))return json({ok:false,error:'Campaign access denied'},403);
 const {data:latestDm}=await admin.from('chat_messages').select('body,created_at').eq('campaign_id',campaignId).eq('sender_kind','dm').eq('visibility','party').order('created_at',{ascending:false}).limit(1).maybeSingle();
 const sceneSummary=String(campaign.current_scene||campaign.state?.sceneText||'').slice(0,5000),narration=String(latestDm?.body||'').slice(0,5000);if(!sceneSummary&&!narration)return json({ok:true,noChange:true,reason:'No authoritative public scene context yet'});
 const {data:map}=await admin.from('campaign_maps').select('*').eq('campaign_id',campaignId).eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle(),{data:worldRow}=await admin.from('campaign_world_maps').select('*').eq('campaign_id',campaignId).maybeSingle();
 const world=sanitizeWorld(worldRow?.state||{}),currentLocation=map?{id:map.id,name:map.name,locationKey:map.location_key,mapKind:map.map_kind,spec:map.generated_spec}:null;
 const prompt=`You update player-safe maps for a D&D campaign. Return ONLY one JSON object in narration, no prose around it. Infer the party's current public location from the authoritative scene below. Never reveal secret or undiscovered rooms, doors, traps, enemies, routes, or landmarks. Only add geometry/features that the party has actually perceived. Reuse locationKey when the party remains in the same place. If they clearly enter a new named place, use a stable lowercase-hyphen locationKey and locationName. Use small deltas, never a full map. Allowed ops: add_region {region}, add_wall {wall}, add_door {door}, set_door {id,isOpen?,isLocked?}, add_object {object}, remove_object {id}, add_effect {effect}, remove_effect {id}, set_north {angle}. Regions use grid coordinates on an approximately 30x22 5-ft map. Include worldLocation {id,name,x,y,type} only when a location is publicly discovered. Include worldRoute {from,to,label?} only when a route between already discovered locations becomes known. If nothing map-relevant changed, use empty ops and keep the same locationKey.\nJSON shape: {"locationKey":"","locationName":"","locationChanged":false,"ops":[],"worldLocation":null,"worldRoute":null}.\nCampaign: ${JSON.stringify({name:campaign.name,currentLocation,worldLocations:world.locations.slice(-40)})}\nScene summary: ${sceneSummary}\nLatest public DM narration: ${narration}`;
 const r=await fetch(worker,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({message:prompt,campaignState:{campaignId,mapMode:'player-safe'}})});const text=await r.text();let raw:any;try{raw=text?JSON.parse(text):{}}catch{raw={raw:text}};if(!r.ok||raw?.ok===false)return json({ok:false,error:raw?.error||raw?.message||text||`AI HTTP ${r.status}`},502);const model=raw?.dm??raw?.result??raw;let out:any=model;if(typeof model==='string'){const m=model.match(/\{[\s\S]*\}/);try{out=JSON.parse(m?.[0]||'{}')}catch{out={}}}if(model&&typeof model==='object'&&typeof model.narration==='string'){const m=model.narration.match(/\{[\s\S]*\}/);try{out=JSON.parse(m?.[0]||'{}')}catch{out={}}}
 const ops=cap(out?.ops,40),locationKey=slug(out?.locationKey||currentLocation?.locationKey||out?.locationName||currentLocation?.name||'current-location'),locationName=String(out?.locationName||currentLocation?.name||'Current Location').slice(0,120),sameLocation=Boolean(map&&String(map.location_key||'')===locationKey&&!out?.locationChanged),hasWorldDelta=Boolean(out?.worldLocation||out?.worldRoute);
 if(sameLocation&&!ops.length&&!hasWorldDelta&&worldRow&&world.currentLocationId===locationKey)return json({ok:true,noChange:true,map:{id:map.id,name:map.name,location_key:map.location_key},world:{currentLocationId:world.currentLocationId,locationCount:world.locations.length,routeCount:world.routes.length},appliedOps:0});
 let target=map;
 if(!target||out?.locationChanged===true||String(target.location_key||'')!==locationKey){const {data:existing}=await admin.from('campaign_maps').select('*').eq('campaign_id',campaignId).eq('location_key',locationKey).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(existing)target=existing;else{const spec=sanitizeSpec(defaultSpec(locationName,locationKey),locationName,locationKey);const {data:created,error:ce}=await admin.from('campaign_maps').insert({campaign_id:campaignId,name:locationName,map_kind:'tactical',location_key:locationKey,active:false,width:spec.widthCells,height:spec.heightCells,grid_size:spec.cellSizeFt,north_angle:spec.northAngle,generated_spec:spec}).select('*').single();if(ce)return json({ok:false,error:ce.message},500);target=created;}}
 if(target){const spec=sanitizeSpec(applyOps(sanitizeSpec(target.generated_spec,locationName,locationKey),ops),locationName,locationKey);await admin.from('campaign_maps').update({active:false}).eq('campaign_id',campaignId).neq('id',target.id);const {data:updated,error:me}=await admin.from('campaign_maps').update({active:true,name:locationName,map_kind:'tactical',location_key:locationKey,width:spec.widthCells,height:spec.heightCells,grid_size:spec.cellSizeFt,north_angle:spec.northAngle,generated_spec:spec,updated_at:new Date().toISOString()}).eq('id',target.id).select('*').single();if(me)return json({ok:false,error:me.message},500);target=updated;await admin.from('tokens').update({map_id:target.id}).eq('campaign_id',campaignId).in('token_type',['pc','player']);}
 if(out?.worldLocation){const wl=out.worldLocation,id=slug(wl.id||locationKey),existing=world.locations.find((x:any)=>x.id===id);const item={id,name:String(wl.name||locationName).slice(0,120),x:clamp(Number(wl.x)||50,0,100),y:clamp(Number(wl.y)||50,0,100),type:String(wl.type||'location').slice(0,40),mapId:target?.id||null};if(existing)Object.assign(existing,item);else world.locations.push(item);}
 if(!world.locations.some((x:any)=>x.id===locationKey))world.locations.push({id:locationKey,name:locationName,x:50,y:50,type:'location',mapId:target?.id||null});
 if(out?.worldRoute){const rr=out.worldRoute,from=slug(rr.from),to=slug(rr.to);if(world.locations.some((x:any)=>x.id===from)&&world.locations.some((x:any)=>x.id===to)&&from!==to&&!world.routes.some((x:any)=>(x.from===from&&x.to===to)||(x.from===to&&x.to===from)))world.routes.push({from,to,label:String(rr.label||'').slice(0,80)});}
 world.currentLocationId=locationKey;world.locations=cap(world.locations,120);world.routes=cap(world.routes,180);
 await admin.from('campaign_world_maps').upsert({campaign_id:campaignId,state:world,updated_at:new Date().toISOString()},{onConflict:'campaign_id'});
 return json({ok:true,map:target?{id:target.id,name:target.name,location_key:target.location_key}:null,world:{currentLocationId:world.currentLocationId,locationCount:world.locations.length,routeCount:world.routes.length},appliedOps:ops.length});
});

