import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const TABLES=['campaign_world_maps','campaign_engine_state','campaign_memory','encounter_state','campaign_maps','characters','tokens','initiative_entries','reaction_windows','quests','knowledge','story_events','chat_messages','npc_state'] as const;
const CHILD_DELETE=['reaction_windows','initiative_entries','tokens','campaign_maps','characters','quests','knowledge','story_events','chat_messages','npc_state'] as const;
function cleanRows(rows:any[],campaignId:string){return (rows||[]).map(r=>{const x={...r,campaign_id:campaignId};delete x.created_at;delete x.updated_at;if('id'in x&&typeof x.id==='number')delete x.id;return x;});}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'POST required'},405);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')||'',uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service),{data:ud}=await uc.auth.getUser(),user=ud?.user;if(!user)return json({ok:false,error:'Authentication required'},401);const body=await req.json().catch(()=>({})),campaignId=String(body.campaignId||''),mode=String(body.mode||'export');if(!campaignId)return json({ok:false,error:'campaignId required'},400);const {data:campaign}=await admin.from('campaigns').select('*').eq('id',campaignId).maybeSingle();if(!campaign||campaign.owner_id!==user.id)return json({ok:false,error:'Only the campaign owner can back up or restore this campaign.'},403);
 if(mode==='export'){const data:any={version:2,app:'Dungeon Dwellers V2',exportedAt:new Date().toISOString(),campaign:{...campaign}};for(const t of TABLES){const {data:rows,error}=await admin.from(t).select('*').eq('campaign_id',campaignId);if(error)return json({ok:false,error:`Backup failed reading ${t}: ${error.message}`},500);data[t]=rows||[];}const {data:members}=await admin.from('campaign_members').select('campaign_id,user_id,role,joined_at').eq('campaign_id',campaignId);data.campaign_members=members||[];return json({ok:true,backup:data});}
 if(mode!=='restore')return json({ok:false,error:'mode must be export or restore'},400);const backup=body.backup;if(!backup||Number(backup.version)!==2||backup.app!=='Dungeon Dwellers V2')return json({ok:false,error:'This is not a Dungeon Dwellers V2 backup.'},400);if(body.confirmName!==campaign.name)return json({ok:false,error:'Campaign name confirmation does not match.'},400);
 const campaignPatch={name:backup.campaign?.name||campaign.name,chapter:Number(backup.campaign?.chapter||1),paused:!!backup.campaign?.paused,current_scene:backup.campaign?.current_scene||null,game_time:backup.campaign?.game_time||null,initiative_style:backup.campaign?.initiative_style||'Initiative Blocks',active_deadline:backup.campaign?.active_deadline||null,deadline_type:backup.campaign?.deadline_type||null,settings:backup.campaign?.settings||{},active_block:backup.campaign?.active_block||null,round_number:Number(backup.campaign?.round_number||0),state:backup.campaign?.state||{},scheduled_start:backup.campaign?.scheduled_start||null,sleep_start:backup.campaign?.sleep_start||null,sleep_end:backup.campaign?.sleep_end||null,schedule_timezone:backup.campaign?.schedule_timezone||'UTC',schedule_paused:!!backup.campaign?.schedule_paused,schedule_pause_started_at:backup.campaign?.schedule_pause_started_at||null,updated_at:new Date().toISOString()};
 const {error:ce}=await admin.from('campaigns').update(campaignPatch).eq('id',campaignId);if(ce)return json({ok:false,error:ce.message},500);
 for(const t of CHILD_DELETE){const {error}=await admin.from(t).delete().eq('campaign_id',campaignId);if(error)return json({ok:false,error:`Restore failed clearing ${t}: ${error.message}`},500);}
 for(const t of ['campaign_world_maps','campaign_engine_state','campaign_memory','encounter_state'] as const){await admin.from(t).delete().eq('campaign_id',campaignId);}
 const order=['campaign_world_maps','campaign_engine_state','campaign_memory','encounter_state','campaign_maps','characters','tokens','initiative_entries','reaction_windows','quests','knowledge','story_events','chat_messages','npc_state'] as const;
 for(const t of order){const rows=cleanRows(Array.isArray(backup[t])?backup[t]:[],campaignId);if(!rows.length)continue;const {error}=await admin.from(t).insert(rows);if(error)return json({ok:false,error:`Restore failed writing ${t}: ${error.message}`},500);}
 await admin.from('campaign_engine_state').upsert({campaign_id:campaignId},{onConflict:'campaign_id'});await admin.from('campaign_memory').upsert({campaign_id:campaignId},{onConflict:'campaign_id'});await admin.from('encounter_state').upsert({campaign_id:campaignId},{onConflict:'campaign_id'});await admin.from('campaign_world_maps').upsert({campaign_id:campaignId},{onConflict:'campaign_id'});
 return json({ok:true,restored:true,campaignId});
});