(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={paused:false,hp:38,maxHp:50,secondWind:3,actionSurge:1,potions:3,relic:false,combat:false,initiativeStyle:'Initiative Blocks',reaction:true,history:[],attackActionAttacks:0,lastScene:'',time:'9:16 PM'};
let state={...defaults,...JSON.parse(localStorage.getItem('ddBetaV4')||'{}')};
const save=()=>localStorage.setItem('ddBetaV4',JSON.stringify(state));
function updateUI(){ $('#hpText').textContent=`${state.hp} / ${state.maxHp} HP`;$('#hpBar').style.width=`${state.hp/state.maxHp*100}%`;$('#swCount').textContent=`${state.secondWind}/3`;$('#asCount').textContent=`${state.actionSurge}/1`;$('#campaignStatus').textContent=state.paused?'Campaign paused':'AI DM active';$('[data-owner="pause"]').textContent=state.paused?'Resume':'Pause';$('#reactionText').textContent=state.reaction?'Available':'Spent';$('#gameTime').textContent=state.time;$('#relicStatus').textContent=state.relic?'Lantern of the Hollow Star · Unidentified · 2 lb':'No identified magic items.';}
function nav(page){$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));$$('.page').forEach(p=>p.classList.toggle('active',p.id===page+'Page'));}
$$('.nav button').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
const modal=$('#modal'), rollModal=$('#rollModal');let modalPrimary=null, modalBack=null, rollCfg=null, rollDone=null, rollBusy=false;
function openModal({kicker='Details',title,body='',choices=[],primary='Use',onPrimary=null,back='Cancel',onBack=null}){ $('#modalKicker').textContent=kicker;$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;const c=$('#modalChoices');c.innerHTML='';choices.forEach(ch=>{const b=document.createElement('button');b.innerHTML=`<strong>${ch.label}</strong><span>${ch.meta||''}</span>`;b.onclick=()=>ch.onSelect?.();c.appendChild(b)});$('#modalPrimary').style.display=onPrimary?'block':'none';$('#modalPrimary').textContent=primary;$('#modalBack').textContent=back;modalPrimary=onPrimary;modalBack=onBack;modal.classList.add('open');}
$('#modalPrimary').onclick=()=>modalPrimary?.();$('#modalBack').onclick=()=>{modal.classList.remove('open');modalBack?.();};
function mathRows(rows){return rows.map(([a,b])=>`<div class="row"><span>${a}</span><strong>${b}</strong></div>`).join('');}
function prepRoll(cfg,done){rollCfg=cfg;rollDone=done;rollBusy=false;$('#rollKicker').textContent=cfg.kicker||'Roll';$('#rollTitle').textContent=cfg.title;$('#dieNum').textContent='—';$('#rollLabel').textContent='Ready';$('#rollResult').textContent='—';$('#rollMath').innerHTML='';$('#rollButton').style.display='block';$('#rollButton').disabled=false;$('#rollButton').textContent=cfg.button||'Roll';$('#rollClose').textContent='Cancel';$('#dieStage').className='dieStage';rollModal.classList.add('open');}
$('#rollButton').onclick=()=>{if(!rollCfg||rollBusy)return;rollBusy=true;const cfg=rollCfg, stage=$('#dieStage'), num=$('#dieNum');$('#rollButton').disabled=true;$('#rollButton').textContent='Rolling';stage.className='dieStage rolling';let seq=[7,13,4,18,9,16,11,5,19,2,14,8,17,6],i=0;const t=setInterval(()=>num.textContent=seq[i++%seq.length],90);setTimeout(()=>{clearInterval(t);num.textContent=cfg.raw;stage.className='dieStage '+(cfg.raw===1?'nat1':cfg.critical?'critical':'');$('#rollLabel').textContent=cfg.label;$('#rollResult').textContent=cfg.result;$('#rollMath').innerHTML=mathRows(cfg.rows||[]);$('#rollButton').style.display='none';$('#rollClose').textContent=cfg.close||'Continue';rollBusy=false;},1400)};
$('#rollClose').onclick=()=>{if(rollBusy)return;rollModal.classList.remove('open');const fn=rollDone;rollCfg=null;rollDone=null;if(fn)fn();};
function impact(msg){nav('scene');$('#sceneNotice').textContent=msg;const r=$('#ripple'),c=$('#sceneCard');r.classList.remove('run');void r.offsetWidth;r.classList.add('run');c.classList.remove('sceneImpact');void c.offsetWidth;c.classList.add('sceneImpact');}
function addEvent(text){const d=document.createElement('div');d.innerHTML=`<strong>Just now</strong>${text}`;$('#timeline').prepend(d);state.history.push(text);save();}
function requireActive(){if(state.paused){$('#sceneNotice').textContent='Campaign is paused. Resume it before advancing the world.';return false}return true;}
function randomD10(){return Math.floor(Math.random()*10)+1}function roll2d6(){return [Math.floor(Math.random()*6)+1,Math.floor(Math.random()*6)+1]}

// Scene actions
$('[data-action="inspect"]').onclick=()=>{if(!requireActive())return;openModal({kicker:'Scene Action',title:'Inspect Shrine',body:'Spend your meaningful scene action examining the collapsed shrine closely.',primary:'Inspect',onPrimary:()=>{modal.classList.remove('open');addEvent('You inspected the collapsed shrine.');impact('You find fresh soot beneath the shrine and hear a faint metallic clicking inside the west wall.')}})};
$('[data-action="attack"]').onclick=()=>{if(!requireActive())return;nav('inventory');setTimeout(()=>document.querySelector('[data-item="claymore"]').click(),120)};
$('[data-action="move"]').onclick=()=>{if(!requireActive())return;openModal({kicker:'Movement',title:'Move toward the bronze door',body:'Move up to your Speed. This preview uses 20 feet of movement and preserves 10 feet.',primary:'Move',onPrimary:()=>{modal.classList.remove('open');impact('You cross the chamber toward the bronze door. Your remaining movement is 10 feet.')}})};
$('[data-action="custom"]').onclick=()=>$('#customInput').focus();
$('[data-action="send-custom"]').onclick=()=>{const v=$('#customInput').value.trim();if(!v)return;if(/rule|how does|can i|what does/i.test(v)){openModal({kicker:'Rules',title:'Rules Question',body:'Rules questions do not consume your scene action in this beta. The production AI DM will answer from the 2024 rules and your current character state.',back:'Close'});}else if(requireActive()){openModal({kicker:'Custom Turn',title:'Confirm Intent',body:`<p>${escapeHtml(v)}</p><p>The production AI DM would convert this intent into legal movement, action economy, checks, targets, costs, and consequences before resolution.</p>`,primary:'Submit Action',onPrimary:()=>{modal.classList.remove('open');impact('Your custom action is submitted. The scene updates after the required checks and consequences resolve.')}});}$('#customInput').value='';};
function escapeHtml(s){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}

// Inventory details and Greatsword/Claymore attack flow
$('[data-item="claymore"]').onclick=()=>openModal({kicker:'Weapon Details',title:'Claymore',body:'<div class="featureGrid"><div><strong>Rules profile</strong><span>Greatsword</span></div><div><strong>Damage</strong><span>2d6 Slashing</span></div><div><strong>Properties</strong><span>Heavy, Two-Handed</span></div><div><strong>Mastery</strong><span>Graze</span></div><div><strong>Weight</strong><span>6 lb</span></div><div><strong>Attack Bonus</strong><span>+7 (STR +4, PB +3)</span></div></div><p>A level 5 Fighter makes two attacks when taking the Attack action.</p>',primary:'Use',onPrimary:()=>{modal.classList.remove('open');chooseWeaponTarget(1)}});
function chooseWeaponTarget(attackNumber){openModal({kicker:`Attack ${attackNumber} of 2`,title:'Select Entity',body:'Choose a visible entity in reach.',choices:[{label:'Unknown Creature',meta:'Hostile · visible · in reach',onSelect:()=>confirmSwing('Unknown Creature',attackNumber)},{label:'Neris',meta:'Friendly NPC · visible · in reach · friendly fire allowed',onSelect:()=>confirmSwing('Neris',attackNumber)}],back:'Back',onBack:()=>nav('inventory')});}
function confirmSwing(target,attackNumber){modal.classList.remove('open');setTimeout(()=>openModal({kicker:`Attack ${attackNumber} of 2`,title:`Swing at ${target}`,body:'Your Claymore is ready. Press Swing to make the attack roll.',primary:'Swing',onPrimary:()=>{modal.classList.remove('open');attackRoll(target,attackNumber)}}),70)}
function attackRoll(target,attackNumber){const raw=attackNumber===1?14:19,total=raw+7,critical=raw>=19;prepRoll({title:'Roll to Hit',button:'Roll to Hit',raw,label:critical?'Critical Hit':'Attack Total',result:critical?`${total} · Critical`:`${total} · Hit`,critical,rows:[['d20',raw],['Strength','+4'],['Proficiency','+3'],['Total',total]],close:'Roll Damage'},()=>damageRoll(target,attackNumber,critical));}
function damageRoll(target,attackNumber,critical){const dice=critical?[...roll2d6(),...roll2d6()]:roll2d6();const total=dice.reduce((a,b)=>a+b,0)+4;prepRoll({title:'Roll Damage',button:'Roll Damage',raw:dice[0],label:'Damage',result:`${total} Slashing`,rows:[['Claymore',critical?'4d6 (Critical)':'2d6'],['Damage Dice',dice.join(' + ')],['Strength','+4'],['Total',`${total} Slashing`]],close:attackNumber<2?'Continue Attack Action':'Apply Damage'},()=>{addEvent(`Attack ${attackNumber}: Claymore hit ${target} for ${total} slashing damage.`);if(attackNumber<2){openModal({kicker:'Extra Attack',title:'One attack remains',body:'Because you are a level 5 Fighter, the Attack action lets you attack twice.',choices:[{label:'Make Second Attack',meta:'Choose a target for attack 2',onSelect:()=>{modal.classList.remove('open');chooseWeaponTarget(2)}},{label:'End Attack Action',meta:'Forfeit the second attack',onSelect:()=>{modal.classList.remove('open');impact(`Your Claymore attack against ${target} changes the fight. You end the Attack action with one attack unused.`)}}],back:'End Action',onBack:()=>impact('You end your Attack action.')});}else impact(`Your second Claymore strike lands. The scene updates around the completed Attack action.`);});}
$('[data-item="potion"]').onclick=()=>openModal({kicker:'Item Details',title:`Healing Potion ×${state.potions}`,body:'Consume one potion to regain 2d4 + 2 Hit Points.',primary:'Use',onPrimary:()=>{if(state.potions<1)return;modal.classList.remove('open');const a=Math.floor(Math.random()*4)+1,b=Math.floor(Math.random()*4)+1,heal=a+b+2;state.potions--;state.hp=Math.min(state.maxHp,state.hp+heal);save();updateUI();impact(`You drink a Healing Potion and regain ${heal} HP (${a} + ${b} + 2).`)}});
$('[data-item="shield"]').onclick=()=>openModal({kicker:'Item Details',title:'Shield',body:'A shield grants +2 AC while wielded. You cannot wield it while making an attack with a Two-Handed weapon such as the Greatsword-profile Claymore.',back:'Close'});
$('[data-item="pack"]').onclick=()=>openModal({kicker:'Inventory',title:'Explorer\'s Pack',body:'Rope, torches, rations, waterskin, bedroll, mess kit, tinderbox, and other tracked adventuring supplies.',back:'Close'});

// Fighter features, correct for Fighter 5
$$('[data-feature="secondWind"]').forEach(b=>b.onclick=()=>{if(state.secondWind<1)return openModal({title:'Second Wind',body:'No uses remain.',back:'Close'});openModal({kicker:'Class Feature · Bonus Action',title:'Second Wind',body:`You have ${state.secondWind}/3 uses. Regain 1d10 + Fighter level (5) HP. At Fighter 5, Tactical Shift also lets you move up to half your Speed without provoking Opportunity Attacks.`,primary:'Use Second Wind',onPrimary:()=>{modal.classList.remove('open');const d=randomD10(),heal=d+5;state.secondWind--;state.hp=Math.min(state.maxHp,state.hp+heal);save();updateUI();openModal({kicker:'Tactical Shift',title:`Recovered ${heal} HP`,body:`Second Wind: d10 ${d} + Fighter level 5 = ${heal} HP. You may now move up to 15 feet without provoking Opportunity Attacks.`,choices:[{label:'Move 15 feet',meta:'Tactical Shift · no Opportunity Attacks',onSelect:()=>{modal.classList.remove('open');impact(`Second Wind restores ${heal} HP. You use Tactical Shift to reposition 15 feet without provoking Opportunity Attacks.`)}},{label:'Stay Put',meta:'Do not use the movement',onSelect:()=>{modal.classList.remove('open');impact(`Second Wind restores ${heal} HP. You hold your position.`)}}],back:'Stay Put',onBack:()=>impact(`Second Wind restores ${heal} HP.`)});}})});
$$('[data-feature="actionSurge"]').forEach(b=>b.onclick=()=>{if(state.actionSurge<1)return openModal({title:'Action Surge',body:'No uses remain until a Short or Long Rest.',back:'Close'});openModal({kicker:'Class Feature',title:'Action Surge',body:'On your turn, gain one additional action. Under the 2024 Fighter feature, that extra action cannot be the Magic action.',primary:'Use Action Surge',onPrimary:()=>{state.actionSurge=0;save();updateUI();modal.classList.remove('open');impact('Action Surge is active. You gain one additional action this turn, except the Magic action.')}})});
$$('[data-feature="tacticalMind"]').forEach(b=>b.onclick=()=>openModal({kicker:'Class Feature',title:'Tactical Mind',body:'Tactical Mind is reactive: after you fail an ability check, you can spend a Second Wind use to roll 1d10 and add it to the check. If the check still fails, the Second Wind use is not expended.',primary:'Test Failed Check',onPrimary:()=>{modal.classList.remove('open');prepRoll({title:'Failed Athletics Check',button:'Roll Check',raw:7,label:'Check Total',result:'11 · Failure',rows:[['d20','7'],['Strength','+4'],['Total','11']],close:'Use Tactical Mind'},()=>{if(state.secondWind<1)return impact('The check fails and no Second Wind uses remain for Tactical Mind.');openModal({kicker:'Tactical Mind',title:'Add 1d10 to the check?',body:`Second Wind uses remaining: ${state.secondWind}/3. If the boosted total still fails, the use is not expended.`,primary:'Use Tactical Mind',onPrimary:()=>{modal.classList.remove('open');const d=8,boosted=19;prepRoll({title:'Tactical Mind',button:'Roll d10',raw:d,label:'Boosted Check',result:`${boosted} · Success`,rows:[['Original Check','11'],['Tactical Mind d10',`+${d}`],['New Total',boosted]],close:'Apply Result'},()=>{state.secondWind--;save();updateUI();impact('Tactical Mind turns the failed check into a success. One Second Wind use is expended.')})}})})}}));

// Champion Initiative: advantage
$('[data-action="initiative-roll"]').onclick=()=>prepRoll({title:'Initiative · Advantage',button:'Roll Initiative',raw:17,label:'Initiative',result:'19',rows:[['d20s','17, 8 · keep 17'],['Dexterity','+2'],['Total','19'],['Reason','Remarkable Athlete grants Advantage']],close:'Apply'},()=>impact('Initiative 19 is recorded.'));

// Tests
$('[data-test="save"]').onclick=()=>prepRoll({title:'Constitution Saving Throw',button:'Roll Save',raw:14,label:'Save Total',result:'17',rows:[['d20','14'],['Constitution','+3'],['Total','17']]});
$('[data-test="hidden"]').onclick=()=>prepRoll({title:'Make a Roll',button:'Roll',raw:9,label:'Hidden Result',result:'?',rows:[['d20','9'],['Wisdom','+1'],['Proficiency','+3'],['Total','13']]});
$('[data-test="passive"]').onclick=()=>openModal({kicker:'Passive Check',title:'Check Passive Perception',body:'Passive Perception is 14. The hidden difficulty is not shown.',primary:'Check',onPrimary:()=>{modal.classList.remove('open');impact('Nothing catches your attention.')}});
$('[data-test="group"]').onclick=()=>prepRoll({title:'Group Check',button:'Roll Group Check',raw:15,label:'Group Result',result:'Success',rows:[['Jesse','22'],['Neris','14'],['Group Result','Success']]});
$('[data-test="concentration"]').onclick=()=>prepRoll({title:'Concentration Save',button:'Roll Save',raw:12,label:'Constitution Save',result:'15 · Success',rows:[['Damage Taken','10'],['DC','10'],['d20','12'],['Constitution','+3'],['Total','15']]});
$('[data-test="death"]').onclick=()=>prepRoll({title:'Death Saving Throw',button:'Roll Death Save',raw:13,label:'Death Save',result:'Success',rows:[['d20','13'],['Successes','1'],['Failures','0']]});

// Owner
$('[data-owner="pause"]').onclick=()=>{state.paused=!state.paused;save();updateUI();$('#ownerNotice').textContent=state.paused?'Campaign paused. Response timers and AI progression are frozen.':'Campaign resumed from the exact paused state.'};
$('[data-owner="rewind"]').onclick=()=>openModal({kicker:'Owner Control',title:'Rewind',body:'Restore the beta to the scene state before the most recent local changes.',primary:'Rewind',onPrimary:()=>{state={...defaults};save();updateUI();modal.classList.remove('open');impact('Campaign state rewound to the chapter checkpoint.')}});
$('[data-owner="correct"]').onclick=()=>openModal({kicker:'Owner Control',title:'Correct HP',body:'Beta correction example: restore 5 HP without consuming a character resource.',primary:'Apply +5 HP',onPrimary:()=>{state.hp=Math.min(state.maxHp,state.hp+5);save();updateUI();modal.classList.remove('open');$('#ownerNotice').textContent='Owner correction applied: +5 HP.'}});
$('[data-owner="combat"]').onclick=()=>{if(!requireActive())return;openModal({kicker:'Combat Begins',title:'Roll Initiative',body:'The hidden creature lunges from behind the shrine. Champion Remarkable Athlete gives Advantage on Initiative.',primary:'Roll Initiative',onPrimary:()=>{modal.classList.remove('open');state.combat=true;save();prepRoll({title:'Initiative · Advantage',button:'Roll Initiative',raw:17,label:'Initiative',result:'19',rows:[['d20s','17, 8 · keep 17'],['Dexterity','+2'],['Total','19']]},()=>{state.attackActionAttacks=2;$('#modeText').textContent='Combat · Player Block';impact('Combat begins. Your Initiative Block opens before the enemy block.')})}})};

// Reactions
$('[data-action="reaction-demo"]').onclick=()=>openModal({kicker:'Reaction',title:'Opportunity Attack',body:'A hostile creature is leaving your reach. Reaction window: 59m 42s.',choices:[{label:'Opportunity Attack',meta:'Use your Reaction to make one melee attack',onSelect:()=>{modal.classList.remove('open');state.reaction=false;save();updateUI();confirmSwing('Unknown Creature',1)}},{label:'Custom Reaction',meta:'Describe a legal creative reaction',onSelect:()=>{modal.classList.remove('open');impact('Custom Reaction selected. In production, the AI DM would validate it against the trigger and your available Reaction.')}}],back:'Forfeit Reaction',onBack:()=>{state.reaction=false;save();updateUI();impact('The reaction window is forfeited.')}});

// Relic
$('[data-action="relic"]').onclick=()=>{if(state.relic)return openModal({kicker:'Magic Item',title:'Lantern of the Hollow Star',body:'Ancient Relic · Unidentified. Known: emits pale cold light. Attunement and deeper properties remain hidden until identified or discovered.',back:'Close'});openModal({kicker:'Relic Discovery',title:'Take the shadowed relic',body:'Add the relic to your inventory. Unknown properties remain hidden.',primary:'Take Relic',onPrimary:()=>{state.relic=true;save();updateUI();modal.classList.remove('open');impact('The relic rises from the dust. Lantern of the Hollow Star added to your inventory.')}})};

// World
$('[data-world="short-rest"]').onclick=()=>openModal({kicker:'Rest',title:'Short Rest',body:'Spend 1 hour. Fighter resources: regain one expended Second Wind use and Action Surge. Hit Dice spending is optional and player-driven.',choices:[{label:'Spend 1 Hit Die',meta:'d10 + CON modifier',onSelect:()=>{const d=7,heal=d+3;state.hp=Math.min(state.maxHp,state.hp+heal);state.secondWind=Math.min(3,state.secondWind+1);state.actionSurge=1;state.time='10:16 PM';save();updateUI();modal.classList.remove('open');impact(`Short Rest complete. Hit Die restores ${heal} HP. One Second Wind use and Action Surge recover.`)}},{label:'Do not spend Hit Dice',meta:'Recover only rest-based class resources',onSelect:()=>{state.secondWind=Math.min(3,state.secondWind+1);state.actionSurge=1;state.time='10:16 PM';save();updateUI();modal.classList.remove('open');impact('Short Rest complete. One Second Wind use and Action Surge recover. No Hit Die spent.')}}],back:'Cancel'});
$('[data-world="long-rest"]').onclick=()=>openModal({kicker:'Rest',title:'Long Rest',body:'Complete a Long Rest to restore HP and eligible class resources. The in-game clock advances.',primary:'Long Rest',onPrimary:()=>{state.hp=state.maxHp;state.secondWind=3;state.actionSurge=1;state.reaction=true;state.time='6:16 AM';save();updateUI();modal.classList.remove('open');impact('Long Rest complete. HP and eligible Fighter resources are restored.')}});
$('[data-world="travel"]').onclick=()=>openModal({kicker:'Travel',title:'Travel to Blackmere',body:'14 miles at normal pace. The production AI DM tracks pace, supplies, weather, watches, time, and hidden encounter checks.',primary:'Begin Travel',onPrimary:()=>{modal.classList.remove('open');state.time='1:40 PM';save();updateUI();impact('You begin the road to Blackmere. Travel time and supplies advance.')}});
$('[data-world="merchant"]').onclick=()=>openModal({kicker:'Merchant',title:'Quartermaster Pell',body:'His suspicion affects willingness and prices.',choices:[{label:'Healing Potion · 50 gp',meta:'Buy one',onSelect:()=>{state.potions++;save();modal.classList.remove('open');impact('You buy one Healing Potion from Pell.')}},{label:'Rope, 50 ft · 1 gp',meta:'Supply item',onSelect:()=>{modal.classList.remove('open');impact('Rope added to inventory.')}},{label:'Bargain',meta:'May require a Charisma check',onSelect:()=>{modal.classList.remove('open');prepRoll({title:'Persuasion Check',button:'Roll Check',raw:13,label:'Check Total',result:'13',rows:[['d20','13'],['Charisma','+0'],['Total','13']]},()=>impact('Pell does not lower the price, but his suspicion does not worsen.'))}}],back:'Leave'});
$('[data-world="downtime"]').onclick=()=>openModal({kicker:'Downtime',title:'Choose Activity',body:'Downtime advances in-game time and tracks cost, progress, and consequences.',choices:[{label:'Train',meta:'Progress a proficiency or language',onSelect:()=>impact('Training downtime is scheduled and progress is recorded.')},{label:'Research',meta:'Investigate the Ashen Vault',onSelect:()=>impact('Research downtime begins. New clues can be uncovered legitimately.')},{label:'Build Relationship',meta:'Spend time with an NPC',onSelect:()=>impact('Relationship downtime begins and NPC memory updates.')}],back:'Cancel'});
$('[data-world="craft"]').onclick=()=>openModal({kicker:'Crafting',title:'Smithing Options',body:'Crafting requires appropriate tools, proficiency, materials, time, and a valid recipe.',choices:[{label:'Repair Armor',meta:'Smith\'s Tools · 1 hour',onSelect:()=>impact('Armor repair begins. Time and materials are tracked.')},{label:'Craft Caltrops',meta:'Smith\'s Tools · iron scrap',onSelect:()=>impact('Caltrop crafting begins. Materials and time are tracked.')}],back:'Cancel'});

// Systems
$('[data-system="initiative"]').onclick=()=>openModal({kicker:'Campaign Setting',title:'Initiative Style',body:`Current: ${state.initiativeStyle}`,choices:['Initiative Blocks','Rolling Initiative Windows','24-Hour Planned Round'].map(x=>({label:x,meta:x===state.initiativeStyle?'Current':'Select',onSelect:()=>{state.initiativeStyle=x;save();modal.classList.remove('open');$('#systemNotice').textContent=`Initiative style set to ${x}.`}})),back:'Cancel'});
$('[data-system="notification"]').onclick=async()=>{if(!('Notification'in window))return $('#systemNotice').textContent='Notifications are unavailable in this browser.';const p=await Notification.requestPermission();if(p==='granted'){const reg=await navigator.serviceWorker.ready;reg.showNotification('Dungeon Dwellers',{body:'Your reaction window is open. You have 1 hour to respond.',icon:'icon-192.png'});$('#systemNotice').textContent='Local test notification sent.'}else $('#systemNotice').textContent='Notification permission was not granted.'};
$('[data-system="split"]').onclick=()=>openModal({kicker:'Party State',title:'Split Party Preview',body:'Each subgroup receives its own scene, fog, narration, and private discoveries.',choices:[{label:'Group A',meta:'Jesse · Ashen Vault',onSelect:()=>impact('You remain in Group A. Group-specific fog and discoveries stay private.')},{label:'Group B',meta:'No players assigned',onSelect:()=>{}}],back:'Close'});
$('[data-system="import"]').onclick=()=>$('#pdfInput').click();$('#pdfInput').onchange=e=>{const f=e.target.files[0];if(f)$('#systemNotice').textContent=`Selected ${f.name}. The static beta can accept the file, but full PDF parsing/review requires the production parser/backend; this beta does not pretend the import succeeded.`};
$('[data-system="reset"]').onclick=()=>openModal({kicker:'Beta',title:'Reset Campaign',body:'Reset all local beta state to the chapter checkpoint.',primary:'Reset',onPrimary:()=>{localStorage.removeItem('ddBetaV4');location.reload()}});

updateUI();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
})();
