(()=>{
'use strict';
if(window.__DD_COMMUNITY_CHAT_V7)return;window.__DD_COMMUNITY_CHAT_V7=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB=()=>window.DungeonDB;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
let uid=null,cid=null,members=[],characters=[],mode='party',peer='dm',refreshing=false,busy=false,channel=null,queued=false;
function patchGlobalRealtime(){const db=DB();if(!db?.client||db.__chatPerfPatched)return;db.__chatPerfPatched=true;db.subscribe=function(campaign_id,onChange){const ch=db.client.channel(`dd:${campaign_id}:${crypto.randomUUID()}`);ch.on('postgres_changes',{event:'*',schema:'public',table:'campaigns',filter:`id=eq.${campaign_id}`},p=>onChange('campaigns',p));['campaign_members','characters','tokens','campaign_maps','map_views','token_visibility','initiative_entries','turn_submissions','scene_submissions','reaction_windows','story_events','knowledge','quests','notification_outbox'].forEach(table=>ch.on('postgres_changes',{event:'*',schema:'public',table,filter:`campaign_id=eq.${campaign_id}`},p=>onChange(table,p)));return ch.subscribe();};}
patchGlobalRealtime();window.addEventListener('dd:db-ready',patchGlobalRealtime,{once:true});
function toast(text,type=''){const t=$('#toast');if(!t)return;t.textContent=text;t.className=`toast show ${type}`;clearTimeout(t._cc);t._cc=setTimeout(()=>t.className='toast',3000);}
function campaignId(){return localStorage.getItem('ddPreferredCampaign');}
async function waitReady(){for(let i=0;i<60;i++){const db=DB(),id=campaignId();if(db&&id){patchGlobalRealtime();const s=await db.session().catch(()=>null);if(s?.user){uid=s.user.id;cid=id;return true;}}await new Promise(r=>setTimeout(r,120));}return false;}
function nameFor(id){if(id===uid)return 'You';const c=characters.find(x=>x.user_id===id);if(c)return c.display_name||c.name||'Player';return members.find(x=>x.user_id===id)?`Player ${String(id).slice(0,5)}`:'Player';}
function installStyles(){if($('#communityChatStyles'))return;const st=document.createElement('style');st.id='communityChatStyles';st.textContent=`
.communityChatCard{padding:14px;min-height:64vh;display:flex;flex-direction:column;background:#050608!important;border:1px solid #8a672f!important;box-shadow:0 16px 48px rgba(0,0,0,.38)}
.chatTop{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding-bottom:12px;border-bottom:1px solid #4d3918}.chatTop h2{margin:4px 0 2px;font-family:Georgia,serif;font-size:24px;color:#f1d590}.chatTop p{margin:0;color:#898f96;font-size:11px}.chatTabs{display:flex;gap:7px}.chatTabs button{border:1px solid #7c5c29;background:#08090b;color:#d0b97f;border-radius:999px;padding:8px 12px;font-size:11px}.chatTabs button.active{border-color:#d4aa52;color:#f8dda0;background:#151006}
.dmPeers{display:flex;gap:8px;overflow-x:auto;padding:10px 0 4px;scrollbar-width:none}.dmPeers::-webkit-scrollbar{display:none}.dmPeer{flex:0 0 auto;display:flex;align-items:center;gap:8px;border:1px solid #80602c;background:#08090b;color:#d6d9dd;border-radius:12px;padding:8px 10px;text-align:left}.dmPeer.active{border-color:#d4aa52;background:#151006}.dmPeer .avatar{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;border:1px solid #a87f3a;background:#030405;color:#ebc978;font-size:10px;font-weight:800}.dmPeer strong,.dmPeer small{display:block}.dmPeer strong{font-size:11px}.dmPeer small{font-size:9px;color:#777d84;margin-top:2px}
.communityFeed{flex:1;min-height:330px;max-height:58vh;overflow:auto;display:flex;flex-direction:column;gap:10px;padding:14px 2px 10px;overscroll-behavior:contain}.communityMsg{display:flex;gap:8px;align-items:flex-end;max-width:94%}.communityMsg.mine{align-self:flex-end;flex-direction:row-reverse}.communityMsg .avatar{width:30px;height:30px;flex:0 0 30px;border-radius:50%;display:grid;place-items:center;border:1px solid #a77e38;background:#030405;color:#deb96d;font-size:9px;font-weight:800}.communityBubble{border:1px solid #a67d39;border-radius:14px;background:#08090b;padding:10px 12px;min-width:0;box-shadow:0 6px 18px rgba(0,0,0,.26)}.communityMsg.mine .communityBubble{border-color:#c99b49;background:#0a0b0d}.communityMsg.dm .communityBubble{border-color:#d7aa51;background:#08090b}.communityBubble strong{font-size:11px;color:#e9c97c}.communityBubble .dmBadge{display:inline-block;margin-left:6px;padding:2px 5px;border-radius:999px;border:1px solid #a27b39;color:#efcd7d;font-size:8px}.communityBubble span.body{display:block;margin-top:5px;white-space:pre-wrap;line-height:1.5;font-size:13px;color:#e2e4e7}.communityBubble small{display:block;margin-top:6px;color:#70767d;font-size:9px}
.communityComposer{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:end;border-top:1px solid #4d3918;padding-top:10px}.communityComposer textarea{min-height:46px;max-height:120px;resize:none;background:#050608!important;border:1px solid #936f33!important;color:#ece7dc!important}.communityFoot{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:8px}.communityFoot span{font-size:10px;color:#777d84}.communityFoot button{border:0;background:none;color:#ddb96b;padding:0}.communityEmpty{margin:auto;color:#767c83;font-size:12px;text-align:center;padding:28px}.communityTyping{font-size:10px;color:#ddb96b;padding:0 2px 7px}@media(max-width:560px){.chatTop{flex-direction:column}.chatTabs{width:100%}.chatTabs button{flex:1}.communityChatCard{min-height:58vh}.communityMsg{max-width:98%}}
`;document.head.appendChild(st);}
async function loadPeople(){if(!cid)return;const [rows,chars]=await Promise.all([DB().members(cid),DB().memberCharacters(cid)]);members=rows||[];characters=chars||[];}
function bindShell(){if(!$('#partyChatHome'))return false;$('#ccParty').onclick=()=>{mode='party';render();};$('#ccPrivate').onclick=()=>{mode='private';render();};$('#communitySend').onclick=sendCurrent;$('#communityAskDM').onclick=askDmInCurrent;$('#communityInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendCurrent();}});return true;}
function renderPeers(){const root=$('#communityPeers');if(!root)return;if(mode!=='private'){root.classList.add('hidden');root.innerHTML='';return;}root.classList.remove('hidden');const others=members.filter(m=>m.user_id!==uid);root.innerHTML=`<button class="dmPeer ${peer==='dm'?'active':''}" data-peer="dm"><span class="avatar">DM</span><span><strong>AI Dungeon Master</strong><small>Private</small></span></button>${others.map(m=>`<button class="dmPeer ${peer===m.user_id?'active':''}" data-peer="${m.user_id}"><span class="avatar">${esc(nameFor(m.user_id).slice(0,2).toUpperCase())}</span><span><strong>${esc(nameFor(m.user_id))}</strong><small>Private</small></span></button>`).join('')}`;$$('.dmPeer',root).forEach(b=>b.onclick=()=>{peer=b.dataset.peer;render();});}
function exactRecipients(m,ids){const got=[...(m.recipient_user_ids||[])].sort(),want=[...new Set(ids)].sort();return got.length===want.length&&got.every((x,i)=>x===want[i]);}
function samePlayerConversation(m){if(m.visibility!=='private')return false;if(m.sender_kind==='dm')return exactRecipients(m,[uid,peer]);return (m.user_id===uid&&(m.recipient_user_ids||[]).includes(peer))||(m.user_id===peer&&(m.recipient_user_ids||[]).includes(uid));}
function visibleRows(rows){if(mode==='party')return rows.filter(m=>m.visibility!=='private');if(peer==='dm')return rows.filter(m=>m.visibility==='private'&&((m.sender_kind==='dm'&&exactRecipients(m,[uid]))||(m.user_id===uid&&m.metadata?.channel==='dm')));return rows.filter(samePlayerConversation);}
async function latestRows(){const {data,error}=await DB().client.from('chat_messages').select('*').eq('campaign_id',cid).order('created_at',{ascending:false}).limit(60);if(error)throw error;return (data||[]).reverse();}
async function renderFeed(){if(refreshing||!cid||!$('#communityFeed'))return;refreshing=true;try{const rows=await latestRows(),shown=visibleRows(rows),root=$('#communityFeed');root.innerHTML=shown.map(m=>{const dm=m.sender_kind==='dm',mine=m.user_id===uid&&m.sender_kind==='player',label=dm?'Dungeon Master':nameFor(m.user_id),time=new Date(m.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});return `<div class="communityMsg ${mine?'mine':''} ${dm?'dm':''}"><div class="avatar">${dm?'DM':esc(label.slice(0,2).toUpperCase())}</div><div class="communityBubble"><strong>${esc(label)}</strong>${dm?'<span class="dmBadge">AI DM</span>':''}<span class="body">${esc(m.body)}</span><small>${esc(time)}</small></div></div>`;}).join('')||`<div class="communityEmpty">${mode==='party'?'No messages yet. Start the conversation.':peer==='dm'?'No private messages with the Dungeon Master yet.':`No private messages with ${esc(nameFor(peer))} yet.`}</div>`;root.scrollTop=root.scrollHeight;}catch(e){toast(e.message||String(e),'bad');}finally{refreshing=false;}}
function queueFeed(){if(queued)return;queued=true;setTimeout(()=>{queued=false;renderFeed();},120);}
function render(){if(!$('#partyChatHome'))return;$('#ccParty').classList.toggle('active',mode==='party');$('#ccPrivate').classList.toggle('active',mode==='private');renderPeers();const sub=$('#communitySubtitle'),privacy=$('#communityPrivacy'),ask=$('#communityAskDM'),input=$('#communityInput');if(mode==='party'){sub.textContent='Shared party channel · public AI DM actions and results appear here';privacy.textContent='Everyone in the campaign can see this channel.';ask.textContent='Ask / Act with AI DM';ask.classList.remove('hidden');input.placeholder='Message the party...';}else if(peer==='dm'){sub.textContent='Private conversation with the AI Dungeon Master';privacy.textContent='Secret questions and secret actions stay in this DM thread.';ask.classList.add('hidden');input.placeholder='Ask or act secretly with the Dungeon Master...';}else{sub.textContent=`Private conversation with ${nameFor(peer)}`;privacy.textContent='Only the people in this DM thread can see these messages.';ask.classList.remove('hidden');ask.textContent='Ask AI DM in this DM';input.placeholder=`Message ${nameFor(peer)} privately...`;}queueFeed();}
async function insertPlayer(body,visibility,recipients,metadata={}){const {error}=await DB().client.from('chat_messages').insert({campaign_id:cid,user_id:uid,sender_kind:'player',visibility,recipient_user_ids:recipients,body,mentions:[],metadata});if(error)throw error;}
async function invokeDm(body,visibility,recipients){const typing=$('#communityTyping');typing?.classList.remove('hidden');try{const {data,error}=await DB().client.functions.invoke('dungeon-chat',{body:{campaignId:cid,message:body,visibility,recipientUserIds:recipients}});if(error)throw error;if(data?.ok===false)throw new Error(data.error||'AI DM failed');if(data?.event?.rollRequest)window.dispatchEvent(new CustomEvent('dd:roll-request',{detail:{request:data.event.rollRequest,visibility:visibility==='private'?'private':'party'}}));return data;}finally{typing?.classList.add('hidden');}}
async function sendCurrent(){const input=$('#communityInput');if(!input||busy)return;const body=input.value.trim();if(!body)return;busy=true;input.value='';try{if(mode==='party')await insertPlayer(body,'party',[],{channel:'party'});else if(peer==='dm'){await insertPlayer(body,'private',[uid],{channel:'dm',to:'dm'});await invokeDm(body,'private',[uid]);}else await insertPlayer(body,'private',[peer],{channel:'direct',peer});queueFeed();}catch(e){toast(e.message||String(e),'bad');}finally{busy=false;}}
async function askDmInCurrent(){const input=$('#communityInput');if(!input||busy)return;const body=input.value.trim();if(!body){toast('Type a message for the Dungeon Master first.','warn');return;}busy=true;input.value='';try{if(mode==='party'){await insertPlayer(body,'party',[],{channel:'party',asksDm:true});await invokeDm(body,'party',[]);}else if(peer!=='dm'){await insertPlayer(body,'private',[peer],{channel:'direct',peer,asksDm:true});await invokeDm(body,'private',[peer]);}queueFeed();}catch(e){toast(e.message||String(e),'bad');}finally{busy=false;}}
async function subscribe(){if(channel)DB().client.removeChannel(channel);channel=DB().client.channel(`community:${cid}:${crypto.randomUUID()}`).on('postgres_changes',{event:'*',schema:'public',table:'chat_messages',filter:`campaign_id=eq.${cid}`},queueFeed).subscribe();}
async function switchCampaign(next=campaignId()){if(!next||next===cid)return;cid=next;peer='dm';await loadPeople();await subscribe();render();}
async function init(){if(!await waitReady())return;patchGlobalRealtime();installStyles();if(!bindShell())return;await loadPeople().catch(()=>{});await subscribe();render();window.addEventListener('storage',()=>switchCampaign().catch(()=>{}));document.addEventListener('visibilitychange',()=>{if(!document.hidden)switchCampaign().catch(()=>{});});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,60));else setTimeout(init,60);
})();