(()=>{
'use strict';
const MAX_DICE_PER_TERM=100,MAX_SIDES=1000;
function secureDie(sides){sides=Number(sides);if(!Number.isInteger(sides)||sides<2||sides>MAX_SIDES)throw new Error(`Invalid die: d${sides}`);const range=0x100000000,limit=Math.floor(range/sides)*sides,a=new Uint32Array(1);do{crypto.getRandomValues(a);}while(a[0]>=limit);return(a[0]%sides)+1;}
function normalizeExpression(expression){const raw=String(expression||'').trim().toLowerCase().replace(/\s+/g,'');if(!raw)throw new Error('Enter a dice expression such as 1d20 or 2d6+4.');if(!/^[0-9d+\-]+$/.test(raw))throw new Error('Dice expression contains unsupported characters.');return/^[+-]/.test(raw)?raw:`+${raw}`;}
function parse(expression){const normalized=normalizeExpression(expression),parts=[],re=/([+-])(\d*d\d+|\d+)/g;let m,consumed='';while((m=re.exec(normalized))){consumed+=m[0];const sign=m[1]==='-'?-1:1,token=m[2];if(token.includes('d')){const[countRaw,sidesRaw]=token.split('d'),count=countRaw?Number(countRaw):1,sides=Number(sidesRaw);if(!Number.isInteger(count)||count<1||count>MAX_DICE_PER_TERM)throw new Error(`Dice quantity must be 1-${MAX_DICE_PER_TERM}.`);if(!Number.isInteger(sides)||sides<2||sides>MAX_SIDES)throw new Error(`Die sides must be 2-${MAX_SIDES}.`);parts.push({type:'dice',sign,count,sides});}else{const value=Number(token);if(!Number.isSafeInteger(value))throw new Error('Modifier is too large.');parts.push({type:'modifier',sign,value});}}if(consumed!==normalized||!parts.length)throw new Error('Invalid dice expression.');return parts;}
function canonical(parts){return parts.map((p,i)=>{const prefix=p.sign<0?'-':(i?'+':'');return p.type==='dice'?`${prefix}${p.count}d${p.sides}`:`${prefix}${p.value}`;}).join('');}
function roll(expression,{label='Roll'}={}){const parts=parse(expression);let total=0;const terms=parts.map(p=>{if(p.type==='modifier'){total+=p.sign*p.value;return{...p,subtotal:p.sign*p.value};}const rolls=Array.from({length:p.count},()=>secureDie(p.sides)),raw=rolls.reduce((a,b)=>a+b,0),subtotal=p.sign*raw;total+=subtotal;return{...p,rolls,raw,subtotal};});return{id:crypto.randomUUID(),label,expression:canonical(parts),total,terms,at:new Date().toISOString()};}
function rollD20(mode='normal',{modifier=0,label='d20 Roll'}={}){const mod=Number(modifier)||0,first=secureDie(20);let rolls=[first],keptIndex=0;if(mode==='advantage'||mode==='disadvantage'){const second=secureDie(20);rolls.push(second);keptIndex=mode==='advantage'?(second>first?1:0):(second<first?1:0);}const kept=rolls[keptIndex];return{id:crypto.randomUUID(),label,mode,expression:`1d20${mod>=0?'+':''}${mod}`,total:kept+mod,kept,keptIndex,rolls,modifier:mod,natural:kept,critical:kept===20,fumble:kept===1,at:new Date().toISOString(),terms:[{type:'dice',sign:1,count:rolls.length,sides:20,rolls,keptIndex},{type:'modifier',sign:mod<0?-1:1,value:Math.abs(mod),subtotal:mod}]};}
function criticalExpression(expression){return canonical(parse(expression).map(p=>p.type==='dice'?{...p,count:p.count*2}:p));}
function text(result){if(result.mode==='advantage'||result.mode==='disadvantage')return`${result.label}: ${result.rolls.join(', ')}; kept ${result.kept}${result.modifier?` ${result.modifier>=0?'+':'-'} ${Math.abs(result.modifier)}`:''} = ${result.total}`;const chunks=[];for(const t of result.terms){if(t.type==='dice')chunks.push(`${t.sign<0?'-':''}${t.count}d${t.sides} [${t.rolls.join(', ')}]`);else chunks.push(`${t.sign<0?'-':'+'}${t.value}`);}return`${result.label}: ${chunks.join(' ')} = ${result.total}`;}
function outcome(result){const natural=Number(result.natural),terms=(result.terms||[]).filter(t=>t.type==='dice'),raw=terms.flatMap(t=>t.rolls||[]),maximum=terms.reduce((n,t)=>n+(Number(t.sides)||0)*(Number(t.count)||0),0),rolled=raw.reduce((n,v)=>n+Number(v||0),0);if(result.critical||natural===20)return'critical';if(result.fumble||natural===1)return'fumble';if(Number.isFinite(natural))return natural>=15?'high':natural<=5?'low':'normal';if(maximum>0)return rolled>=maximum*.75?'high':rolled<=maximum*.35?'low':'normal';return'normal';}
function impact(result,container){const kind=outcome(result),el=document.createElement('div'),source=container?.querySelector('.diceTray')||container,rect=source?.getBoundingClientRect?.(),x=rect?rect.left+rect.width/2:innerWidth/2,y=rect?rect.top+rect.height/2:innerHeight/2;el.className=`ddRollImpact ddRollImpact--${kind}`;if(kind==='critical'||kind==='high'){el.innerHTML=`<div class="ddImpactFrame"></div><div class="ddSparks">${Array.from({length:14},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div>${kind==='critical'?'<b>CRITICAL</b>':''}`;const sparks=el.querySelector('.ddSparks');sparks.style.position='fixed';sparks.style.left=`${x}px`;sparks.style.top=`${y}px`;}document.body.appendChild(el);container?.closest('.modal')?.classList.add(`ddRollModal--${kind}`);setTimeout(()=>container?.closest('.modal')?.classList.remove(`ddRollModal--${kind}`),kind==='critical'?900:650);setTimeout(()=>el.remove(),kind==='critical'?1050:750);}
function render(container,result){if(!container)return;container.innerHTML='';const kind=outcome(result),dice=[];container.dataset.rollOutcome=kind;if(result.mode==='advantage'||result.mode==='disadvantage'){result.rolls.forEach((value,index)=>dice.push({sides:20,value,kept:index===result.keptIndex}));}else{result.terms.filter(t=>t.type==='dice').forEach(t=>t.rolls.forEach(value=>dice.push({sides:t.sides,value,kept:true,negative:t.sign<0})));}const tray=document.createElement('div');tray.className='diceTray';dice.forEach((d,i)=>{const el=document.createElement('div');el.className=`dieVisual d${d.sides}${d.kept?' kept':' discarded'}${d.negative?' negative':''}`;el.style.setProperty('--delay',`${Math.min(i,20)*32}ms`);el.innerHTML=`<span class="dieType">d${d.sides}</span><strong>${d.value}</strong>`;tray.appendChild(el);});const sum=document.createElement('div');sum.className=`diceTotal ${kind}${result.critical?' critical':''}${result.fumble?' fumble':''}`;sum.innerHTML=`<span>${result.label||'Result'}</span><strong>${result.total}</strong><small>${result.mode&&result.mode!=='normal'?result.mode:''}</small>`;container.append(tray,sum);setTimeout(()=>impact(result,container),result.critical?420:180);}
window.DungeonDice={parse,roll,rollD20,criticalExpression,text,render,secureDie};
})();
