(()=>{
'use strict';
if(window.__DD_FINAL_APP)return;window.__DD_FINAL_APP=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const BLOCK={player_1:1,enemy_1:2,player_2:3,enemy_2:4};
let locked=false,timer=null;
function campaignId(){return localStorage.getItem('ddPreferredCampaign');}
async function readTurn(){const db=window.DungeonDB,cid=campaignId();if(!db?.client||!cid)return{key:'waiting',label:'Waiting for campaign',allowed:false};const session=await db.session(),uid=session?.user?.id;if(!uid)return{key:'waiting',label:'Sign in',allowed:false};const [{data:campaign},{data:mine},{data:reaction}]=await Promise.all([db.client.from('campaigns').select('paused,active_block').eq('id',cid).maybeSingle(),db.client.from('initiative_entries').select('block_index,defeated').eq('campaign_id',cid).eq('user_id',uid).eq('defeated',false).maybeSingle(),db.client.from('reaction_windows').select('id').eq('campaign_id',cid).eq('user_id',uid).eq('status','open').limit(1).maybeSingle()]);if(!campaign)return{key:'waiting',label:'Waiting',allowed:false};if(campaign.paused)return{key:'paused',label:'Campaign paused',allowed:false};if(reaction)return{key:'yourTurn',label:'Reaction ready',allowed:true};if(!campaign.active_block)return{key:'scene',label:'Your scene turn',allowed:true};const allowed=!!mine&&Number(mine.block_index)===BLOCK[campaign.active_block];return allowed?{key:'yourTurn',label:'Your turn',allowed:true}:{key:'waiting',label:'Waiting for turn',allowed:false};}
function applyTurn(turn){locked=!turn.allowed;const badge=$('#playerTurnBadge'),text=$('#playerTurnBadgeText');if(badge)badge.className=`playerTurnBadge ${turn.key}`;if(text)text.textContent=turn.label;const panel=$('#ddV2PlayPanel');panel?.querySelector('.ddV2ActionGroups')?.setAttribute('data-turn-locked',String(locked));$$('[data-v2-action],#ddV2EndTurn',panel||document).forEach(b=>{b.disabled=locked;b.setAttribute('aria-disabled',String(locked));});const primary=$('#primaryActionButton');if(primary){primary.disabled=locked;primary.setAttribute('aria-disabled',String(locked));}document.body.dataset.turn=turn.key;}
async function refresh(){try{applyTurn(await readTurn());}catch(err){console.warn('Turn status refresh failed',err);}}
function relabelUnifiedActions(){const panel=$('#ddV2PlayPanel');if(!panel)return;$$('.ddV2ActionGroup h4',panel).forEach(h=>{if(/actions?|abilities?|features?/i.test(h.textContent||''))h.textContent='Actions & Abilities';});const groups=$$('.ddV2ActionGroup',panel);const actionGroups=groups.filter(g=>/Actions & Abilities/i.test(g.querySelector('h4')?.textContent||''));if(actionGroups.length>1){const first=actionGroups[0].querySelector('.ddV2Actions');for(const extra of actionGroups.slice(1)){extra.querySelectorAll('.ddV2Action').forEach(b=>first?.appendChild(b));extra.remove();}}applyTurn({key:document.body.dataset.turn||'waiting',label:$('#playerTurnBadgeText')?.textContent||'Waiting',allowed:!locked});}
function bindReferenceLayout(){
  $$('.desktopNav [data-page]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`.bottomNav [data-page="${b.dataset.page}"]`)?.click()));
  $('#primaryActionButton')?.addEventListener('click',()=>{const panel=$('#ddV2PlayPanel');if(!panel)return;panel.scrollIntoView({behavior:'smooth',block:'center'});panel.querySelector('.ddV2Action')?.focus();});
  $('#quickRollButton')?.addEventListener('click',()=>$('#freeDiceBtn')?.click());
  const date=$('#adventureClock');if(date)date.textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',hour:'numeric',minute:'2-digit'}).format(new Date());
  const feed=$('#communityFeed'),heading=$('#liveSceneHeading'),syncHeading=()=>{const bodies=$$('.communityMsg.dm .communityBubble .body',feed);const text=bodies.at(-1)?.textContent?.trim();if(text&&heading){const first=text.split(/(?<=[.!?])\s/)[0].slice(0,96);heading.textContent=first+(first.length<text.length&&!/[.!?]$/.test(first)?'…':'');}};if(feed&&heading)new MutationObserver(syncHeading).observe(feed,{childList:true,subtree:true});
}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>{refresh();relabelUnifiedActions();},80);}
function init(){bindReferenceLayout();schedule();window.addEventListener('dd:v2-refresh',schedule);window.addEventListener('dd:campaign-changed',schedule);window.addEventListener('dd:initiative-recorded',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule();});setInterval(refresh,15000);const db=window.DungeonDB,cid=campaignId();if(db?.client&&cid)db.client.channel(`dd-final-turn:${cid}:${crypto.randomUUID()}`).on('postgres_changes',{event:'*',schema:'public',table:'campaigns',filter:`id=eq.${cid}`},schedule).on('postgres_changes',{event:'*',schema:'public',table:'initiative_entries',filter:`campaign_id=eq.${cid}`},schedule).on('postgres_changes',{event:'*',schema:'public',table:'reaction_windows',filter:`campaign_id=eq.${cid}`},schedule).subscribe();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300),{once:true});else setTimeout(init,300);
})();
