(()=>{
'use strict';
if(window.__DD_INTERACTION_UI_V5)return;window.__DD_INTERACTION_UI_V5=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
let pendingInitiative=null,dicePatched=false;
function db(){return window.DungeonDB;}function dice(){return window.DungeonDice;}function rules(){return window.DungeonRulesV2;}function v2(){return window.DungeonDwellersV2;}
function installStyles(){if($('#ddInteractionUiStyles'))return;const s=document.createElement('style');s.id='ddInteractionUiStyles';s.textContent=`.communityComposer{grid-template-columns:minmax(0,1fr) 48px!important;align-items:stretch!important}.communitySendBtn{width:48px!important;min-width:48px!important;height:48px!important;padding:0!important;display:grid!important;place-items:center!important;border:1px solid #f0b650!important;border-radius:14px!important;background:#f0b650!important;color:#342307!important;font-size:28px!important;font-weight:900!important}.ddTokenPanel{position:absolute;z-index:12;left:8px;right:8px;bottom:8px;max-height:55%;overflow:auto;border:1px solid #416159;border-radius:13px;background:rgba(11,24,20,.97);box-shadow:0 12px 30px rgba(0,0,0,.35);padding:10px}.ddTokenPanelTop{display:flex;justify-content:space-between;gap:10px}.ddTokenPanel strong{color:#bfffee;font-size:13px}.ddTokenPanel small{display:block;color:#91aaa2;font-size:9px;margin-top:3px}.ddTokenPanelActions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin-top:9px}.ddTokenPanel button{border:1px solid #416159;border-radius:10px;background:#14241f;color:#dcebe6;padding:7px 8px;font-size:9px;font-weight:800}.ddTokenPanel button.primary{background:#f0b650;color:#342307}.ddTokenPanel button.close{border:0;background:transparent;margin-left:auto}.ddTokenSelectedRing{position:absolute;z-index:7;border:2px solid #54d7bd;border-radius:50%;box-shadow:0 0 14px rgba(84,215,189,.55);pointer-events:none;transform:translate(-50%,-50%)}@media(max-width:420px){.communityComposer{grid-template-columns:minmax(0,1fr) 46px!important}.communitySendBtn{width:46px!important;min-width:46px!important;height:46px!important}.ddTokenPanelActions{grid-template-columns:1fr}}`;document.head.appendChild(s);}
function replaceChatSendButton(){const b=$('#communitySend');if(!b)return;b.className='communitySendBtn';b.setAttribute('aria-label','Send message');b.textContent='›';}
function initiativeRequest(req){return /initiative/i.test(`${req?.label||''} ${req?.reason||''} ${req?.ability||''}`);}
function closeModal(){const root=$('#modalRoot');if(root){root.classList.add('hidden');root.innerHTML='';}}
function showInitiativeGate(req,visibility='party'){const root=$('#modalRoot');if(!root)return;const expression=String(req?.expression||'1d20').replace(/\s+/g,''),mode=['advantage','disadvantage'].includes(req?.mode)?req.mode:'normal';root.innerHTML=`<div class="modalBackdrop"><div class="modal"><div class="eyebrow">Initiative Required</div><h2>Roll Initiative</h2><div class="modalBody"><p>The Dungeon Master has started structured combat.</p><div class="statusLine">${esc(expression)} · ${esc(mode==='normal'?'Normal':mode)}</div><p>Press <strong>Roll Initiative</strong> first. The dice still will not roll until you press the separate <strong>Roll</strong> button.</p></div><div class="buttonRow"><button id="ddInitCancel" class="ghostBtn">Cancel</button><button id="ddInitContinue" class="goldBtn">Roll Initiative</button></div></div></div>`;root.classList.remove('hidden');$('#ddInitCancel').onclick=closeModal;$('#ddInitContinue').onclick=()=>{pendingInitiative={request:req,visibility};closeModal();window.dispatchEvent(new CustomEvent('dd:roll-request',{detail:{request:{...req,__ddInitiativeStage2:true},visibility}}));};}
async function recordInitiative(r){const ctx=pendingInitiative;pendingInitiative=null;if(!ctx||!r)return;try{const database=db(),cid=localStorage.getItem('ddPreferredCampaign'),session=await database.session(),uid=session?.user?.id;if(!cid||!uid)return;const [ch,tokens]=await Promise.all([database.character(cid),database.tokens(cid)]),name=ch?.display_name||ch?.name||ch?.profile?.identity?.name||'Adventurer',row={campaign_id:cid,combatant_key:`player:${uid}`,side:'player',user_id:uid,token_id:(tokens||[]).find(t=>t.owner_user_id===uid)?.id||null,display_name:name,initiative:r.total,state:{verified_roll_id:r.id,requested_by_ai:true,v2:true}};const {error}=await database.client.from('initiative_entries').upsert(row,{onConflict:'campaign_id,combatant_key'});if(error)throw error;window.dispatchEvent(new CustomEvent('dd:initiative-recorded',{detail:{initiative:r.total,rollId:r.id}}));}catch(err){console.warn('Could not record initiative',err);}}
function patchDice(){if(dicePatched)return;const d=dice();if(!d?.roll||!d?.rollD20)return;dicePatched=true;const a=d.roll.bind(d),b=d.rollD20.bind(d);d.roll=(...x)=>{const r=a(...x);if(pendingInitiative)void recordInitiative(r);return r;};d.rollD20=(...x)=>{const r=b(...x);if(pendingInitiative)void recordInitiative(r);return r;};}
window.addEventListener('dd:roll-request',e=>{const d=e.detail||{},req=d.request||d;if(req?.__ddInitiativeStage2||!initiativeRequest(req))return;e.stopImmediatePropagation();showInitiativeGate(req,d.visibility==='private'?'private':'party');});
function specFor(map){const s=map?.generated_spec||{};return{widthCells:Number(s.widthCells||map?.width||30),heightCells:Number(s.heightCells||map?.height||22)};}
function pos(t,s){let x=Number(t?.x),y=Number(t?.y);if(!Number.isFinite(x))x=s.widthCells/2;if(!Number.isFinite(y))y=s.heightCells/2;if(!(t?.state?.position_mode==='grid'||(x<=s.widthCells&&y<=s.heightCells))){x=x/100*s.widthCells;y=y/100*s.heightCells;}return{x:clamp(x,0,s.widthCells),y:clamp(y,0,s.heightCells)};}
function closePanel(frame){frame?.querySelectorAll('.ddTokenPanel,.ddTokenSelectedRing').forEach(x=>x.remove());}
function chatAction(text,auto=true){$('#ccParty')?.click();setTimeout(()=>{const input=$('#communityInput'),ask=$('#communityAskDM');if(!input)return;input.value=text;input.focus();if(auto&&ask)ask.click();},0);}
async function actionButtons(token,own){if(own)return[{label:'Open Character',kind:'character'}];const type=String(token.token_type||'token').toLowerCase();if(type==='npc')return[{label:`Talk to ${token.name||'NPC'}`,kind:'talk'},{label:'Interact',kind:'interact'}];if(type!=='enemy')return[{label:'Interact',kind:'interact'}];const ch=v2()?.state?.character||await db().character(localStorage.getItem('ddPreferredCampaign')),actions=rules()?.actionCatalog(ch)||[],use=actions.filter(a=>['weapon','attack','spell','feature','item'].includes(a.kind)||['basic:grapple','basic:shove','basic:help'].includes(a.id)).filter(a=>rules().resourceAvailable(ch,a.resource)).slice(0,12);return use.map(a=>({label:a.name,kind:'v2',action:a}));}
async function showPanel(frame,token,opts,hit){closePanel(frame);const wrap=frame.querySelector('.ddMapCanvasWrap');if(!wrap)return;const own=token.owner_user_id===opts.userId||token.character_id===opts.characterId,type=String(token.token_type||'token').toLowerCase(),ring=document.createElement('div');ring.className='ddTokenSelectedRing';ring.style.left=`${hit.x}px`;ring.style.top=`${hit.y}px`;ring.style.width=`${hit.size}px`;ring.style.height=`${hit.size}px`;wrap.appendChild(ring);const panel=document.createElement('div');panel.className='ddTokenPanel',buttons=await actionButtons(token,own),hp=token.state?.hp,max=token.state?.maxHp;panel.innerHTML=`<div class="ddTokenPanelTop"><div><strong>${esc(token.name||'Token')}</strong><small>${esc(own?'Your character':type)}${Number.isFinite(Number(hp))&&Number.isFinite(Number(max))?` · ${hp}/${max} HP`:''}</small></div><button class="close" data-close>✕</button></div><div class="ddTokenPanelActions">${buttons.map((b,i)=>`<button ${i===0?'class="primary"':''} data-act="${i}">${esc(b.label)}</button>`).join('')}</div>`;wrap.appendChild(panel);$('[data-close]',panel).onclick=()=>closePanel(frame);$$('[data-act]',panel).forEach(b=>b.onclick=async()=>{const a=buttons[Number(b.dataset.act)];if(a.kind==='character')document.querySelector('[data-page="character"],.quick[data-page="character"]')?.click();else if(a.kind==='talk')chatAction(`I speak to ${token.name}.`);else if(a.kind==='interact')chatAction(`I interact with ${token.name}.`);else if(a.kind==='v2'){closePanel(frame);await v2()?.runServerAction(a.action,token.character_id||token.id);} });}
function attach(frame,opts){const canvas=frame.querySelector('.ddMapCanvas');if(!canvas||!opts?.map||canvas.dataset.ddV2Tokens==='1')return;canvas.dataset.ddV2Tokens='1';const tokens=(opts.tokens||[]).filter(t=>!t.map_id||t.map_id===opts.map.id),s=specFor(opts.map);let down=null,moved=false;const hit=e=>{const r=canvas.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top,sx=r.width/s.widthCells,sy=r.height/s.heightCells;let best=null;for(const t of tokens){const p=pos(t,s),x=p.x*sx,y=p.y*sy,rad=Math.max(18,Math.min(sx,sy)*.58),d=Math.hypot(px-x,py-y);if(d<=rad&&(!best||d<best.d))best={token:t,d,x,y,size:rad*2};}return best;};canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};moved=false;},true);canvas.addEventListener('pointermove',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)moved=true;},true);canvas.addEventListener('pointerup',e=>{const drag=moved;down=null;moved=false;if(drag)return;const h=hit(e);if(h)void showPanel(frame,h.token,opts,h);else closePanel(frame);});const tip=frame.querySelector('.ddMapTip');if(tip)tip.textContent='Tap tokens for actions · drag your token to move';}
function patchMap(){const engine=window.DungeonMapEngine;if(!engine?.renderTactical||engine.__ddV2TokenPatched)return;engine.__ddV2TokenPatched=true;const original=engine.renderTactical.bind(engine);engine.renderTactical=(frame,opts={})=>{const out=original(frame,opts);attach(frame,opts);return out;};}
function init(){installStyles();replaceChatSendButton();document.getElementById('rollInitiativeBtn')?.remove();patchDice();patchMap();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();window.addEventListener('load',()=>{replaceChatSendButton();patchDice();patchMap();},{once:true});
})();

