(()=>{
'use strict';
if(window.__DD_NAV_LAYOUT_V10)return;window.__DD_NAV_LAYOUT_V10=true;
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const characterIcon='<svg viewBox="0 0 48 48"><circle cx="24" cy="15" r="7"/><path d="M11 41c1-11 6-17 13-17s12 6 13 17"/></svg>';
const npcIcon='<svg viewBox="0 0 48 48"><circle cx="24" cy="15" r="8"/><path d="M10 41c1-10 6-16 14-16s13 6 14 16M6 36c1-6 4-10 9-12m27 12c-1-6-4-10-9-12"/></svg>';
const norm=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]+/g,''),clean=v=>String(v??'').trim();
function pdfFields(p){return p?.sourceData?.pdfFields||p?.importedSections?.find(x=>x?.name==='All PDF fields')?.data||{}}
function getField(f,...names){for(const n of names){const nn=norm(n);for(const [k,v] of Object.entries(f)){if(norm(k)===nn&&clean(v))return clean(v)}}return''}
function asNum(v){const m=String(v??'').match(/[+-]?\d+(?:\.\d+)?/);return m?Number(m[0]):null}
function likelyWeapon(name){return /\b(club|dagger|greatclub|handaxe|javelin|light hammer|mace|quarterstaff|sickle|spear|crossbow|dart|shortbow|sling|battleaxe|flail|glaive|greataxe|greatsword|halberd|lance|longsword|maul|morningstar|pike|rapier|scimitar|shortsword|trident|war pick|warhammer|whip|longbow|blowgun|net|musket|pistol|unarmed strike)\b/i.test(String(name||''))}
function pdfGear(p){const f=pdfFields(p),out=[];for(let i=0;i<50;i++){const name=getField(f,`Eq Name${i}`);if(name)out.push({name,quantity:getField(f,`Eq Qty${i}`)||'1',weight:getField(f,`Eq Weight${i}`)||'',_type:likelyWeapon(name)?'weapon':'gear'})}return out}
function pdfWeapons(p){const f=pdfFields(p),out=[];for(let i=1;i<=6;i++){const name=getField(f,i===1?'Wpn Name':`Wpn Name ${i}`,`Wpn Name${i}`);if(!name)continue;out.push({name,attackBonusText:getField(f,`Wpn${i} AtkBonus`,`Wpn${i} AtkBonus `),attackBonus:asNum(getField(f,`Wpn${i} AtkBonus`,`Wpn${i} AtkBonus `)),damage:getField(f,`Wpn${i} Damage`,`Wpn${i} Damage `),range:getField(f,`Wpn${i} Range`,`Wpn${i} Range `),properties:getField(f,`Wpn${i} Properties`,`Wpn${i} Properties `),detail:getField(f,`Wpn Notes ${i}`),_type:'weapon'})}return out}
function normalizeCharacter(row){if(!row?.profile)return row;const p=structuredClone(row.profile),e=p.equipment??={};let gear=[...(e.gear||[])],weapons=[...(e.weapons||[])];if(!gear.length)gear=pdfGear(p);const attacks=(p.attacks||[]).filter(x=>x?.name).map(x=>({name:x.name,attackBonusText:x.attackBonusText??x.attackBonus,attackBonus:asNum(x.attackBonusText??x.attackBonus),damage:x.damage,range:x.range,properties:x.properties||x.rulesProfile,detail:x.detail||x.description,_type:'weapon'}));for(const w of [...attacks,...pdfWeapons(p)])if(!weapons.some(x=>norm(x.name)===norm(w.name)))weapons.push(w);for(const g of gear)if((g._type==='weapon'||likelyWeapon(g.name))&&!weapons.some(w=>norm(w.name)===norm(g.name)))weapons.push({...g,_type:'weapon'});const names=new Set(weapons.map(x=>norm(x.name)));gear=gear.map(x=>names.has(norm(x.name))?{...x,_type:'weapon'}:x);for(const w of weapons){const g=gear.find(x=>norm(x.name)===norm(w.name));if(g){w.quantity??=g.quantity;w.weight??=g.weight}w._type='weapon'}e.weapons=weapons;e.gear=gear;p.equipment=e;return{...row,profile:p}}
function patchCharacterReads(){const db=window.DungeonDB;if(!db||db.__characterInventoryPatched)return;const original=db.character?.bind(db);if(!original)return;db.__characterInventoryPatched=true;db.character=async id=>normalizeCharacter(await original(id));db.normalizeCharacterInventory=normalizeCharacter}
function inventoryItems(p){const e=p?.equipment||{},seen=new Set(),out=[];for(const [type,list] of [['weapon',e.weapons],['armor',e.armor],['consumable',e.consumables],['gear',e.gear],['magic',p?.magicItems]])for(const raw of list||[]){if(!raw?.name)continue;const key=norm(raw.name);if(seen.has(`${type}:${key}`)||type==='gear'&&seen.has(`weapon:${key}`))continue;seen.add(`${type}:${key}`);out.push({...raw,_type:raw._type||type})}return out}
function detailRows(i){const rows=[['Type',i._type],['Quantity',i.quantity??i.qty],['Weight',i.weight],['Attack Bonus',i.attackBonusText??i.attackBonus],['Damage',i.damage],['Range',i.range],['Properties',i.properties||i.rulesProfile],['Effect',i.effect],['Notes',i.detail||i.description]];return rows.filter(([,v])=>v!==null&&v!==undefined&&clean(v)!=='').map(([k,v])=>`<div class="invDetailRow"><strong>${esc(k)}</strong><span>${esc(Array.isArray(v)?v.join(', '):v)}</span></div>`).join('')}
function installInventoryStyles(){if($('#ddInventoryStyles'))return;const s=document.createElement('style');s.id='ddInventoryStyles';s.textContent=`.characterInventoryList{display:grid;gap:9px;margin-top:10px}.inventoryItem{border:1px solid #6f5428;border-radius:12px;background:#080a0d;overflow:hidden}.inventoryItem summary{cursor:pointer;list-style:none;padding:12px;display:flex;justify-content:space-between;gap:10px;align-items:center}.inventoryItem summary::-webkit-details-marker{display:none}.inventoryItem summary strong{color:#e7c77f}.inventoryItem summary>span{color:#969da5;font-size:11px;text-align:right}.inventoryItem[open] summary{border-bottom:1px solid #3e301b}.invDetails{padding:11px 12px;display:grid;gap:7px}.invDetailRow{display:grid;grid-template-columns:105px minmax(0,1fr);gap:10px;font-size:11px}.invDetailRow strong{color:#cfae68}.invDetailRow span{color:#d5d9de}.weaponBadge{display:inline-block;border:1px solid #9f7836;border-radius:999px;padding:2px 7px;color:#e5c270;font-size:9px;margin-left:7px}`;document.head.appendChild(s)}
async function renderInventory(){const root=$('#inventoryContent'),page=$('#inventoryPage');if(!root||!page?.classList.contains('active'))return;const db=window.DungeonDB,cid=localStorage.getItem('ddPreferredCampaign');if(!db||!cid)return;try{const ch=await db.character(cid),p=ch?.profile||{},items=inventoryItems(p);root.innerHTML=`<div class="eyebrow">${esc(ch?.name||p.identity?.name||'Character')} Inventory</div><div class="characterInventoryList">${items.map(i=>{const sub=[i._type==='weapon'?'Weapon':i._type,i.damage,i.range,i.quantity!=null?`Qty ${i.quantity}`:null].filter(Boolean).join(' · ');return `<details class="inventoryItem"><summary><strong>${esc(i.name)}${i._type==='weapon'?'<span class="weaponBadge">Weapon</span>':''}</strong><span>${esc(sub)}</span></summary><div class="invDetails">${detailRows(i)||'<span class="statusLine">No additional item details recorded.</span>'}</div></details>`}).join('')||'<div class="statusLine">No inventory recorded for the selected character.</div>'}</div>`}catch(e){root.innerHTML=`<div class="statusLine bad">Could not load character inventory: ${esc(e.message||e)}</div>`}}
function apply(){const bottomNpc=$('.bottomNav [data-page="npc"]');if(bottomNpc&&!bottomNpc.dataset.ddSwapped){bottomNpc.dataset.page='character';bottomNpc.dataset.ddSwapped='1';bottomNpc.innerHTML=`${characterIcon}<span>Character</span>`;bottomNpc.setAttribute('aria-label','Character sheet')}const quickCharacter=$('.quickGrid .quick[data-page="character"]');if(quickCharacter&&!quickCharacter.dataset.ddSwapped){quickCharacter.dataset.page='npc';quickCharacter.dataset.ddSwapped='1';quickCharacter.innerHTML=`${npcIcon}<span>NPCs</span>`;quickCharacter.setAttribute('aria-label','NPCs')}const pdfLabel=document.querySelector('label[for="characterPdf"]');if(pdfLabel)pdfLabel.textContent='Import PDF';installInventoryStyles()}
patchCharacterReads();window.addEventListener('dd:db-ready',patchCharacterReads,{once:true});
document.addEventListener('click',e=>{if(e.target?.closest?.('[data-page="inventory"]'))setTimeout(renderInventory,0)},true);
window.addEventListener('dd:character-selected',()=>setTimeout(renderInventory,0));
window.addEventListener('dd:character-imported',()=>setTimeout(renderInventory,0));
document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(renderInventory,0)});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
window.DungeonInventory={render:renderInventory,normalizeCharacter};
})();