(()=>{
'use strict';
if(window.DungeonBackupV2)return;
const $=(s,r=document)=>r.querySelector(s);
const DB=()=>window.DungeonDB;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function cid(){return localStorage.getItem('ddPreferredCampaign');}
function toast(text,type=''){const t=$('#toast');if(!t)return;t.textContent=text;t.className=`toast show ${type}`;clearTimeout(t._b2);t._b2=setTimeout(()=>t.className='toast',3600);}
function modal(title,html){const root=$('#modalRoot');if(!root)return null;root.innerHTML=`<div class="modalBackdrop"><div class="modal"><div class="eyebrow">Campaign Safety</div><h2>${esc(title)}</h2><div class="modalBody">${html}</div></div></div>`;root.classList.remove('hidden');return root;}
function close(){const r=$('#modalRoot');if(r){r.classList.add('hidden');r.innerHTML='';}}
async function exportBackup(){const id=cid();if(!id)return;try{toast('Building campaign backup...');const {data,error}=await DB().client.functions.invoke('campaign-backup',{body:{campaignId:id,mode:'export'}});if(error)throw error;if(data?.ok===false)throw new Error(data.error);const blob=new Blob([JSON.stringify(data.backup,null,2)],{type:'application/json'}),a=document.createElement('a'),name=String(data.backup?.campaign?.name||'campaign').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase();a.href=URL.createObjectURL(blob);a.download=`dungeon-dwellers-${name||'campaign'}-v2-backup.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Campaign backup exported.','ok');}catch(e){toast(e.message||String(e),'bad');}}
async function restoreFile(file){const id=cid();if(!id||!file)return;try{const backup=JSON.parse(await file.text()),campaign=await DB().campaign(id);const root=modal('Restore Campaign Backup',`<p class="statusLine bad">This replaces the gameplay state of <strong>${esc(campaign.name)}</strong> with the selected V2 backup. Members are not removed, but maps, characters, tokens, initiative, reactions, quests, knowledge, story, chat, NPC state, memory and encounter state are replaced.</p><label class="fieldLabel">Type the current campaign name to confirm<input id="ddRestoreName" autocomplete="off"></label><div id="ddRestoreStatus" class="statusLine">Backup: ${esc(backup?.campaign?.name||'Unknown')}</div><div class="buttonRow" style="margin-top:12px"><button id="ddRestoreCancel" class="ghostBtn">Cancel</button><button id="ddRestoreConfirm" class="dangerBtn" disabled>Restore Backup</button></div>`);const input=$('#ddRestoreName',root),btn=$('#ddRestoreConfirm',root);input.oninput=()=>btn.disabled=input.value.trim()!==campaign.name;$('#ddRestoreCancel',root).onclick=close;btn.onclick=async()=>{if(input.value.trim()!==campaign.name)return;btn.disabled=true;btn.textContent='Restoring...';try{const {data,error}=await DB().client.functions.invoke('campaign-backup',{body:{campaignId:id,mode:'restore',backup,confirmName:campaign.name}});if(error)throw error;if(data?.ok===false)throw new Error(data.error);close();toast('Campaign restored. Reloading...','ok');setTimeout(()=>location.reload(),500);}catch(e){btn.disabled=false;btn.textContent='Restore Backup';$('#ddRestoreStatus',root).textContent=e.message||String(e);$('#ddRestoreStatus',root).className='statusLine bad';}};}catch(e){toast(`Backup file could not be read: ${e.message||e}`,'bad');}}
function install(){const ownerPanel=$('#ownerPanel .buttonRow');if(!ownerPanel||$('#ddBackupExport'))return;const ex=document.createElement('button');ex.id='ddBackupExport';ex.className='ghostBtn';ex.textContent='Export Backup';ex.onclick=exportBackup;const label=document.createElement('label');label.className='ghostBtn';label.textContent='Restore Backup';label.htmlFor='ddBackupImport';const input=document.createElement('input');input.id='ddBackupImport';input.type='file';input.accept='application/json,.json';input.hidden=true;input.onchange=()=>{const f=input.files?.[0];if(f)restoreFile(f);input.value='';};ownerPanel.append(ex,label,input);}
window.DungeonBackupV2={exportBackup,restoreFile};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();setTimeout(install,500);
})();