(()=>{
'use strict';
if(window.DungeonCombatV2)return;
const $=(s,r=document)=>r.querySelector(s);
const DB=()=>window.DungeonDB;
let busy=false,channel=null,boundarySyncKey='';
function cid(){return localStorage.getItem('ddPreferredCampaign');}
function toast(text,type=''){const t=$('#toast');if(!t)return;t.textContent=text;t.className=`toast show ${type}`;clearTimeout(t._c2);t._c2=setTimeout(()=>t.className='toast',3600);}
async function state(){const id=cid();if(!id||!DB())return null;const [campaign,session,initiative,submission]=await Promise.all([DB().campaign(id),DB().session(),DB().initiative(id),Promise.resolve(null)]),uid=session?.user?.id,mine=initiative.find(e=>e.user_id===uid&&!e.defeated),idx={player_1:1,enemy_1:2,player_2:3,enemy_2:4}[campaign.active_block]||0;let sub=null;if(uid&&idx&&(idx===1||idx===3))sub=await DB().myTurnSubmission(id,campaign.round_number,idx);return{campaign,uid,mine,idx,sub};}
async function endTurn(){if(busy)return;busy=true;try{const id=cid(),{data,error}=await DB().client.functions.invoke('dungeon-combat',{body:{campaignId:id,operation:'end_turn'}});if(error)throw error;if(data?.ok===false)throw new Error(data.error);if(data.boundaryRequired){toast(`Resolve ${data.pending||1} required end-of-turn roll${data.pending===1?'':'s'} first.`,'warn');window.dispatchEvent(new CustomEvent('dd:v2-refresh'));return;}if(data.advanced)toast(data.ended?'Combat ended.':'Block complete. Enemy actions resolved and the next player block is active.','ok');else toast(`Turn submitted. Waiting for ${data.waitingFor||0} player${data.waitingFor===1?'':'s'} in this block.`,'ok');window.dispatchEvent(new CustomEvent('dd:v2-refresh'));setTimeout(render,250);}catch(e){toast(e.message||String(e),'bad');}finally{busy=false;}}
async function syncBoundary(s){const key=`${s.campaign.id}:${s.campaign.round_number}:${s.idx}:${s.uid}`;if(boundarySyncKey===key)return;boundarySyncKey=key;try{const {data,error}=await DB().client.functions.invoke('dungeon-combat',{body:{campaignId:s.campaign.id,operation:'sync_boundary'}});if(error)throw error;if(data?.pending)window.dispatchEvent(new CustomEvent('dd:v2-refresh'));}catch{boundarySyncKey='';}}
async function recover(){if(busy)return;busy=true;try{const {data,error}=await DB().client.functions.invoke('dungeon-combat',{body:{campaignId:cid(),operation:'recover_advance'}});if(error)throw error;if(data?.ok===false)throw new Error(data.error);toast('Combat block recovered.','ok');window.dispatchEvent(new CustomEvent('dd:v2-refresh'));}catch(e){toast(e.message||String(e),'bad');}finally{busy=false;}}
async function render(){document.getElementById('startCombatBtn')?.remove();document.getElementById('advanceBlockBtn')?.remove();const panel=$('#ddV2PlayPanel');if(!panel)return;let bar=$('#ddV2CombatBar',panel);if(!bar){bar=document.createElement('div');bar.id='ddV2CombatBar';bar.className='ddV2Toolbar';panel.appendChild(bar);}try{const s=await state();if(!s?.campaign?.active_block){boundarySyncKey='';bar.innerHTML='';return;}const playerBlock=s.idx===1||s.idx===3,own=playerBlock&&s.mine&&Number(s.mine.block_index)===s.idx;if(own)void syncBoundary(s);if(own&&!s.sub)bar.innerHTML='<button id="ddV2EndTurn" class="goldBtn">End My Turn</button><span class="ddV2Chip">Required saves resolve before the turn can end</span>';else if(own&&s.sub)bar.innerHTML='<span class="ddV2Chip">Turn submitted · waiting for your block</span>';else if(playerBlock)bar.innerHTML='<span class="ddV2Chip">Waiting for the active player block</span>';else bar.innerHTML='<span class="ddV2Chip">Enemy block resolving automatically</span>';$('#ddV2EndTurn',bar)?.addEventListener('click',endTurn);}catch{}}
async function subscribe(){const id=cid();if(!id||!DB())return;if(channel)DB().client.removeChannel(channel);channel=DB().client.channel(`dd-v2-combat-ui:${id}:${crypto.randomUUID()}`).on('postgres_changes',{event:'*',schema:'public',table:'campaigns',filter:`id=eq.${id}`},render).on('postgres_changes',{event:'*',schema:'public',table:'turn_submissions',filter:`campaign_id=eq.${id}`},render).subscribe();render();}
function installRecovery(){const row=$('#ownerPanel .buttonRow');if(!row||$('#ddV2RecoverCombat'))return;const b=document.createElement('button');b.id='ddV2RecoverCombat';b.className='ghostBtn';b.textContent='Recover Combat Block';b.onclick=recover;row.appendChild(b);}
function init(){document.getElementById('startCombatBtn')?.remove();document.getElementById('advanceBlockBtn')?.remove();installRecovery();subscribe();setTimeout(()=>{installRecovery();render();},500);}
window.DungeonCombatV2={endTurn,recover,render};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();

