(()=>{
'use strict';
if(window.DungeonRulesV2)return;
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const norm=v=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const arr=v=>Array.isArray(v)?v:[];
const first=(...v)=>v.find(x=>x!==undefined&&x!==null&&x!=='');
const ALIAS={str:'strength',dex:'dexterity',con:'constitution',int:'intelligence',wis:'wisdom',cha:'charisma'};
const SIZE={tiny:.5,small:1,medium:1,large:2,huge:3,gargantuan:4};
const XP=[0,300,900,2700,6500,14000,23000,34000,48000,64000,85000,100000,120000,140000,165000,195000,225000,265000,305000,355000];
const FLAGS={blinded:{attackDisadvantage:1,attackersAdvantage:1},frightened:{attackDisadvantage:1},grappled:{speedZero:1},incapacitated:{noActions:1,noReactions:1},invisible:{attackAdvantage:1,attackersDisadvantage:1},paralyzed:{noActions:1,noReactions:1,speedZero:1,attackersAdvantage:1},petrified:{noActions:1,noReactions:1,speedZero:1,attackersAdvantage:1},poisoned:{attackDisadvantage:1,checkDisadvantage:1},prone:{attackDisadvantage:1},restrained:{speedZero:1,attackDisadvantage:1,attackersAdvantage:1},stunned:{noActions:1,noReactions:1,speedZero:1,attackersAdvantage:1},unconscious:{noActions:1,noReactions:1,speedZero:1,attackersAdvantage:1}};
function p(c){return c?.profile||c||{};} function d(c){return p(c).defenses||(p(c).defenses={});}
function abilityEntry(c,key){const k=ALIAS[norm(key)]||norm(key);return p(c).abilities?.[k]||p(c).abilities?.[k.slice(0,3)]||{};}
function abilityMod(c,key){const e=abilityEntry(c,key);if(Number.isFinite(Number(e.mod)))return Number(e.mod);if(Number.isFinite(Number(e.modifier)))return Number(e.modifier);return Math.floor((n(e.score,10)-10)/2);}
function proficiency(c){return n(first(p(c).proficiencyBonus,p(c).proficiency,p(c).identity?.proficiencyBonus),2);}
function conditions(c){return arr(d(c).conditions).map(x=>typeof x==='string'?{name:x}:{...x,name:x?.name||x?.condition||''}).filter(x=>x.name);}
function conditionFlags(c){const out={};for(const q of conditions(c))for(const[k,v]of Object.entries(FLAGS[norm(q.name)]||{}))if(v)out[k]=true;return out;}
const hp=c=>n(first(c?.hp,d(c).currentHp),0),maxHp=c=>Math.max(0,n(first(c?.max_hp,d(c).maxHp),hp(c))),tempHp=c=>Math.max(0,n(first(d(c).tempHp,d(c).temporaryHp),0)),ac=c=>n(first(c?.ac,d(c).armorClass),10);
function speed(c){const raw=first(p(c).movement?.walk,p(c).speed,p(c).identity?.speed,d(c).speed,30),m=String(raw).match(/\d+/);return typeof raw==='number'?raw:m?Number(m[0]):30;}
function size(c){return norm(first(p(c).identity?.size,p(c).size,'medium'))||'medium';} const sizeCells=c=>SIZE[size(c)]||1;
function level(c){return Math.max(1,n(first(p(c).identity?.level,p(c).level),1));} function xp(c){return Math.max(0,n(first(p(c).identity?.xp,p(c).xp,p(c).experience),0));}
function levelStatus(c){let target=1;for(let i=0;i<XP.length;i++)if(xp(c)>=XP[i])target=i+1;const lv=level(c),next=lv>=20?null:XP[lv];return{level:lv,xp:xp(c),eligible:target>lv,recommendedLevel:target,nextXp:next,remaining:next==null?0:Math.max(0,next-xp(c))};}
function resourceValue(c,key){const r=(p(c).resources||(p(c).resources={}))[key];return r&&typeof r==='object'?n(first(r.current,r.value,r.remaining),0):n(r,0);} function resourceMax(c,key){const r=p(c).resources?.[key];return r&&typeof r==='object'?n(first(r.max,r.maximum,r.total),resourceValue(c,key)):resourceValue(c,key);}
function parseDice(text){const m=String(text||'').replace(/\s+/g,'').match(/(\d+)d(\d+)([+-]\d+)?/i);return m?{count:n(m[1],1),sides:n(m[2],20),mod:n(m[3],0),expression:m[0]}:null;}
function parseRange(raw){if(Number.isFinite(Number(raw)))return{normal:Number(raw),long:null,unit:'ft'};const s=String(raw||'').toLowerCase();if(s.includes('self'))return{normal:0,long:0,self:true,unit:'ft'};if(s.includes('touch'))return{normal:5,long:5,touch:true,unit:'ft'};const q=s.match(/(\d+)\s*\/\s*(\d+)/),m=s.match(/(\d+)\s*(?:ft|feet|foot)/);return q?{normal:+q[1],long:+q[2],unit:'ft'}:{normal:m?+m[1]:5,long:null,unit:'ft'};}
const aid=(k,name,i=0)=>`${k}:${norm(name)||i}`;
function normalizeWeapon(w,i=0){const name=w?.name||`Weapon ${i+1}`,ab=first(w.attackBonus,w.attack_bonus,w.toHit,w.rulesProfile?.attackBonus);return{id:aid('weapon',name,i),kind:'weapon',name,activation:String(first(w.activation,w.actionType,'action')).toLowerCase(),attackBonus:Number.isFinite(Number(ab))?+ab:null,damage:String(first(w.damage,w.damageDice,w.rulesProfile?.damage,'')),damageType:first(w.damageType,w.rulesProfile?.damageType),range:parseRange(first(w.range,w.rulesProfile?.range,w.properties)),properties:String(first(w.properties,w.rulesProfile?.properties,'')),resource:w.ammunition?{key:norm(w.ammunition),cost:1}:null,target:'creature',source:w};}
function normalizeAttack(a,i=0){const name=a?.name||`Attack ${i+1}`;return{id:a.id||aid('attack',name,i),kind:a.kind||'attack',name,activation:String(first(a.activation,a.actionType,'action')).toLowerCase(),attackBonus:Number.isFinite(Number(first(a.attackBonus,a.toHit)))?Number(first(a.attackBonus,a.toHit)):null,saveAbility:first(a.saveAbility,a.save),saveDC:Number.isFinite(Number(first(a.saveDC,a.dc)))?Number(first(a.saveDC,a.dc)):null,damage:String(first(a.damage,a.damageDice,'')),damageType:a.damageType,healing:String(first(a.healing,a.heal,'')),range:parseRange(first(a.range,a.reach)),resource:a.resource||null,target:a.target||'creature',source:a};}
function normalizeSpell(s,i=0){const name=s?.name||`Spell ${i+1}`,lv=n(s.level,0);return{id:s.id||aid('spell',name,i),kind:'spell',name,activation:String(first(s.activation,s.castingTime,'action')).toLowerCase(),level:lv,range:parseRange(s.range),attackBonus:Number.isFinite(Number(first(s.attackBonus,s.spellAttackBonus)))?Number(first(s.attackBonus,s.spellAttackBonus)):null,saveAbility:first(s.saveAbility,s.save),saveDC:Number.isFinite(Number(first(s.saveDC,s.dc)))?Number(first(s.saveDC,s.dc)):null,damage:String(first(s.damage,s.damageDice,'')),damageType:s.damageType,healing:String(first(s.healing,s.heal,'')),concentration:!!s.concentration,duration:s.duration||null,area:s.area||null,target:s.target||'creature',resource:lv>0?{spellSlotLevel:lv,cost:1}:null,source:s};}
function normalizeFeature(f,i=0){const name=f?.name||`Feature ${i+1}`;return{id:f.id||aid('feature',name,i),kind:'feature',name,activation:String(first(f.activation,f.actionType,f.useType,'passive')).toLowerCase(),range:parseRange(f.range),attackBonus:Number.isFinite(Number(f.attackBonus))?Number(f.attackBonus):null,saveAbility:first(f.saveAbility,f.save),saveDC:Number.isFinite(Number(first(f.saveDC,f.dc)))?Number(first(f.saveDC,f.dc)):null,damage:String(first(f.damage,f.damageDice,'')),healing:String(first(f.healing,f.heal,'')),resource:f.resource||((f.uses||f.maxUses)?{key:norm(name),cost:1}:null),target:f.target||null,source:f};}
function normalizeItem(it,i=0){const name=it?.name||`Item ${i+1}`,usable=it?.usable!==false&&(it?.effect||it?.healing||it?.damage||it?.consumable||it?.category==='consumable'||Number.isFinite(Number(it?.charges)));return{id:it.id||aid('item',name,i),kind:'item',name,activation:String(first(it.activation,it.actionType,'action')).toLowerCase(),range:parseRange(it.range),damage:String(first(it.damage,'')),healing:String(first(it.healing,it.heal,'')),target:it.target||null,quantity:n(first(it.quantity,it.qty),1),charges:n(it.charges,0),usable,source:it};}
function actionCatalog(c,{includePassive=false}={}){const pr=p(c),eq=pr.equipment||{},out=[];arr(eq.weapons).forEach((x,i)=>out.push(normalizeWeapon(x,i)));arr(pr.attacks).forEach((x,i)=>out.push(normalizeAttack(x,i)));arr(first(pr.spellcasting?.spells,pr.spells,[])).forEach((x,i)=>out.push(normalizeSpell(x,i)));[...arr(pr.classFeatures),...arr(pr.speciesFeatures),...arr(pr.backgroundFeatures),...arr(pr.feats),...arr(pr.features)].forEach((x,i)=>{const a=normalizeFeature(x,i);if(includePassive||a.activation!=='passive')out.push(a);});[...arr(eq.consumables),...arr(eq.magicItems),...arr(pr.magicItems),...arr(eq.gear).filter(x=>x?.usable||x?.effect||x?.charges)].forEach((x,i)=>{const a=normalizeItem(x,i);if(a.usable)out.push(a);});out.push({id:'basic:dash',kind:'basic',name:'Dash',activation:'action'},{id:'basic:disengage',kind:'basic',name:'Disengage',activation:'action'},{id:'basic:dodge',kind:'basic',name:'Dodge',activation:'action'},{id:'basic:help',kind:'basic',name:'Help',activation:'action',target:'creature',range:{normal:5,long:5}},{id:'basic:hide',kind:'basic',name:'Hide',activation:'action'},{id:'basic:ready',kind:'basic',name:'Ready',activation:'action'},{id:'basic:search',kind:'basic',name:'Search',activation:'action'},{id:'basic:study',kind:'basic',name:'Study',activation:'action'},{id:'basic:influence',kind:'basic',name:'Influence',activation:'action'},{id:'basic:grapple',kind:'basic',name:'Grapple',activation:'attack',target:'creature',range:{normal:5,long:5}},{id:'basic:shove',kind:'basic',name:'Shove',activation:'attack',target:'creature',range:{normal:5,long:5}});const seen=new Set();return out.filter(a=>{if(seen.has(a.id))return false;seen.add(a.id);return true;});}
function slots(c){return p(c).spellcasting?.slots||{};} function slotAvailable(c,lv){if(!lv)return true;const r=slots(c)[lv]??slots(c)[String(lv)]??slots(c)[`level${lv}`];return r&&typeof r==='object'?n(first(r.current,r.remaining,r.value),0)>0:n(r,0)>0;} function resourceAvailable(c,res){if(!res)return true;if(res.spellSlotLevel)return slotAvailable(c,res.spellSlotLevel);return !res.key||resourceValue(c,res.key)>=n(res.cost,1);}
function distanceFt(a,b,cellSize=5){if(!a||!b)return Infinity;return Math.max(Math.abs(n(a.x)-n(b.x)),Math.abs(n(a.y)-n(b.y)))*n(cellSize,5);}
function lineIntersects(a,b,c,e){const cross=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x),c1=cross(a,b,c),c2=cross(a,b,e),c3=cross(c,e,a),c4=cross(c,e,b);return(c1===0&&c2===0)||(c1*c2<=0&&c3*c4<=0);}
function lineOfSight(spec,a,b){if(!spec||!a||!b)return{clear:true,cover:0};let cover=0;for(const w of arr(spec.walls))if(w.blocksVision!==false&&lineIntersects(a,b,{x:n(w.x1),y:n(w.y1)},{x:n(w.x2),y:n(w.y2)}))return{clear:false,cover:3,reason:'A wall blocks line of sight.'};for(const door of arr(spec.doors)){if(door.isOpen)continue;const horizontal=Number(door.orientation||0)%180===0,c={x:n(door.x)+(horizontal?-.5:0),y:n(door.y)+(horizontal?0:-.5)},e={x:n(door.x)+(horizontal?0.5:0),y:n(door.y)+(horizontal?0:.5)};if(lineIntersects(a,b,c,e))return{clear:false,cover:3,reason:'A closed door blocks line of sight.'};}for(const o of arr(spec.objects)){if(!o?.blocksVision&&!o?.cover)continue;const r=Math.max(.25,n(first(o.radius,o.width),.5)),mx=(a.x+b.x)/2,my=(a.y+b.y)/2;if(Math.hypot(mx-n(o.x),my-n(o.y))<=r)cover=Math.max(cover,n(o.cover,2));}return{clear:true,cover};}
function inferAdvantage(actor,target){const af=conditionFlags(actor),tf=conditionFlags(target);let score=0;if(af.attackAdvantage)score++;if(af.attackDisadvantage)score--;if(tf.attackersAdvantage)score++;if(tf.attackersDisadvantage)score--;return{mode:score>0?'advantage':score<0?'disadvantage':'normal'};}
function actionLegality(action,actor,{target,distance,los,inCombat=false,turn=true,reaction=false}={}){const f=conditionFlags(actor),reasons=[];if(f.noActions&&!reaction)reasons.push('You cannot take actions right now.');if(f.noReactions&&reaction)reasons.push('You cannot take reactions right now.');if(!resourceAvailable(actor,action.resource))reasons.push('Required resource is unavailable.');if(target&&Number.isFinite(distance)){const r=action.range||{normal:5};if(r.self&&target!==actor)reasons.push('This action targets self.');else if(r.long!=null&&distance>r.long)reasons.push('Target is out of range.');else if(r.long==null&&r.normal!=null&&distance>r.normal)reasons.push('Target is out of range.');}if(target&&los?.clear===false&&!action.source?.ignoresLineOfSight)reasons.push(los.reason||'Line of sight is blocked.');if(inCombat&&!turn&&!String(action.activation).includes('reaction')&&!reaction)reasons.push('It is not your active block.');return{ok:!reasons.length,reasons};}
function reactionOptions(c,trigger={}){const out=[];for(const a of actionCatalog(c)){if(String(a.activation).includes('reaction')&&resourceAvailable(c,a.resource))out.push(a);}if(trigger.enemyLeavesReach)out.unshift({id:'reaction:opportunity',kind:'reaction',name:'Opportunity Attack',activation:'reaction',target:'creature',range:{normal:5,long:5}});return out;}
function summarize(c){const pr=p(c);return{hp:hp(c),maxHp:maxHp(c),tempHp:tempHp(c),ac:ac(c),speed:speed(c),size:size(c),sizeCells:sizeCells(c),conditions:conditions(c),exhaustion:n(d(c).exhaustion,0),concentration:pr.concentration||{},resources:pr.resources||{},level:level(c),xp:xp(c)};}
window.DungeonRulesV2={abilityMod,proficiency,conditions,conditionFlags,hp,maxHp,tempHp,ac,speed,size,sizeCells,level,xp,levelStatus,resourceValue,resourceMax,parseDice,parseRange,actionCatalog,slotAvailable,resourceAvailable,distanceFt,lineOfSight,inferAdvantage,actionLegality,reactionOptions,summarize};
})();