(()=>{
'use strict';
if(window.DungeonDwellersV2)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB=()=>window.DungeonDB,R=()=>window.DungeonRulesV2,Dice=()=>window.DungeonDice;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const arr=v=>Array.isArray(v)?v:[];
let cache={cid:null,user:null,character:null,characters:[],tokens:[],map:null,campaign:null,initiative:[],reactions:[],economy:null},busy=false,refreshTimer=null;
function toast(text,type=''){const t=$('#toast');if(!t)return;t.textContent=text;t.className=`toast show ${type}`;clearTimeout(t._v2);t._v2=setTimeout(()=>t.className='toast',3600);}
function cid(){return localStorage.getItem('ddPreferredCampaign');}
async function invoke(name,body){const {data,error}=await DB().client.functions.invoke(name,{body});if(error)throw error;if(data?.ok===false)throw new Error(data.error||`${name} failed`);return data;}
function modal(title,html,buttons=[]){const root=$('#modalRoot');if(!root)return null;root.innerHTML=`<div class="modalBackdrop"><div class="modal ddV2Modal"><div class="eyebrow">Dungeon Dwellers V2</div><h2>${esc(title)}</h2><div class="modalBody">${html}</div><div class="buttonRow modalButtons"></div></div></div>`;const row=$('.modalButtons',root);buttons.forEach(b=>{const el=document.createElement('button');el.className=b.className||'ghostBtn';el.textContent=b.label;el.disabled=!!b.disabled;el.onclick=()=>b.onClick?.(root,el);row.appendChild(el);});root.classList.remove('hidden');return root;}
function closeModal(){const r=$('#modalRoot');if(r){r.classList.add('hidden');r.innerHTML='';}}
function installStyles(){if($('#ddV2Styles'))return;const s=document.createElement('style');s.id='ddV2Styles';s.textContent=`
.ddV2Panel{margin:12px 0}.ddV2StatusGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin:9px 0}.ddV2Stat{border:1px solid #44371f;background:#090b0e;border-radius:10px;padding:8px;text-align:center}.ddV2Stat small{display:block;color:#7f8790;font-size:8px;text-transform:uppercase;letter-spacing:.08em}.ddV2Stat strong{display:block;color:#efd28b;margin-top:3px;font-size:14px}.ddV2Conditions{display:flex;flex-wrap:wrap;gap:5px;margin:7px 0}.ddV2Chip{border:1px solid #66512d;border-radius:999px;padding:4px 7px;font-size:9px;color:#dbc58f;background:#0c0e11}.ddV2Chip.bad{border-color:#7f4949;color:#e2abab}.ddV2ActionGroups{display:grid;gap:11px}.ddV2ActionGroup h4{margin:0 0 6px;color:#9ca3aa;font-size:9px;text-transform:uppercase;letter-spacing:.12em}.ddV2Actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.ddV2Action{min-height:44px;border:1px solid #72592f;border-radius:11px;background:#11151a;color:#e7d7ad;padding:8px 9px;text-align:left}.ddV2Action strong{display:block;font-size:11px}.ddV2Action small{display:block;color:#818992;font-size:8px;margin-top:3px}.ddV2Action:disabled{opacity:.42}.ddV2Toolbar{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.ddV2TargetList{display:grid;gap:7px;max-height:45vh;overflow:auto}.ddV2Target{border:1px solid #5d4a2b;background:#0b0e12;color:#e6d7b3;border-radius:10px;padding:9px;text-align:left}.ddV2Target small{display:block;color:#858c94;margin-top:3px}.ddV2DiceStage{text-align:center;padding:10px}.ddV2DiceStage .diceTotal{margin-top:10px}.ddV2RollExpression{font-size:18px;color:#efd18a;font-family:ui-monospace,monospace;margin:10px 0}.ddV2Memory{font-size:10px;color:#89919a}.ddV2LevelReady{border:1px solid #8d6c31;background:#171107;border-radius:10px;padding:8px;margin-top:8px;color:#f0cf7d}.ddV2ResourceList{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.ddV2Resource{font-size:8px;border:1px solid #3b4650;border-radius:7px;padding:3px 5px;color:#aeb6bf}@media(max-width:520px){.ddV2StatusGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.ddV2Actions{grid-template-columns:1fr}}
`;document.head.appendChild(s);}
async function load(){const id=cid();if(!id||!DB())return null;const session=await DB().session();if(!session?.user)return null;cache.cid=id;cache.user=session.user;const [character,characters,tokens,map,campaign,initiative,reactions]=await Promise.all([DB().character(id),DB().memberCharacters(id),DB().tokens(id),DB().activeMap(id),DB().campaign(id),DB().initiative(id),DB().myReactions(id)]);let economy=null;if(campaign?.active_block)try{economy=(await invoke('dungeon-action',{campaignId:id,actionId:'system:economy'})).economy||null;}catch{}Object.assign(cache,{character,characters:characters||[],tokens:tokens||[],map,campaign,initiative:initiative||[],reactions:reactions||[],economy});return cache;}
function turnAllowed(){const active=cache.campaign?.active_block;if(!active)return true;const mine=cache.initiative.find(x=>x.user_id===cache.user?.id&&!x.defeated);if(!mine)return false;return Number(mine.block_index)===({player_1:1,enemy_1:2,player_2:3,enemy_2:4}[active]||0);}
function actionSubtitle(a){const bits=[];if(a.kind==='spell')bits.push(a.level?`Level ${a.level}`:'Cantrip');if(a.damage)bits.push(a.damage);if(a.healing)bits.push(`Heal ${a.healing}`);if(a.range?.normal!=null)bits.push(a.range.long?`${a.range.normal}/${a.range.long} ft`:`${a.range.normal} ft`);return bits.join(' · ')||String(a.activation||a.kind||'Action');}
function targetNeeds(a){if(['basic:dash','basic:dodge','basic:disengage','basic:hide','basic:search','basic:study','basic:influence','basic:ready'].includes(a.id))return false;if(a.range?.self)return false;if(a.kind==='item'&&a.healing&&!a.source?.target)return false;if(a.healing&&!a.target)return false;return !!(a.kind==='weapon'||a.kind==='attack'||a.kind==='spell'||a.id==='basic:grapple'||a.id==='basic:shove'||a.id==='basic:help'||a.target);
}
function targetRows(action){const actorToken=cache.tokens.find(t=>t.owner_user_id===cache.user?.id)||cache.tokens.find(t=>t.character_id===cache.character?.id),spec=cache.map?.generated_spec||{},charBy=new Map(cache.characters.map(c=>[c.id,c]));const out=[];for(const t of cache.tokens){if(t.id===actorToken?.id)continue;const c=charBy.get(t.character_id),target=c||{id:t.id,name:t.name,profile:t.state?.profile||{},ac:t.state?.ac,hp:t.state?.hp,max_hp:t.state?.maxHp};const distance=actorToken?R().distanceFt({x:Number(actorToken.x),y:Number(actorToken.y)},{x:Number(t.x),y:Number(t.y)},Number(spec.cellSizeFt||5)):null,los=actorToken?R().lineOfSight(spec,{x:Number(actorToken.x),y:Number(actorToken.y)},{x:Number(t.x),y:Number(t.y)}):{clear:true},legal=R().actionLegality(action,cache.character,{target,distance,los,inCombat:!!cache.campaign?.active_block,turn:turnAllowed()});out.push({id:c?.id||t.id,name:t.name||c?.name||'Target',kind:t.token_type||'character',distance,legal,token:t});}
 if(action.healing){for(const c of cache.characters){if(out.some(x=>x.id===c.id))continue;out.push({id:c.id,name:c.display_name||c.name||'Ally',kind:'pc',distance:null,legal:{ok:true,reasons:[]}});}}
 return out;
}
function chooseTarget(action){return new Promise(resolve=>{const rows=targetRows(action),root=modal(`Choose target · ${action.name}`,`<div class="ddV2TargetList">${rows.map((x,i)=>`<button class="ddV2Target" data-i="${i}" ${x.legal.ok?'':'disabled'}><strong>${esc(x.name)}</strong><small>${esc(x.kind)}${x.distance!=null?` · ${Math.round(x.distance)} ft`:''}${x.legal.ok?'':` · ${esc(x.legal.reasons[0]||'Unavailable')}`}</small></button>`).join('')||'<p class="statusLine bad">No valid targets are currently visible.</p>'}</div>`,[{label:'Cancel',onClick:()=>{closeModal();resolve(null);}}]);if(!root)return resolve(null);$$('[data-i]',root).forEach(b=>b.onclick=()=>{const x=rows[Number(b.dataset.i)];closeModal();resolve(x?.id||null);});});}
function rollModal(request){return new Promise(resolve=>{let result=null;const mode=['advantage','disadvantage'].includes(request?.mode)?request.mode:'normal',expr=String(request?.expression||'1d20');const root=modal(request?.label||'Roll',`<div class="ddV2DiceStage"><p>Press <strong>Roll</strong> to make the verified player roll.</p><div class="ddV2RollExpression">${esc(expr)}${mode!=='normal'?` · ${esc(mode)}`:''}</div><div id="ddV2DiceResult"></div><div id="ddV2ApplyStatus" class="statusLine">Ready</div></div>`,[{label:'Cancel',onClick:()=>{closeModal();resolve(null);}},{label:'Roll',className:'goldBtn',onClick:async(_r,btn)=>{if(result)return;try{if(/^1d20([+-]\d+)?$/i.test(expr.replace(/\s+/g,''))){const m=expr.replace(/\s+/g,'').match(/^1d20([+-]\d+)?$/i),mod=Number(m?.[1]||0);result=Dice().rollD20(mode,{modifier:mod,label:request?.label||'Roll'});}else result=Dice().roll(expr,{label:request?.label||'Roll'});result.requestId=request?.requestId||crypto.randomUUID();result.requestLabel=request?.label||'Roll';Dice().render($('#ddV2DiceResult'),result);$('#ddV2ApplyStatus').textContent='Roll confirmed';$('#ddV2ApplyStatus').className='statusLine ok ddRollApplying';btn.disabled=true;btn.textContent='Applying result…';await new Promise(done=>setTimeout(done,1050));closeModal();resolve(result);}catch(err){result=null;btn.disabled=false;btn.textContent='Retry';toast(err.message||String(err),'bad');}}}]);});}
async function narrateResolved(action,result,targetId){try{const hint=result?.narrationHint||`${cache.character?.name||'The character'} uses ${action.name}.`;await DB().client.functions.invoke('dungeon-chat',{body:{campaignId:cache.cid,message:`APP_RESOLVED_ACTION\nAction: ${action.name}\nMechanical result: ${JSON.stringify(result||{})}\nMechanics have already been authoritatively applied by Dungeon Dwellers V2. Narrate only the visible outcome from the players' perspective. Do not repeat rolls, reveal hidden enemy statistics, or apply duplicate state changes.`,visibility:'party',recipientUserIds:[]}});}catch(err){console.warn('V2 narration unavailable',err);}}
async function runServerAction(action,targetId=null){if(busy)return;busy=true;const requestId=crypto.randomUUID();try{let phase='prepare',verifiedRoll=null;for(let step=0;step<5;step++){const data=await invoke('dungeon-action',{campaignId:cache.cid,actionId:action.id,targetId,phase,verifiedRoll,requestId});if(data.complete){toast(data.result?.narrationHint||`${action.name} resolved.`,'ok');await narrateResolved(action,data.result,targetId);await load();render();return data;}const next=data.next;if(!next?.rollRequest)throw new Error('The action resolver did not provide the next required roll.');const rolled=await rollModal(next.rollRequest);if(!rolled){await load();render();return null;}phase=next.phase||phase;verifiedRoll=rolled;targetId=next.targetId||targetId;}throw new Error('Action resolution exceeded the safe step limit.');}catch(err){toast(err.message||String(err),'bad');await load().catch(()=>null);render();}finally{busy=false;}}
async function runAction(action){if(!cache.character)return toast('Choose a character first.','warn');if(cache.campaign?.paused)return toast('This campaign is paused.','warn');if(cache.campaign?.active_block&&!turnAllowed()&&!String(action.activation).includes('reaction'))return toast('It is not your active initiative block.','warn');let targetId=null;if(targetNeeds(action)){targetId=await chooseTarget(action);if(!targetId)return;}await runServerAction(action,targetId);}
async function runRest(type){if(cache.campaign?.active_block)return toast('You cannot take a rest during active combat.','warn');if(type==='long'){modal('Long Rest','<p>A Long Rest restores the character according to tracked V2 recovery data, restores HP and spell slots, clears temporary HP/death saves, ends concentration, and reduces exhaustion by one.</p>',[{label:'Cancel',onClick:closeModal},{label:'Take Long Rest',className:'goldBtn',onClick:async()=>{closeModal();try{await invoke('dungeon-action',{campaignId:cache.cid,actionId:'rest:long'});await narrateResolved({name:'Long Rest'},{narrationHint:`${cache.character?.name||'The party member'} completes a long rest.`});await load();render();toast('Long Rest complete.','ok');}catch(e){toast(e.message||String(e),'bad');}}}]);return;}
 const p=cache.character?.profile||{},hd=p.hitDice||p.resources?.hitDice||{},available=Number(hd.current??hd.remaining??hd.value??0),die=Number(hd.sides||String(hd.die||hd.type||'d8').match(/d(\d+)/i)?.[1]||8),con=R().abilityMod(cache.character,'constitution');let spent=0,heal=0;const root=modal('Short Rest',`<p>Spend Hit Dice if you want to recover HP. Available: <strong>${available}</strong>.</p><div id="ddV2RestRolls" class="statusLine">No Hit Dice spent.</div>`,[{label:'Cancel',onClick:closeModal},{label:'Roll Hit Die',className:'ghostBtn',onClick:(_r,btn)=>{if(spent>=available){toast('No more Hit Dice available.','warn');return;}const rr=Dice().roll(`1d${die}${con>=0?'+':''}${con}`,{label:'Hit Die'});spent++;heal+=Math.max(0,rr.total);$('#ddV2RestRolls').textContent=`${spent} Hit Die spent · ${heal} HP to recover`; }},{label:'Finish Short Rest',className:'goldBtn',onClick:async()=>{closeModal();try{await invoke('dungeon-action',{campaignId:cache.cid,actionId:'rest:short',hitDiceSpent:spent,healing:heal});await narrateResolved({name:'Short Rest'},{narrationHint:`${cache.character?.name||'The party member'} completes a short rest.`});await load();render();toast('Short Rest complete.','ok');}catch(e){toast(e.message||String(e),'bad');}}}]);}
function statusHtml(){if(!cache.character)return'<p class="statusLine">Select or import a character to enable V2 actions.</p>';const s=R().summarize(cache.character),lvl=R().levelStatus(cache.character),conds=s.conditions||[],res=Object.entries(s.resources||{}).slice(0,10);return`<div class="ddV2StatusGrid"><div class="ddV2Stat"><small>HP</small><strong>${s.hp}/${s.maxHp}${s.tempHp?` +${s.tempHp}`:''}</strong></div><div class="ddV2Stat"><small>AC</small><strong>${s.ac}</strong></div><div class="ddV2Stat"><small>Speed</small><strong>${s.speed} ft</strong></div><div class="ddV2Stat"><small>Exhaustion</small><strong>${s.exhaustion}</strong></div></div><div class="ddV2Conditions">${conds.map(c=>`<span class="ddV2Chip bad">${esc(c.name)}</span>`).join('')}${s.concentration?.active?`<span class="ddV2Chip">Concentrating · ${esc(s.concentration.spell||'Effect')}</span>`:''}${!conds.length&&!s.concentration?.active?'<span class="ddV2Chip">No active conditions</span>':''}</div>${res.length?`<div class="ddV2ResourceList">${res.map(([k,v])=>{const cur=v&&typeof v==='object'?(v.current??v.value??v.remaining??0):v,max=v&&typeof v==='object'?(v.max??v.maximum??v.total):null;return`<span class="ddV2Resource">${esc(k)} ${esc(cur)}${max!=null?`/${esc(max)}`:''}</span>`;}).join('')}</div>`:''}${lvl.eligible?`<div class="ddV2LevelReady"><strong>Level up available</strong><br>XP supports level ${lvl.recommendedLevel}. Open Character to make the legal class/spell/feat choices before committing the new level.</div>`:''}`;}
function actionHtml(){if(!cache.character)return'';const actions=R().actionCatalog(cache.character),groups={Attacks:[],Spells:[],Features:[],Items:[],Basic:[]},e=cache.economy||{},p=cache.character.profile||{},level=Number(p.identity?.level||p.level||1),cls=String(p.identity?.class||p.class||p.classes?.[0]?.name||'').toLowerCase(),features=[...arr(p.classFeatures),...arr(p.features)],attackMax=cls.includes('fighter')?(level>=20?4:level>=11?3:level>=5?2:1):features.some(f=>/extra attack/i.test(String(f?.name||f)))?2:1;for(const a of actions){if(a.kind==='weapon'||a.kind==='attack')groups.Attacks.push(a);else if(a.kind==='spell')groups.Spells.push(a);else if(a.kind==='feature')groups.Features.push(a);else if(a.kind==='item')groups.Items.push(a);else groups.Basic.push(a);}const spent=a=>{if(!cache.campaign?.active_block)return false;const act=String(a.activation||'action');if(act.includes('bonus'))return e.bonus_action_used;if(act.includes('reaction'))return e.reaction_used;if(a.kind==='weapon'||a.kind==='attack')return e.action_used&&(!e.attack_action_started||Number(e.attacks_used||0)>=attackMax);return e.action_used;};return`${cache.campaign?.active_block?`<div class="ddV2ResourceList"><span class="ddV2Resource">Action ${e.action_used?'spent':'ready'}</span>${e.attack_action_started?`<span class="ddV2Resource">Attacks ${Number(e.attacks_used||0)}/${attackMax}</span>`:''}<span class="ddV2Resource">Bonus ${e.bonus_action_used?'spent':'ready'}</span><span class="ddV2Resource">Reaction ${e.reaction_used?'spent':'ready'}</span><span class="ddV2Resource">Move ${Number(e.movement_used_ft||0)} ft</span></div>`:''}<div class="ddV2ActionGroups">${Object.entries(groups).filter(([,xs])=>xs.length).map(([name,xs])=>`<div class="ddV2ActionGroup"><h4>${name}</h4><div class="ddV2Actions">${xs.map(a=>`<button class="ddV2Action" data-v2-action="${esc(a.id)}" ${spent(a)?'disabled':''}><strong>${esc(a.name)}</strong><small>${spent(a)?'Spent this turn':esc(actionSubtitle(a))}</small></button>`).join('')}</div></div>`).join('')}</div>`;}
function ensurePanel(){let host=$('#ddV2PlayPanel');if(host)return host;const home=$('#homePage');if(!home)return null;host=document.createElement('article');host.id='ddV2PlayPanel';host.className='card sectionCard ddV2Panel';const chat=$('#partyChatHome');chat?.insertAdjacentElement('afterend',host);return host;}
function bindPanel(host){const byId=new Map(R().actionCatalog(cache.character||{}).map(a=>[a.id,a]));$$('[data-v2-action]',host).forEach(b=>b.onclick=()=>runAction(byId.get(b.dataset.v2Action)));$('#ddV2ShortRest',host)?.addEventListener('click',()=>runRest('short'));$('#ddV2LongRest',host)?.addEventListener('click',()=>runRest('long'));$('#ddV2Refresh',host)?.addEventListener('click',async()=>{await load();render();toast('V2 state refreshed.','ok');});}
function render(){installStyles();const host=ensurePanel();if(!host)return;host.innerHTML=`<div class="sectionHead"><div><div class="eyebrow">Dungeon Dwellers V2</div><h2>Play Your Character</h2></div><span class="ddV2Chip">2024 mechanics</span></div>${statusHtml()}${actionHtml()}<div class="ddV2Toolbar"><button id="ddV2ShortRest" class="ghostBtn">Short Rest</button><button id="ddV2LongRest" class="ghostBtn">Long Rest</button><button id="ddV2Refresh" class="ghostBtn">Refresh State</button></div>`;bindPanel(host);renderReactionPanel();}
function renderReactionPanel(){const root=$('#reactionList');if(!root||!cache.character)return;for(const rw of cache.reactions||[]){if(root.querySelector(`[data-v2-reaction-id="${rw.id}"]`))continue;const box=document.createElement('div');box.className='listItem';box.dataset.v2ReactionId=rw.id;const legal=arr(rw.legal_options),fallback=R().reactionOptions(cache.character,{enemyLeavesReach:rw.trigger?.kind==='leaves_reach'}),opts=legal.length?legal:fallback,spent=!!cache.economy?.reaction_used;box.innerHTML=`<strong>Reaction Available</strong><span>${spent?'Your Reaction is already spent this round.':esc(rw.trigger?.description||rw.trigger?.kind||'A trigger allows a reaction.')}</span><div class="buttonRow" style="margin-top:7px">${opts.map((o,i)=>`<button class="ghostBtn" data-r="${i}" ${spent?'disabled':''}>${esc(o.name||o.label||String(o))}</button>`).join('')}<button class="ghostBtn" data-r-pass>Pass</button></div>`;root.prepend(box);$$('[data-r]',box).forEach(b=>b.onclick=async()=>{const o=opts[Number(b.dataset.r)];try{await invoke('dungeon-action',{campaignId:cache.cid,actionId:'system:reaction',requestId:crypto.randomUUID()});await DB().resolveReaction(rw.id,{choice:o.id||o.name||o.label||o,at:new Date().toISOString()});toast('Reaction submitted.','ok');await load();render();}catch(e){toast(e.message||String(e),'bad');}});$('[data-r-pass]',box).onclick=async()=>{try{await DB().resolveReaction(rw.id,{choice:'pass',at:new Date().toISOString()});await load();render();}catch(e){toast(e.message||String(e),'bad');}};}}
function patchRealtime(){const db=DB();if(!db||db.__v2RealtimePatched)return;db.__v2RealtimePatched=true;db.subscribe=function(campaignId,onChange){const ch=db.client.channel(`dd-v2:${campaignId}:${crypto.randomUUID()}`);const add=(table,filter=`campaign_id=eq.${campaignId}`)=>ch.on('postgres_changes',{event:'*',schema:'public',table,filter},p=>onChange(table,p));add('campaigns',`id=eq.${campaignId}`);['campaign_members','characters','tokens','campaign_maps','initiative_entries','reaction_windows','story_events','knowledge','quests','campaign_engine_state','encounter_state'].forEach(t=>add(t));return ch.subscribe();};}
function schedule(){clearTimeout(refreshTimer);refreshTimer=setTimeout(async()=>{try{if(cid()!==cache.cid||document.visibilityState==='visible'){await load();render();}}catch{}},180);}
async function init(){if(!DB()||!R()||!Dice())return;patchRealtime();await load().catch(()=>null);render();DB().client.channel(`dd-v2-ui:${crypto.randomUUID()}`).on('postgres_changes',{event:'*',schema:'public',table:'characters'},schedule).on('postgres_changes',{event:'*',schema:'public',table:'reaction_windows'},schedule).subscribe();window.addEventListener('dd:initiative-recorded',schedule);window.addEventListener('dd:v2-refresh',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule();});}
window.DungeonDwellersV2={load,render,runAction,runRest,runServerAction,rollModal,get state(){return cache;}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,100),{once:true});else setTimeout(init,100);
})();

