import { createClient } from 'npm:@supabase/supabase-js@2';

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});

Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
  if(req.method!=='POST')return json({ok:false,error:'POST required'},405);
  const supabaseUrl=Deno.env.get('SUPABASE_URL')!,anonKey=Deno.env.get('SUPABASE_ANON_KEY')!,serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,aiWorkerUrl=Deno.env.get('DUNGEON_AI_WORKER_URL')||'https://dungeon-dwellers-ai.jesse-datema08.workers.dev',authHeader=req.headers.get('Authorization')||'';
  const userClient=createClient(supabaseUrl,anonKey,{global:{headers:{Authorization:authHeader}}}),admin=createClient(supabaseUrl,serviceKey);
  const {data:userData,error:userError}=await userClient.auth.getUser(),user=userData?.user;if(userError||!user)return json({ok:false,error:'Authentication required'},401);
  const payload=await req.json().catch(()=>({})),campaignId=String(payload.campaignId||''),message=String(payload.message||'').slice(0,12000),verifiedRoll=payload.verifiedRoll||null,suppressChatPersist=payload.suppressChatPersist===true;if(!campaignId||!message)return json({ok:false,error:'campaignId and message are required'},400);
  const {data:membership}=await admin.from('campaign_members').select('role').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle();const {data:campaign}=await admin.from('campaigns').select('*').eq('id',campaignId).maybeSingle();if(!campaign||(!membership&&campaign.owner_id!==user.id))return json({ok:false,error:'Campaign access denied'},403);
  const {data:character}=await admin.from('characters').select('*').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle();
  const {data:map}=await admin.from('campaign_maps').select('*').eq('campaign_id',campaignId).eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();
  const {data:mapView}=map?await admin.from('map_views').select('*').eq('map_id',map.id).eq('user_id',user.id).maybeSingle():{data:null} as any;
  const {data:tokens}=await admin.from('tokens').select('*').eq('campaign_id',campaignId),tokenIds=(tokens||[]).map((t:any)=>t.id);
  const {data:tokenVis}=tokenIds.length?await admin.from('token_visibility').select('*').eq('user_id',user.id).in('token_id',tokenIds):{data:[]} as any,visMap=new Map((tokenVis||[]).map((v:any)=>[v.token_id,v]));
  const visibleTokens=(tokens||[]).filter((t:any)=>!t.hidden||visMap.get(t.id)?.visible===true).map((t:any)=>{const v=visMap.get(t.id);return{id:t.id,token_type:t.token_type,name:v?.label_override||t.name,x:t.x,y:t.y,rotation:t.rotation,state:t.hidden?(v?.state||{}):t.state};});
  const {data:initiative}=await admin.from('initiative_entries').select('*').eq('campaign_id',campaignId).eq('defeated',false).order('block_index').order('initiative',{ascending:false});
  const {data:reactions}=await admin.from('reaction_windows').select('*').eq('campaign_id',campaignId).eq('user_id',user.id).eq('resolved',false).gt('deadline',new Date().toISOString());
  const {data:quests}=await admin.from('quests').select('*').eq('campaign_id',campaignId).order('updated_at',{ascending:false});
  const {data:knowledge}=await userClient.from('knowledge').select('*').eq('campaign_id',campaignId).order('created_at',{ascending:false}).limit(60);
  const {data:story}=await userClient.from('story_events').select('*').eq('campaign_id',campaignId).order('created_at',{ascending:false}).limit(30);
  const authoritative={app:'Dungeon Dwellers',rulesEdition:'D&D 5e 2024 revised',campaign,membership:membership||{role:campaign.owner_id===user.id?'owner':'player'},character,map:map?{id:map.id,name:map.name,generated_spec:map.generated_spec,view:mapView?.view_state||null}:null,visibleTokens,initiative:initiative||[],reactions:reactions||[],quests:quests||[],knowledge:knowledge||[],recentStory:story||[],verifiedRoll,rollAuthority:'Only app-generated APP_VERIFIED_ROLL results are authoritative for player-facing rolls.'};
  const systemMessage=`You are the AI Dungeon Master for Dungeon Dwellers using D&D 5e 2024 revised rules only. You communicate with players through the campaign chat, not through a separate scene-description persona. The supplied campaign state and character record are authoritative. The Campaign Owner has system-recovery authority but remains a normal player during play. Never reveal hidden information absent from the player-safe state. Players enact every player-facing roll themselves. Combat uses four initiative blocks after sorting each side by initiative: first ceil-half of players, first ceil-half of enemies, remaining players, remaining enemies. Player blocks are 6 real-world hours. Reactions are 1 real-world hour. A combat round is 6 seconds in-world. Outside combat, gather one meaningful scene action from each player and resolve the scene turn together. Missed combat turns do nothing meaningful. Be permissive with creative play but enforce fair mechanics and costs. Return narration followed by one optional machine line exactly as [[DD_EVENT:{"notify":"none|reaction|turn|attacked|afflicted|info|scene|round","sceneSummary":"","publicKnowledge":"","rollRequest":null,"reaction":null,"visibilityUpdates":[],"mapView":null}]]. A reaction object may contain {"userId":"...","trigger":{},"legalOptions":[]}. visibilityUpdates is an array of {"tokenId":"...","userId":"...","visible":true,"label":null,"state":{}}. mapView may be {"userId":"...","viewState":{}}. Use notify=attacked, afflicted, or info for major character events that should alert this player. Never put secrets in sceneSummary or publicKnowledge.`;
  const aiRes=await fetch(aiWorkerUrl,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({message:`${systemMessage}\n\nPLAYER MESSAGE:\n${message}`,campaignState:authoritative})});const rawText=await aiRes.text();let ai:any;try{ai=rawText?JSON.parse(rawText):{}}catch{ai={raw:rawText}}if(!aiRes.ok||ai?.ok===false)return json({ok:false,error:ai?.error||ai?.message||rawText||`AI HTTP ${aiRes.status}`},502);
  const narration=String(typeof ai==='string'?ai:(ai.narration||ai.response||ai.result?.narration||ai.result?.response||ai.raw||'')),match=/\[\[DD_EVENT:(\{.*?\})\]\]/s.exec(narration);let event:any=null;if(match){try{event=JSON.parse(match[1]);}catch{}}const clean=narration.replace(match?.[0]||'','').trim();
  const isGenerator=message.startsWith('CAMPAIGN_GENERATION_REQUEST');
  if(clean&&!isGenerator&&!suppressChatPersist){
    await admin.from('chat_messages').insert({campaign_id:campaignId,user_id:null,body:clean,sender_kind:'dm',visibility:'private',recipient_user_ids:[user.id],metadata:{channel:'dm',kind:'dm_reply'}});
    await admin.from('notification_outbox').insert({campaign_id:campaignId,user_id:user.id,kind:'mentions',title:'Message from AI DM',body:clean.slice(0,180),data:{campaignId,direct:true},deliver_after:new Date().toISOString()});
  }
  if(event?.sceneSummary)await admin.from('campaigns').update({current_scene:event.sceneSummary,state:{...(campaign.state||{}),sceneText:event.sceneSummary},updated_at:new Date().toISOString()}).eq('id',campaignId);
  if(event?.publicKnowledge)await admin.from('knowledge').insert({campaign_id:campaignId,user_id:null,visibility:'party',fact:String(event.publicKnowledge).slice(0,4000)});
  if(Array.isArray(event?.visibilityUpdates))for(const u of event.visibilityUpdates.slice(0,100)){if(!u?.tokenId||!u?.userId)continue;await admin.from('token_visibility').upsert({token_id:u.tokenId,user_id:u.userId,visible:!!u.visible,label_override:u.label||null,state:u.state||{},updated_at:new Date().toISOString()},{onConflict:'token_id,user_id'});}
  if(event?.mapView?.userId&&map?.id)await admin.from('map_views').upsert({map_id:map.id,user_id:event.mapView.userId,view_state:event.mapView.viewState||{},updated_at:new Date().toISOString()},{onConflict:'map_id,user_id'});
  if(event?.reaction?.userId){const hours=Number(campaign.settings?.reactionWindowHours||1),deadline=new Date(Date.now()+hours*3600000).toISOString();await admin.from('reaction_windows').insert({campaign_id:campaignId,user_id:event.reaction.userId,trigger:event.reaction.trigger||{},legal_options:event.reaction.legalOptions||[],deadline});await admin.from('notification_outbox').insert({campaign_id:campaignId,user_id:event.reaction.userId,kind:'reaction',title:'Reaction Available',body:clean.slice(0,180)||'A reaction is available.',data:{campaignId},deliver_after:new Date().toISOString()});}
  const notify=String(event?.notify||'none');if(['attacked','afflicted','info'].includes(notify)){const titles:any={attacked:'Your Character Was Attacked',afflicted:'Character Status Changed',info:'Important Character Information'};await admin.from('notification_outbox').insert({campaign_id:campaignId,user_id:user.id,kind:'major_character',title:titles[notify],body:clean.slice(0,180)||'Your character has an important update.',data:{campaignId,kind:notify},deliver_after:new Date().toISOString()});}
  return json({ok:true,narration:clean,event});
});