import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const n=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const norm=(v:any)=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const arr=(v:any)=>Array.isArray(v)?v:[];
const first=(...v:any[])=>v.find(x=>x!==undefined&&x!==null&&x!=='');
const clone=(v:any)=>JSON.parse(JSON.stringify(v??{}));
const abilityAlias:any={str:'strength',dex:'dexterity',con:'constitution',int:'intelligence',wis:'wisdom',cha:'charisma'};
function profile(c:any){return c?.profile||{};}
function prof(c:any){return n(first(profile(c).proficiencyBonus,profile(c).proficiency),2);}
function mod(c:any,key:any){const p=profile(c),k=abilityAlias[norm(key)]||norm(key),e=p.abilities?.[k]||p.abilities?.[k.slice(0,3)]||{};if(Number.isFinite(Number(e.mod)))return Number(e.mod);if(Number.isFinite(Number(e.modifier)))return Number(e.modifier);return Math.floor((n(e.score,10)-10)/2);}
function parseDice(raw:any){const m=String(raw||'').replace(/\s+/g,'').match(/(\d+)d(\d+)([+-]\d+)?/i);return m?{count:n(m[1],1),sides:n(m[2],20),mod:n(m[3],0),expression:m[0]}:null;}
function parseRange(raw:any){if(Number.isFinite(Number(raw)))return Number(raw);const s=String(raw||'').toLowerCase(),slash=s.match(/(\d+)\s*\/\s*(\d+)/),m=s.match(/(\d+)\s*(?:ft|feet|foot)/);if(s.includes('self'))return 0;if(s.includes('touch'))return 5;if(slash)return Number(slash[2]);return m?Number(m[1]):5;}
function weaponAction(w:any,i:number){const name=w?.name||`Weapon ${i+1}`,ab=first(w.attackBonus,w.attack_bonus,w.toHit,w.rulesProfile?.attackBonus);return{id:`weapon:${norm(name)}`,kind:'weapon',name,attackBonus:Number.isFinite(Number(ab))?Number(ab):null,damage:String(first(w.damage,w.damageDice,w.rulesProfile?.damage,'')),damageType:first(w.damageType,w.rulesProfile?.damageType),range:parseRange(first(w.range,w.rulesProfile?.range,w.properties)),properties:String(first(w.properties,w.rulesProfile?.properties,'')),source:w};}
function attackAction(a:any,i:number){const name=a?.name||`Attack ${i+1}`;return{id:a.id||`attack:${norm(name)}`,kind:a.kind||'attack',name,attackBonus:Number.isFinite(Number(first(a.attackBonus,a.toHit)))?Number(first(a.attackBonus,a.toHit)):null,saveAbility:first(a.saveAbility,a.save),saveDC:Number.isFinite(Number(first(a.saveDC,a.dc)))?Number(first(a.saveDC,a.dc)):null,damage:String(first(a.damage,a.damageDice,'')),damageType:a.damageType,healing:String(first(a.healing,a.heal,'')),range:parseRange(first(a.range,a.reach)),resource:a.resource||null,source:a};}
function spellAction(s:any,i:number){const name=s?.name||`Spell ${i+1}`,lv=n(s.level,0);return{id:s.id||`spell:${norm(name)}`,kind:'spell',name,level:lv,attackBonus:Number.isFinite(Number(first(s.attackBonus,s.spellAttackBonus)))?Number(first(s.attackBonus,s.spellAttackBonus)):null,saveAbility:first(s.saveAbility,s.save),saveDC:Number.isFinite(Number(first(s.saveDC,s.dc)))?Number(first(s.saveDC,s.dc)):null,damage:String(first(s.damage,s.damageDice,'')),damageType:s.damageType,healing:String(first(s.healing,s.heal,'')),range:parseRange(s.range),concentration:!!s.concentration,resource:lv?{spellSlotLevel:lv,cost:1}:null,source:s};}
function featureAction(f:any,i:number){const name=f?.name||`Feature ${i+1}`;return{id:f.id||`feature:${norm(name)}`,kind:'feature',name,attackBonus:Number.isFinite(Number(f.attackBonus))?Number(f.attackBonus):null,saveAbility:first(f.saveAbility,f.save),saveDC:Number.isFinite(Number(first(f.saveDC,f.dc)))?Number(first(f.saveDC,f.dc)):null,damage:String(first(f.damage,f.damageDice,'')),healing:String(first(f.healing,f.heal,'')),range:parseRange(f.range),resource:f.resource||((f.uses||f.maxUses)?{key:norm(name),cost:1}:null),source:f};}
function itemAction(it:any,i:number){const name=it?.name||`Item ${i+1}`;return{id:it.id||`item:${norm(name)}`,kind:'item',name,damage:String(first(it.damage,'')),healing:String(first(it.healing,it.heal,'')),range:parseRange(it.range),source:it};}
function catalog(c:any){const p=profile(c),eq=p.equipment||{},out:any[]=[];arr(eq.weapons).forEach((x,i)=>out.push(weaponAction(x,i)));arr(p.attacks).forEach((x,i)=>out.push(attackAction(x,i)));arr(first(p.spellcasting?.spells,p.spells,[])).forEach((x,i)=>out.push(spellAction(x,i)));[...arr(p.classFeatures),...arr(p.speciesFeatures),...arr(p.backgroundFeatures),...arr(p.feats),...arr(p.features)].forEach((x,i)=>out.push(featureAction(x,i)));[...arr(eq.consumables),...arr(eq.magicItems),...arr(p.magicItems),...arr(eq.gear)].forEach((x,i)=>{if(x?.usable||x?.effect||x?.healing||x?.damage||x?.charges||x?.category==='consumable')out.push(itemAction(x,i));});out.push({id:'basic:grapple',kind:'basic',name:'Grapple',range:5},{id:'basic:shove',kind:'basic',name:'Shove',range:5},{id:'basic:help',kind:'basic',name:'Help',range:5},{id:'basic:dash',kind:'basic',name:'Dash'},{id:'basic:dodge',kind:'basic',name:'Dodge'},{id:'basic:disengage',kind:'basic',name:'Disengage'},{id:'basic:hide',kind:'basic',name:'Hide'},{id:'basic:search',kind:'basic',name:'Search'},{id:'basic:study',kind:'basic',name:'Study'},{id:'basic:influence',kind:'basic',name:'Influence'});return out;}
function attackBonus(c:any,a:any){if(Number.isFinite(Number(a.attackBonus)))return Number(a.attackBonus);const finesse=/finesse/i.test(a.properties||''),ranged=/ranged|bow|crossbow/i.test(`${a.source?.attackType||''} ${a.name||''} ${a.properties||''}`);return mod(c,ranged||finesse?'dexterity':'strength')+prof(c);}
function saveDC(c:any,a:any){if(Number.isFinite(Number(a.saveDC)))return Number(a.saveDC);const p=profile(c),abil=first(p.spellcasting?.ability,p.spellcasting?.spellcastingAbility,a.source?.ability,'wisdom');return 8+prof(c)+mod(c,abil);}
function currentSlot(p:any,level:number){const slots=p.spellcasting?.slots||{},key=Object.keys(slots).find(k=>norm(k)===norm(String(level))||norm(k)===`level${level}`)||String(level),v=slots[key];return{slots,key,current:v&&typeof v==='object'?n(first(v.current,v.remaining,v.value),0):n(v,0),max:v&&typeof v==='object'?n(first(v.max,v.maximum,v.total),0):n(v,0)};}
function spend(c:any,a:any){const p=c.profile=clone(profile(c));if(a.resource?.spellSlotLevel){const r=currentSlot(p,a.resource.spellSlotLevel);if(r.current<1)throw new Error(`No level ${a.resource.spellSlotLevel} spell slot remains.`);if(r.slots[r.key]&&typeof r.slots[r.key]==='object')r.slots[r.key].current=r.current-1;else r.slots[r.key]=r.current-1;}if(a.resource?.key){const map=p.resources=p.resources||{},v=map[a.resource.key],cur=v&&typeof v==='object'?n(first(v.current,v.remaining,v.value),0):n(v,0),cost=n(a.resource.cost,1);if(cur<cost)throw new Error('Required resource is unavailable.');if(v&&typeof v==='object')v.current=cur-cost;else map[a.resource.key]=cur-cost;}return c;}
function hpOf(x:any){return n(first(x?.hp,x?.state?.hp,x?.state?.statBlock?.hp,x?.state?.stat_block?.hp),0);}
function maxHpOf(x:any){return Math.max(0,n(first(x?.max_hp,x?.state?.maxHp,x?.state?.statBlock?.maxHp,x?.state?.stat_block?.max_hp,hpOf(x)),hpOf(x)));}
function acOf(x:any){return n(first(x?.ac,x?.state?.ac,x?.state?.statBlock?.ac,x?.state?.stat_block?.ac),10);}
function enemySaveMod(t:any,ability:any){const k=abilityAlias[norm(ability)]||norm(ability),sb=t?.state?.statBlock||t?.state?.stat_block||{},s=sb.saves?.[k]??sb.savingThrows?.[k];if(Number.isFinite(Number(s)))return Number(s);const score=sb.abilities?.[k]?.score??sb.abilities?.[k]??10;return Math.floor((n(score,10)-10)/2);}
function secureDie(sides=20){const a=new Uint32Array(1);crypto.getRandomValues(a);return(a[0]%sides)+1;}
function distance(a:any,b:any,cell=5){if(!a||!b)return null;return Math.max(Math.abs(n(a.x)-n(b.x)),Math.abs(n(a.y)-n(b.y)))*cell;}
async function saveCharacter(admin:any,c:any){await admin.from('characters').update({profile:c.profile,hp:c.hp,max_hp:c.max_hp,ac:c.ac,updated_at:new Date().toISOString()}).eq('id',c.id).eq('campaign_id',c.campaign_id);}
async function damageTarget(admin:any,campaignId:string,target:any,amount:number){amount=Math.max(0,Math.floor(amount));if(target.kind==='character'){const c=target.row,p=c.profile=clone(profile(c)),d=p.defenses=p.defenses||{},max=maxHpOf(c),temp=Math.max(0,n(first(d.tempHp,d.temporaryHp),0)),absorbed=Math.min(temp,amount),next=Math.max(0,hpOf(c)-(amount-absorbed));d.tempHp=temp-absorbed;d.temporaryHp=d.tempHp;d.currentHp=next;d.maxHp=max;c.hp=next;c.max_hp=max;if(next===0)d.unconscious=true;await saveCharacter(admin,c);return{hp:next,maxHp:max,absorbed};}const t=target.row,state=clone(t.state||{}),max=maxHpOf(t),next=Math.max(0,hpOf(t)-amount);state.hp=next;state.maxHp=max;state.defeated=next<=0;await admin.from('tokens').update({state,updated_at:new Date().toISOString()}).eq('id',t.id).eq('campaign_id',campaignId);if(next<=0)await admin.from('initiative_entries').update({defeated:true}).eq('campaign_id',campaignId).eq('token_id',t.id);return{hp:next,maxHp:max};}
async function healTarget(admin:any,campaignId:string,target:any,amount:number){amount=Math.max(0,Math.floor(amount));if(target.kind==='character'){const c=target.row,p=c.profile=clone(profile(c)),d=p.defenses=p.defenses||{},max=maxHpOf(c),next=Math.min(max,hpOf(c)+amount);c.hp=next;c.max_hp=max;d.currentHp=next;d.maxHp=max;if(next>0){d.unconscious=false;d.deathSaves={successes:0,failures:0};}await saveCharacter(admin,c);return{hp:next,maxHp:max};}const t=target.row,state=clone(t.state||{}),max=maxHpOf(t),next=Math.min(max,hpOf(t)+amount);state.hp=next;state.maxHp=max;state.defeated=false;await admin.from('tokens').update({state,updated_at:new Date().toISOString()}).eq('id',t.id).eq('campaign_id',campaignId);return{hp:next,maxHp:max};}
async function resolveTarget(admin:any,campaignId:string,id:any){if(!id)return null;let {data:c}=await admin.from('characters').select('*').eq('campaign_id',campaignId).eq('id',id).maybeSingle();if(c)return{kind:'character',row:c};let {data:t}=await admin.from('tokens').select('*').eq('campaign_id',campaignId).eq('id',id).maybeSingle();if(t)return{kind:'token',row:t};return null;}
function verified(v:any){if(!v||!Number.isFinite(Number(v.total)))return null;return{...v,total:Number(v.total),natural:Number.isFinite(Number(v.natural))?Number(v.natural):null};}
async function rest(admin:any,c:any,type:string,payload:any){const out={...c,profile:clone(profile(c))},p=out.profile,d=p.defenses=p.defenses||{},max=maxHpOf(out);if(type==='long'){out.hp=max;out.max_hp=max;d.currentHp=max;d.maxHp=max;d.tempHp=0;d.temporaryHp=0;d.deathSaves={successes:0,failures:0};d.exhaustion=Math.max(0,n(d.exhaustion)-1);p.concentration={active:false};for(const s of Object.values(p.spellcasting?.slots||{}) as any[])if(s&&typeof s==='object'&&Number.isFinite(Number(first(s.max,s.maximum,s.total))))s.current=Number(first(s.max,s.maximum,s.total));for(const r of Object.values(p.resources||{}) as any[])if(r&&typeof r==='object'&&String(r.recovery||r.reset||'').toLowerCase().includes('long')&&Number.isFinite(Number(first(r.max,r.maximum,r.total))))r.current=Number(first(r.max,r.maximum,r.total));}else{const heal=Math.max(0,n(payload?.healing,0));out.hp=Math.min(max,hpOf(out)+heal);d.currentHp=out.hp;for(const r of Object.values(p.resources||{}) as any[])if(r&&typeof r==='object'&&String(r.recovery||r.reset||'').toLowerCase().includes('short')&&Number.isFinite(Number(first(r.max,r.maximum,r.total))))r.current=Number(first(r.max,r.maximum,r.total));const hd=p.hitDice||p.resources?.hitDice;if(hd&&typeof hd==='object'&&n(payload?.hitDiceSpent)>0)hd.current=Math.max(0,n(first(hd.current,hd.remaining))-n(payload.hitDiceSpent));}await saveCharacter(admin,out);return out;}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'POST required'},405);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')||'',uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service),{data:ud}=await uc.auth.getUser(),user=ud?.user;if(!user)return json({ok:false,error:'Authentication required'},401);const body=await req.json().catch(()=>({})),campaignId=String(body.campaignId||''),actionId=String(body.actionId||''),phase=String(body.phase||'prepare'),targetId=body.targetId||null,roll=verified(body.verifiedRoll);if(!campaignId)return json({ok:false,error:'campaignId required'},400);const {data:membership}=await admin.from('campaign_members').select('role').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle(),{data:campaign}=await admin.from('campaigns').select('*').eq('id',campaignId).maybeSingle();if(!campaign||(!membership&&campaign.owner_id!==user.id))return json({ok:false,error:'Campaign access denied'},403);if(campaign.paused)return json({ok:false,error:'The campaign is paused.'},409);const {data:actor}=await admin.from('characters').select('*').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle();if(!actor)return json({ok:false,error:'Select a character for this campaign first.'},409);if(campaign.active_block){const blockIndex=({player_1:1,enemy_1:2,player_2:3,enemy_2:4} as Record<string,number>)[String(campaign.active_block)]||0,{data:initiative}=await admin.from('initiative_entries').select('block_index,defeated').eq('campaign_id',campaignId).eq('user_id',user.id).eq('defeated',false).maybeSingle();if(!initiative||Number(initiative.block_index)!==blockIndex)return json({ok:false,error:'It is not your turn.'},409);}
 if(actionId==='rest:short'||actionId==='rest:long'){const type=actionId.endsWith('long')?'long':'short',out=await rest(admin,actor,type,body);await admin.from('story_events').insert({campaign_id:campaignId,actor_user_id:user.id,event_type:`${type}_rest`,payload:{characterId:actor.id,healing:n(body.healing,0),hitDiceSpent:n(body.hitDiceSpent,0)}});return json({ok:true,complete:true,kind:'rest',character:{id:out.id,hp:out.hp,max_hp:out.max_hp,profile:out.profile}});}
 const action=catalog(actor).find(a=>a.id===actionId);if(!action)return json({ok:false,error:'That action is not present on the authoritative character.'},400);const target=await resolveTarget(admin,campaignId,targetId);if(targetId&&!target)return json({ok:false,error:'Target no longer exists.'},404);const {data:actorToken}=await admin.from('tokens').select('*').eq('campaign_id',campaignId).eq('owner_user_id',user.id).maybeSingle();if(target?.kind==='token'&&actorToken){const {data:map}=await admin.from('campaign_maps').select('generated_spec,grid_size').eq('campaign_id',campaignId).eq('active',true).maybeSingle(),cell=n(map?.generated_spec?.cellSizeFt,map?.grid_size===50?5:n(map?.grid_size,5)),dist=distance(actorToken,target.row,cell);if(dist!==null&&Number.isFinite(Number(action.range))&&dist>Number(action.range))return json({ok:false,error:`${action.name} is out of range.`,distance:dist},400);}
 let actorOut={...actor,profile:clone(profile(actor))};if(phase==='prepare'){
   if(action.resource?.spellSlotLevel){const sl=currentSlot(actorOut.profile,action.resource.spellSlotLevel);if(sl.current<1)return json({ok:false,error:`No level ${action.resource.spellSlotLevel} spell slot remains.`},400);}
   if(action.resource?.key){const r=actorOut.profile.resources?.[action.resource.key],cur=r&&typeof r==='object'?n(first(r.current,r.remaining,r.value)):n(r);if(cur<n(action.resource.cost,1))return json({ok:false,error:'Required resource is unavailable.'},400);}
   if(action.id==='basic:grapple'||action.id==='basic:shove'){if(!target)return json({ok:false,error:'Choose a target.'},400);const dc=8+prof(actorOut)+mod(actorOut,'strength'),save=Math.max(enemySaveMod(target.row,'strength'),enemySaveMod(target.row,'dexterity')),die=secureDie(20),total=die+save,success=total>=dc;if(!success&&target.kind==='token'){const st=clone(target.row.state||{}),conds=arr(st.conditions).filter((x:any)=>norm(typeof x==='string'?x:x?.name)!=='grappled');if(action.id==='basic:grapple')conds.push({name:'Grappled',sourceCharacterId:actor.id});st.conditions=conds;await admin.from('tokens').update({state:st,updated_at:new Date().toISOString()}).eq('id',target.row.id);}return json({ok:true,complete:true,result:{success:!success,enemySave:{hidden:true},effect:action.id==='basic:grapple'&&!success?'Grappled':action.id==='basic:shove'&&!success?'Shove succeeds':'Target resists'}});}
   if(action.saveAbility&&target?.kind==='token'){const dc=saveDC(actorOut,action),sm=enemySaveMod(target.row,action.saveAbility),die=secureDie(20),total=die+sm,failed=total<dc;if(action.resource)actorOut=spend(actorOut,action);await saveCharacter(admin,actorOut);if(!failed)return json({ok:true,complete:true,result:{saveSucceeded:true,hiddenEnemyRoll:true,narrationHint:`${target.row.name||'The target'} resists ${action.name}.`}});const dmg=parseDice(action.damage),heal=parseDice(action.healing);if(dmg)return json({ok:true,complete:false,next:{phase:'damage',rollRequest:{label:`${action.name} damage`,expression:dmg.expression,mode:'normal'},actionId,targetId}});if(heal)return json({ok:true,complete:false,next:{phase:'healing',rollRequest:{label:`${action.name} healing`,expression:heal.expression,mode:'normal'},actionId,targetId}});return json({ok:true,complete:true,result:{saveFailed:true,hiddenEnemyRoll:true}});}
   if(action.kind==='weapon'||action.kind==='attack'||action.attackBonus!==null&&action.attackBonus!==undefined){if(!target)return json({ok:false,error:'Choose a target.'},400);const ab=attackBonus(actorOut,action);return json({ok:true,complete:false,next:{phase:'attack',rollRequest:{label:`${action.name} attack`,expression:`1d20${ab>=0?'+':''}${ab}`,mode:'normal'},actionId,targetId}});}
   const heal=parseDice(action.healing),dmg=parseDice(action.damage);if(heal)return json({ok:true,complete:false,next:{phase:'healing',rollRequest:{label:`${action.name} healing`,expression:heal.expression,mode:'normal'},actionId,targetId:targetId||actor.id}});if(dmg)return json({ok:true,complete:false,next:{phase:'damage',rollRequest:{label:`${action.name} damage`,expression:dmg.expression,mode:'normal'},actionId,targetId}});if(action.resource){actorOut=spend(actorOut,action);await saveCharacter(admin,actorOut);}return json({ok:true,complete:true,result:{resolved:true,narrationHint:`${actor.name} uses ${action.name}.`}});
 }
 if(phase==='attack'){
   if(!roll||!target)return json({ok:false,error:'Verified attack roll and target are required.'},400);const targetAc=acOf(target.row),hit=roll.total>=targetAc||roll.natural===20,miss=roll.natural===1||!hit;if(miss)return json({ok:true,complete:true,result:{hit:false,critical:false,narrationHint:`${actor.name}'s ${action.name} misses.`}});if(action.resource){actorOut=spend(actorOut,action);await saveCharacter(admin,actorOut);}const dmg=parseDice(action.damage);if(!dmg)return json({ok:true,complete:true,result:{hit:true,critical:roll.natural===20}});let expression=dmg.expression;if(roll.natural===20)expression=`${dmg.count*2}d${dmg.sides}${dmg.mod>=0&&dmg.mod?'+':''}${dmg.mod||''}`.replace(/\+0$/,'');return json({ok:true,complete:false,next:{phase:'damage',rollRequest:{label:`${action.name} damage${roll.natural===20?' · Critical':''}`,expression,mode:'normal'},actionId,targetId,critical:roll.natural===20}});
 }
 if(phase==='damage'){
   if(!roll||!target)return json({ok:false,error:'Verified damage roll and target are required.'},400);const result=await damageTarget(admin,campaignId,target,Math.max(0,roll.total));await admin.from('story_events').insert({campaign_id:campaignId,actor_user_id:user.id,event_type:'mechanical_action',payload:{actionId,actionName:action.name,targetId,kind:'damage',amount:Math.max(0,roll.total),result}});return json({ok:true,complete:true,result:{hit:true,damage:Math.max(0,roll.total),target:result,narrationHint:`${action.name} deals ${Math.max(0,roll.total)} damage.`}});
 }
 if(phase==='healing'){
   if(!roll)return json({ok:false,error:'Verified healing roll required.'},400);const tgt=target||{kind:'character',row:actorOut},result=await healTarget(admin,campaignId,tgt,Math.max(0,roll.total));if(action.resource){actorOut=spend(actorOut,action);await saveCharacter(admin,actorOut);}await admin.from('story_events').insert({campaign_id:campaignId,actor_user_id:user.id,event_type:'mechanical_action',payload:{actionId,actionName:action.name,targetId:tgt.row.id,kind:'healing',amount:Math.max(0,roll.total),result}});return json({ok:true,complete:true,result:{healing:Math.max(0,roll.total),target:result,narrationHint:`${action.name} restores ${Math.max(0,roll.total)} HP.`}});
 }
 return json({ok:false,error:'Unsupported action phase.'},400);
});
