import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const playerNarration=(raw:unknown)=>{let text=String(raw||'').trim();for(let i=0;i<2;i++){const fenced=text.match(/```(?:json)?\s*([\s\S]*?)```/i);const candidate=fenced?.[1]?.trim()||text;const a=candidate.indexOf('{'),b=candidate.lastIndexOf('}');try{const parsed=JSON.parse(a>=0&&b>a?candidate.slice(a,b+1):candidate),next=parsed?.narration??parsed?.dm?.narration;if(typeof next!=='string')break;text=next.trim();}catch{break;}}return text;};
Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
  if(req.method!=='POST')return json({ok:false,error:'POST required'},405);
  const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')||'';
  const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service);
  const {data:uData,error:uErr}=await userClient.auth.getUser();const user=uData?.user;if(uErr||!user)return json({ok:false,error:'Authentication required'},401);
  const p=await req.json().catch(()=>({}));const campaignId=String(p.campaignId||''),message=String(p.message||'').trim().slice(0,12000);
  const requestedVisibility=p.visibility==='private'?'private':'party';const recipients=Array.isArray(p.recipientUserIds)?[...new Set(p.recipientUserIds.map(String))].slice(0,20):[];
  if(!campaignId||!message)return json({ok:false,error:'campaignId and message are required'},400);
  const {data:member}=await admin.from('campaign_members').select('role').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle();
  const {data:campaign}=await admin.from('campaigns').select('owner_id,paused,active_block,round_number,active_deadline,state,settings').eq('id',campaignId).maybeSingle();
  if(!campaign||(!member&&campaign.owner_id!==user.id))return json({ok:false,error:'Campaign access denied'},403);
  if(requestedVisibility==='private'&&!recipients.length)return json({ok:false,error:'Choose at least one private recipient'},400);
  if(recipients.length){const {data:valid}=await admin.from('campaign_members').select('user_id').eq('campaign_id',campaignId).in('user_id',recipients);const allowed=new Set((valid||[]).map((x:any)=>x.user_id));for(const id of recipients)if(!allowed.has(id)&&id!==campaign.owner_id)return json({ok:false,error:'A selected recipient is not in this campaign'},400);}
  const channelContext=requestedVisibility==='private'?`This is a PRIVATE AI-DM channel. Adjudicate secret questions/actions normally and keep secret results private. Set responseVisibility=private.`:`This is the SHARED PARTY channel. Public actions and visible consequences belong here. Never reveal player-specific secrets.`;
  const turnContext=campaign.paused?'Campaign progression is paused; answer rules/known-fact questions but do not resolve new in-world actions.':campaign.active_block?`Combat is active in block ${campaign.active_block}, round ${campaign.round_number||1}. Enforce the active player block.`:`The campaign is outside combat in scene turn ${campaign.state?.scene_turn_number||1}.`;
  const {data:armedReady}=campaign.active_block?await admin.from('readied_actions').select('id,user_id,trigger_text,action_id,action_name,slot_level').eq('campaign_id',campaignId).eq('round_number',campaign.round_number||1).eq('status','armed'): {data:[] as any[]};
  const readyContext=(armedReady||[]).length?`\nARMED READY ACTIONS: ${JSON.stringify((armedReady||[]).map((r:any)=>({id:r.id,trigger:r.trigger_text,response:r.action_name})))}. If and only if an event you narrate objectively satisfies one of these observable triggers, append [[DD_READY_TRIGGER:<exact id>]] for each satisfied trigger. Never invent an ID, trigger on player speculation, or expose this marker in prose.`:'';
  const chatRules=`${channelContext} ${turnContext}\nYou are the authoritative Dungeon Master used by the main gameplay flow. Rules questions and already-known facts are always allowed. Answer rules questions directly; never request an ability or skill check merely to determine how a published spell or feature works. A spell that selects a point within range may select the caster's space unless its text says otherwise. Fireball may be centered on the caster, who is then in its area and makes the Dexterity save normally; no Arcana check is involved. In-world actions may be adjudicated here when they are not already represented by a structured V2 button. If a player-facing roll is genuinely needed to resolve an in-world action, stop and return the exact roll request. Dungeon Dwellers V2 applies structured character mechanics through its action resolver; never duplicate an APP_RESOLVED_ACTION state change. Keep responses concise enough for chat.${readyContext}`;
  const edge=await fetch(`${url}/functions/v1/dungeon-v2-ai`,{method:'POST',headers:{Authorization:auth,apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({campaignId,message:`${chatRules}\n\nCHAT MESSAGE:\n${message}`,suppressChatPersist:true,responseVisibility:requestedVisibility})});
  const text=await edge.text();let data:any;try{data=text?JSON.parse(text):{}}catch{data={}}if(!edge.ok||data?.ok===false)return json({ok:false,error:data?.error||text||`AI HTTP ${edge.status}`},502);
  const rawNarration=playerNarration(data?.narration),triggerIds=[...rawNarration.matchAll(/\[\[DD_READY_TRIGGER:([0-9a-f-]{36})\]\]/gi)].map(m=>m[1].toLowerCase()),narration=rawNarration.replace(/\s*\[\[DD_READY_TRIGGER:[0-9a-f-]{36}\]\]/gi,'').trim();const actualVisibility=requestedVisibility==='private'||data?.event?.responseVisibility==='private'?'private':'party';
  for(const ready of (armedReady||[]).filter((r:any)=>triggerIds.includes(String(r.id).toLowerCase()))){const hours=Math.max(.05,Number(campaign.settings?.reactionWindowHours||1)),deadline=new Date(Date.now()+hours*3600000).toISOString(),option={id:'ready:execute',name:`Use ${ready.action_name}`,actionId:ready.action_id,readyActionId:ready.id,slotLevel:ready.slot_level||0},{data:rw}=await admin.from('reaction_windows').insert({campaign_id:campaignId,user_id:ready.user_id,trigger:{kind:'readied_action',text:ready.trigger_text,description:`Your declared trigger occurred: ${ready.trigger_text}`},legal_options:[option],deadline,ready_action_id:ready.id}).select('id').maybeSingle();if(rw){await admin.from('readied_actions').update({status:'triggered',triggered_at:new Date().toISOString()}).eq('id',ready.id).eq('status','armed');await admin.from('notification_outbox').insert({campaign_id:campaignId,user_id:ready.user_id,kind:'reaction',title:'Readied Action Triggered',body:`Your trigger occurred. Use ${ready.action_name} or pass.`,data:{campaignId,reactionId:rw.id},deliver_after:new Date().toISOString()});}}
  if(narration){const dmRecipients=actualVisibility==='private'?(requestedVisibility==='private'?[...new Set([user.id,...recipients])]:[user.id]):[];const {data:row,error}=await admin.from('chat_messages').insert({campaign_id:campaignId,user_id:null,sender_kind:'dm',visibility:actualVisibility,recipient_user_ids:dmRecipients,body:narration,mentions:[],metadata:{source:'dungeon-chat-v2',channel:actualVisibility==='party'?'party':'direct',event:data?.event||null,chat_only:false}}).select('id').single();if(error)return json({ok:false,error:error.message},500);if(actualVisibility==='private')for(const target of dmRecipients)await admin.from('notification_outbox').insert({campaign_id:campaignId,user_id:target,kind:'mentions',title:'Private message from AI DM',body:narration.slice(0,180),data:{campaignId,chatMessageId:row?.id,direct:true},deliver_after:new Date().toISOString()});}
  return json({ok:true,narration,event:{...(data?.event||{}),responseVisibility:actualVisibility}});
});

