import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const n=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=(v:any)=>Array.isArray(v)?v:[];
const clone=(v:any)=>JSON.parse(JSON.stringify(v??{}));
const first=(...v:any[])=>v.find(x=>x!==undefined&&x!==null&&x!=='');
const norm=(v:any)=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_');
const BLOCK_INDEX:any={player_1:1,enemy_1:2,player_2:3,enemy_2:4};
function die(sides:number){const a=new Uint32Array(1);crypto.getRandomValues(a);return(a[0]%Math.max(2,sides))+1;}
function rollExpr(expr:any){const s=String(expr||'').replace(/\s+/g,''),m=s.match(/(\d+)d(\d+)([+-]\d+)?/i);if(!m)return Math.max(0,n(s,1));let total=n(m[3],0);for(let i=0;i<Math.min(30,n(m[1],1));i++)total+=die(n(m[2],6));return Math.max(0,total);}
function ac(c:any){return n(first(c?.ac,c?.profile?.defenses?.armorClass),10);}
function hp(c:any){return n(first(c?.hp,c?.profile?.defenses?.currentHp),0);}
function maxHp(c:any){return Math.max(0,n(first(c?.max_hp,c?.profile?.defenses?.maxHp,hp(c)),hp(c)));}
async function hurt(admin:any,c:any,amount:number){const p=c.profile=clone(c.profile||{}),d=p.defenses=p.defenses||{},max=maxHp(c),temp=Math.max(0,n(first(d.tempHp,d.temporaryHp),0)),absorbed=Math.min(temp,amount),next=Math.max(0,hp(c)-(amount-absorbed));d.tempHp=temp-absorbed;d.temporaryHp=d.tempHp;d.currentHp=next;d.maxHp=max;c.hp=next;c.max_hp=max;if(next===0)d.unconscious=true;await admin.from('characters').update({hp:next,max_hp:max,profile:p,updated_at:new Date().toISOString()}).eq('id',c.id);return{hp:next,maxHp:max,absorbed};}
async function heal(admin:any,c:any,amount:number){const p=c.profile=clone(c.profile||{}),d=p.defenses=p.defenses||{},max=maxHp(c),next=Math.min(max,hp(c)+Math.max(0,amount));c.hp=next;c.max_hp=max;d.currentHp=next;d.maxHp=max;if(next>0){d.unconscious=false;d.stable=false;d.deathSaves={successes:0,failures:0};}await admin.from('characters').update({hp:next,max_hp:max,profile:p,updated_at:new Date().toISOString()}).eq('id',c.id);return{hp:next,maxHp:max};}
function abilityMod(c:any,key:any){const k=norm(key),a=c?.profile?.abilities?.[k]||c?.profile?.abilities?.[k.slice(0,3)]||{};return Number.isFinite(Number(a.mod??a.modifier))?Number(a.mod??a.modifier):Math.floor((n(a.score,10)-10)/2);}
async function queuePlayerBoundary(admin:any,campaign:any,userId:string,timing:string){const round=campaign.round_number||1,{data:character}=await admin.from('characters').select('*').eq('campaign_id',campaign.id).eq('user_id',userId).maybeSingle();if(!character)return 0;const {data:effects}=await admin.from('combat_effects').select('*').eq('campaign_id',campaign.id).eq('target_character_id',character.id).eq('active',true),deadline=new Date(Date.now()+Math.max(.05,n(campaign.settings?.reactionWindowHours,1))*3600000).toISOString();for(const effect of effects||[]){const st=clone(effect.state||{}),effectTiming=norm(first(st.ongoingTiming,effect.save_timing,'end')),marker=`${round}:${timing}`;if(effectTiming===timing&&st.lastBoundary!==marker){if(st.ongoingDamage)await hurt(admin,character,rollExpr(st.ongoingDamage));if(st.ongoingHealing)await heal(admin,character,rollExpr(st.ongoingHealing));st.lastBoundary=marker;await admin.from('combat_effects').update({state:st}).eq('id',effect.id);}if(effect.save_ability&&norm(effect.save_timing||'end')===timing){const mod=abilityMod(character,effect.save_ability),key=`effect:${effect.id}:${round}:${timing}`;await admin.from('reaction_windows').upsert({campaign_id:campaign.id,user_id:userId,boundary_key:key,trigger:{kind:'effect_save',effectId:effect.id,effectName:effect.name,ability:effect.save_ability,dc:effect.save_dc||10,description:`${effect.save_ability} save DC ${effect.save_dc||10} to end ${effect.name}.`},legal_options:[{id:'system:effect-save',name:`Roll ${effect.save_ability} Save`,expression:`1d20${mod>=0?'+':''}${mod}`,dc:effect.save_dc||10}],deadline,resolved:false},{onConflict:'campaign_id,boundary_key',ignoreDuplicates:true});}}
 const p=character.profile||{},d=p.defenses||{},deathKey=`death:${character.id}:${round}:start`;if(timing==='start'&&hp(character)<=0&&!d.dead&&!d.stable)await admin.from('reaction_windows').upsert({campaign_id:campaign.id,user_id:userId,boundary_key:deathKey,trigger:{kind:'death_save',description:'Roll a death saving throw before taking your turn.'},legal_options:[{id:'system:death-save',name:'Roll Death Save',expression:'1d20',dc:10}],deadline,resolved:false},{onConflict:'campaign_id,boundary_key',ignoreDuplicates:true});const {count}=await admin.from('reaction_windows').select('id',{count:'exact',head:true}).eq('campaign_id',campaign.id).eq('user_id',userId).eq('resolved',false).not('boundary_key','is',null);return count||0;}
async function processEnemyEffects(admin:any,campaign:any,index:number,timing:string){const round=campaign.round_number||1,{data:entries}=await admin.from('initiative_entries').select('token_id').eq('campaign_id',campaign.id).eq('side','enemy').eq('block_index',index).eq('defeated',false),ids=(entries||[]).map((x:any)=>x.token_id).filter(Boolean);if(!ids.length)return[];const {data:effects}=await admin.from('combat_effects').select('*').eq('campaign_id',campaign.id).eq('active',true).in('target_token_id',ids),summary=[];for(const effect of effects||[]){const {data:token}=await admin.from('tokens').select('*').eq('id',effect.target_token_id).maybeSingle();if(!token)continue;const st=clone(effect.state||{}),marker=`${round}:${timing}`,effectTiming=norm(first(st.ongoingTiming,effect.save_timing,'end'));if(effectTiming===timing&&st.lastBoundary!==marker){let amount=0,healed=0,ts=clone(token.state||{});if(st.ongoingDamage){amount=rollExpr(st.ongoingDamage);ts.hp=Math.max(0,n(first(ts.hp,ts.statBlock?.hp),0)-amount);}if(st.ongoingHealing){healed=rollExpr(st.ongoingHealing);ts.hp=Math.min(n(first(ts.maxHp,ts.statBlock?.maxHp,ts.hp),ts.hp),n(ts.hp)+healed);}ts.defeated=ts.hp<=0;await admin.from('tokens').update({state:ts,updated_at:new Date().toISOString()}).eq('id',token.id);await admin.from('initiative_entries').update({defeated:ts.defeated}).eq('campaign_id',campaign.id).eq('token_id',token.id);st.lastBoundary=marker;await admin.from('combat_effects').update({state:st}).eq('id',effect.id);if(amount||healed)summary.push({targetId:token.id,target:token.name,effect:effect.name,ongoingDamage:amount,ongoingHealing:healed,defeated:ts.defeated});}if(effect.save_ability&&norm(effect.save_timing||'end')===timing){const sb=token.state?.statBlock||token.state?.stat_block||{},score=sb.abilities?.[norm(effect.save_ability)]?.score??sb.abilities?.[norm(effect.save_ability)]??10,total=die(20)+Math.floor((n(score,10)-10)/2);if(total>=n(effect.save_dc,10)){await admin.from('combat_effects').update({active:false,ended_at:new Date().toISOString()}).eq('id',effect.id);summary.push({targetId:token.id,target:token.name,effect:effect.name,outcome:'ends'});}}}return summary;}
function tokenPos(t:any){return{x:n(t?.x),y:n(t?.y)};}
function distance(a:any,b:any,cell=5){const p=tokenPos(a),q=tokenPos(b);return Math.max(Math.abs(p.x-q.x),Math.abs(p.y-q.y))*cell;}
function rangeOf(a:any){const raw=first(a?.range,a?.reach,5);if(Number.isFinite(Number(raw)))return Number(raw);const s=String(raw).toLowerCase(),slash=s.match(/(\d+)\s*\/\s*(\d+)/),m=s.match(/(\d+)\s*(?:ft|feet|foot)/);return slash?Number(slash[2]):m?Number(m[1]):5;}
function moveToward(enemy:any,target:any,feet:number,cell=5){const e=tokenPos(enemy),t=tokenPos(target),cells=Math.max(0,feet/cell),dx=t.x-e.x,dy=t.y-e.y,dist=Math.max(Math.abs(dx),Math.abs(dy));if(dist<=0)return e;const f=Math.min(1,cells/dist);return{x:Math.round((e.x+dx*f)*2)/2,y:Math.round((e.y+dy*f)*2)/2};}
async function finishCombat(admin:any,campaign:any){const stateRow=(await admin.from('campaign_engine_state').select('*').eq('campaign_id',campaign.id).maybeSingle()).data,st=clone(stateRow?.state||{version:2}),now=new Date().toISOString();st.combat={...(st.combat||{}),active:false,pendingInitiative:false,endedAt:now,activeBlock:null};await admin.from('campaign_engine_state').upsert({campaign_id:campaign.id,state:st},{onConflict:'campaign_id'});await admin.from('encounter_state').update({active:false,public_state:{round:campaign.round_number||1,phase:'ended',effects:[],log:[]},updated_at:now}).eq('campaign_id',campaign.id);await admin.from('reaction_windows').update({resolved:true,resolution:{type:'combat_ended',at:now}}).eq('campaign_id',campaign.id).eq('resolved',false);await admin.from('readied_actions').update({status:'expired',resolved_at:now}).eq('campaign_id',campaign.id).in('status',['armed','triggered']);await admin.from('combat_effects').update({active:false,ended_at:now}).eq('campaign_id',campaign.id).eq('active',true).contains('state',{endsWithCombat:true});await admin.from('campaigns').update({active_block:null,active_deadline:null,deadline_type:null,updated_at:now}).eq('id',campaign.id);}
async function enemyBlock(admin:any,campaign:any,index:number){const {data:entries}=await admin.from('initiative_entries').select('*').eq('campaign_id',campaign.id).eq('side','enemy').eq('block_index',index).eq('defeated',false).order('initiative',{ascending:false}),ids=(entries||[]).map((e:any)=>e.token_id).filter(Boolean),{data:enemyTokens}=ids.length?await admin.from('tokens').select('*').in('id',ids):{data:[] as any[]},{data:chars}=await admin.from('characters').select('*').eq('campaign_id',campaign.id),{data:pcTokens}=await admin.from('tokens').select('*').eq('campaign_id',campaign.id).eq('token_type','pc'),{data:map}=await admin.from('campaign_maps').select('*').eq('campaign_id',campaign.id).eq('active',true).maybeSingle();const characters=chars||[],pcs=(pcTokens||[]).map((t:any)=>({token:t,character:characters.find((c:any)=>c.id===t.character_id||c.user_id===t.owner_user_id)})).filter((x:any)=>x.character&&hp(x.character)>0),cell=n(map?.generated_spec?.cellSizeFt,map?.grid_size===50?5:n(map?.grid_size,5)),summary:any[]=await processEnemyEffects(admin,campaign,index,'start'),defeatedAtStart=new Set(summary.filter((x:any)=>x.defeated).map((x:any)=>x.targetId));for(const enemy of enemyTokens||[]){if(defeatedAtStart.has(enemy.id)||enemy.state?.defeated||n(enemy.state?.hp,1)<=0||!pcs.length)continue;let target=pcs.slice().sort((a:any,b:any)=>distance(enemy,a.token,cell)-distance(enemy,b.token,cell))[0],sb=enemy.state?.statBlock||enemy.state?.stat_block||{},attacks=arr(sb.attacks),attack=attacks[0]||{name:'Attack',attackBonus:n(sb.attackBonus,2),damage:first(sb.damage,'1d6+1'),range:5},range=rangeOf(attack),dist=distance(enemy,target.token,cell);if(dist>range){const speed=n(first(sb.speed,enemy.state?.speed),30),pos=moveToward(enemy,target.token,speed,cell);await admin.from('tokens').update({x:pos.x,y:pos.y,updated_at:new Date().toISOString()}).eq('id',enemy.id);enemy.x=pos.x;enemy.y=pos.y;dist=distance(enemy,target.token,cell);if(dist>range){summary.push({enemy:enemy.name,target:target.character.name,outcome:'moves closer'});continue;}}
 const bonus=n(first(attack.attackBonus,attack.toHit),2),natural=die(20),total=natural+bonus,hit=natural===20||(natural!==1&&total>=ac(target.character));if(!hit){summary.push({enemy:enemy.name,target:target.character.name,attack:attack.name||'Attack',outcome:'misses'});continue;}let damageExpr=String(first(attack.damage,'1d6+1'));if(natural===20){const m=damageExpr.match(/(\d+)d(\d+)([+-]\d+)?/i);if(m)damageExpr=`${n(m[1])*2}d${m[2]}${m[3]||''}`;}const damage=rollExpr(damageExpr),result=await hurt(admin,target.character,damage);summary.push({enemy:enemy.name,target:target.character.name,attack:attack.name||'Attack',outcome:'hits',damage,hpAfter:result.hp});await admin.from('notification_outbox').insert({campaign_id:campaign.id,user_id:target.character.user_id,kind:'major_character',title:'Your Character Was Hit',body:`${enemy.name||'An enemy'} hit ${target.character.name||'your character'} for ${damage} damage.`,data:{campaignId:campaign.id,kind:'attacked'},deliver_after:new Date().toISOString()});}
 summary.push(...await processEnemyEffects(admin,campaign,index,'end'));return summary;}
async function advance(admin:any,campaign:any,fromIndex:number,auth:string,anon:string,url:string){let nextIndex=fromIndex===1?2:fromIndex===2?3:fromIndex===3?4:1,round=campaign.round_number||1,summary:any[]=[];if(nextIndex===2||nextIndex===4){const blockName=nextIndex===2?'enemy_1':'enemy_2';await admin.from('campaigns').update({active_block:blockName,active_deadline:null,updated_at:new Date().toISOString()}).eq('id',campaign.id);summary=await enemyBlock(admin,campaign,nextIndex);const alive=(await admin.from('initiative_entries').select('id',{count:'exact',head:true}).eq('campaign_id',campaign.id).eq('side','enemy').eq('defeated',false)).count||0;if(alive<=0){await finishCombat(admin,campaign);return{ended:true,summary};}if(nextIndex===2)nextIndex=3;else{nextIndex=1;round++;}}
 const nextName=nextIndex===1?'player_1':'player_2',hours=Math.max(1,Math.min(24,n(campaign.settings?.combatTurnHours,6))),deadline=new Date(Date.now()+hours*3600000).toISOString();await admin.from('campaigns').update({active_block:nextName,round_number:round,active_deadline:deadline,deadline_type:'combat_block',updated_at:new Date().toISOString()}).eq('id',campaign.id);const {data:eng}=await admin.from('campaign_engine_state').select('*').eq('campaign_id',campaign.id).maybeSingle(),st=clone(eng?.state||{version:2});st.combat={...(st.combat||{}),active:true,pendingInitiative:false,round,activeBlock:nextName};await admin.from('campaign_engine_state').upsert({campaign_id:campaign.id,state:st},{onConflict:'campaign_id'});if(summary.length){const prompt=`APP_RESOLVED_ENEMY_BLOCK\nThe Dungeon Dwellers V2 combat engine has already resolved this enemy block. Mechanics are authoritative and hidden enemy rolls must stay hidden. Narrate only what the player characters can perceive. Do not apply duplicate state effects. Visible outcomes: ${JSON.stringify(summary).slice(0,8000)}`;try{await fetch(`${url}/functions/v1/dungeon-v2-ai`,{method:'POST',headers:{Authorization:auth,apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({campaignId:campaign.id,message:prompt,responseVisibility:'party'})});}catch{}}
 return{ended:false,nextBlock:nextName,round,summary};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'POST required'},405);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')||'',uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service),{data:ud}=await uc.auth.getUser(),user=ud?.user;if(!user)return json({ok:false,error:'Authentication required'},401);const body=await req.json().catch(()=>({})),campaignId=String(body.campaignId||''),operation=String(body.operation||'end_turn');const {data:campaign}=await admin.from('campaigns').select('*').eq('id',campaignId).maybeSingle(),{data:member}=await admin.from('campaign_members').select('role').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle();if(!campaign||(!member&&campaign.owner_id!==user.id))return json({ok:false,error:'Campaign access denied'},403);if(!campaign.active_block)return json({ok:false,error:'Combat is not active.'},409);const idx=BLOCK_INDEX[campaign.active_block],{data:mine}=await admin.from('initiative_entries').select('*').eq('campaign_id',campaignId).eq('user_id',user.id).eq('defeated',false).maybeSingle();if(operation==='sync_boundary'){if((idx!==1&&idx!==3)||!mine||Number(mine.block_index)!==idx)return json({ok:true,complete:true,pending:0});const pending=await queuePlayerBoundary(admin,campaign,user.id,'start');return json({ok:true,complete:true,pending});}if(operation==='end_turn'){if(idx!==1&&idx!==3)return json({ok:false,error:'The active block belongs to enemies.'},409);if(!mine||Number(mine.block_index)!==idx)return json({ok:false,error:'It is not your initiative block.'},403);const pending=await queuePlayerBoundary(admin,campaign,user.id,'end');if(pending)return json({ok:true,advanced:false,boundaryRequired:true,pending});await admin.from('turn_submissions').upsert({campaign_id:campaignId,round_number:campaign.round_number,block_index:idx,user_id:user.id,action:{v2:true,ended:true},submitted_at:new Date().toISOString()},{onConflict:'campaign_id,round_number,block_index,user_id'});}
 if(idx===1||idx===3){const {count:need}=await admin.from('initiative_entries').select('id',{count:'exact',head:true}).eq('campaign_id',campaignId).eq('side','player').eq('block_index',idx).eq('defeated',false),{count:done}=await admin.from('turn_submissions').select('id',{count:'exact',head:true}).eq('campaign_id',campaignId).eq('round_number',campaign.round_number).eq('block_index',idx);if((done||0)<(need||0))return json({ok:true,advanced:false,waitingFor:(need||0)-(done||0)});const result=await advance(admin,campaign,idx,auth,anon,url);return json({ok:true,advanced:true,...result});}
 if(operation==='recover_advance'&&campaign.owner_id===user.id){const result=await advance(admin,campaign,idx,auth,anon,url);return json({ok:true,advanced:true,...result});}
 return json({ok:false,error:'Enemy blocks resolve automatically after the preceding player block.'},409);
});

