import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const n=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d, norm=(v:any)=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''), arr=(v:any)=>Array.isArray(v)?v:[], clone=(v:any)=>JSON.parse(JSON.stringify(v??{})), first=(...v:any[])=>v.find(x=>x!==undefined&&x!==null&&x!=='');
const XP=[0,300,900,2700,6500,14000,23000,34000,48000,64000,85000,100000,120000,140000,165000,195000,225000,265000,305000,355000];
function level(c:any){return Math.max(1,n(first(c.profile?.identity?.level,c.profile?.level),1));}function xp(c:any){return Math.max(0,n(first(c.profile?.identity?.xp,c.profile?.xp,c.profile?.experience),0));}function hp(c:any){return n(first(c.hp,c.profile?.defenses?.currentHp),0);}function maxHp(c:any){return Math.max(1,n(first(c.max_hp,c.profile?.defenses?.maxHp,hp(c)),1));}
async function save(admin:any,c:any){const {error}=await admin.from('characters').update({profile:c.profile,hp:c.hp,max_hp:c.max_hp,ac:c.ac,updated_at:new Date().toISOString()}).eq('id',c.id).eq('campaign_id',c.campaign_id);if(error)throw error;}
function groups(p:any){const e=p.equipment=p.equipment||{};return['weapons','armor','consumables','magicItems','gear'].map(k=>[k,e[k]=arr(e[k])]);}
function findItem(p:any,itemId:any){for(const [group,list] of groups(p) as any){const i=list.findIndex((x:any,j:number)=>String(x.id||`${group}:${norm(x.name)}:${j}`)===String(itemId)||norm(x.name)===norm(itemId));if(i>=0)return{group,list,index:i,item:list[i]};}return null;}
function addItem(p:any,group:string,item:any,quantity:number){const e=p.equipment=p.equipment||{},list=e[group]=arr(e[group]),existing=list.find((x:any)=>norm(x.name)===norm(item.name)&&String(x.id||'')===String(item.id||''));if(existing)existing.quantity=n(first(existing.quantity,existing.qty),1)+quantity;else list.push({...clone(item),quantity});}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'POST required'},405);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')||'',uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service),{data:ud}=await uc.auth.getUser(),user=ud?.user;if(!user)return json({ok:false,error:'Authentication required'},401);const body=await req.json().catch(()=>({})),campaignId=String(body.campaignId||''),op=String(body.operation||'');const {data:campaign}=await admin.from('campaigns').select('owner_id,active_block,round_number').eq('id',campaignId).maybeSingle(),{data:member}=await admin.from('campaign_members').select('role').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle(),{data:actor}=await admin.from('characters').select('*').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle();if(!campaign||(!member&&campaign.owner_id!==user.id))return json({ok:false,error:'Campaign access denied'},403);if(!actor)return json({ok:false,error:'Choose a character first.'},409);
 if(op==='death_save'){if(hp(actor)>0)return json({ok:false,error:'Death saves are only used at 0 HP.'},409);const p=actor.profile=clone(actor.profile||{}),d=p.defenses=p.defenses||{};if(d.dead)return json({ok:false,error:'This character is dead.'},409);if(d.stable)return json({ok:false,error:'This character is stable.'},409);const roll=body.verifiedRoll,total=n(roll?.total,-1),natural=n(first(roll?.natural,roll?.rolls?.[0]),-1);if(total<0||natural<1||natural>20)return json({ok:false,error:'A verified d20 roll is required.'},400);const ds=d.deathSaves=d.deathSaves||{successes:0,failures:0};let outcome='';if(natural===20){actor.hp=1;d.currentHp=1;d.unconscious=false;d.stable=false;d.deathSaves={successes:0,failures:0};outcome='Natural 20: regain 1 HP.';}else if(natural===1){ds.failures=Math.min(3,n(ds.failures)+2);outcome='Natural 1: two failures.';}else if(total>=10){ds.successes=Math.min(3,n(ds.successes)+1);outcome='Death save success.';}else{ds.failures=Math.min(3,n(ds.failures)+1);outcome='Death save failure.';}if(n(ds.failures)>=3){d.dead=true;outcome='Three failures: the character dies.';}else if(n(ds.successes)>=3){d.stable=true;outcome='Three successes: the character is stable.';}await save(admin,actor);await admin.from('story_events').insert({campaign_id:campaignId,actor_user_id:user.id,event_type:'death_save',payload:{characterId:actor.id,total,natural,successes:n(d.deathSaves?.successes),failures:n(d.deathSaves?.failures),outcome}});return json({ok:true,outcome,hp:actor.hp,deathSaves:d.deathSaves,dead:!!d.dead,stable:!!d.stable});}
 if(op==='level_up'){const old=level(actor),target=Math.min(20,old+1),required=XP[target-1];if(old>=20)return json({ok:false,error:'This character is already level 20.'},409);if(xp(actor)<required)return json({ok:false,error:`Level ${target} requires ${required} XP.`},409);const p=actor.profile=clone(actor.profile||{});p.identity=p.identity||{};p.identity.level=target;p.level=target;p.levelHistory=arr(p.levelHistory);p.levelHistory.push({level:target,at:new Date().toISOString(),choices:body.choices||{},source:'v2-guided'});actor.profile=p;await save(admin,actor);await admin.from('story_events').insert({campaign_id:campaignId,actor_user_id:user.id,event_type:'level_up',payload:{characterId:actor.id,from:old,to:target,choices:body.choices||{}}});return json({ok:true,level:target,progression:p.progression?.[target]||p.levelProgression?.[target]||null,message:'Level increased. Any class/subclass/spell/feat choices stored in the character profile remain authoritative; use Character Edit or re-import an updated sheet when the profile does not contain structured progression choices.'});}
 if(op==='equip'){const p=actor.profile=clone(actor.profile||{}),hit=findItem(p,body.itemId);if(!hit)return json({ok:false,error:'Item not found.'},404);const equip=body.equipped!==false;hit.item.equipped=equip;if(hit.group==='armor'&&equip){for(const x of hit.list)if(x!==hit.item&&x.category!=='shield')x.equipped=false;}await save(admin,actor);return json({ok:true,item:hit.item});}
 if(op==='transfer'){const toId=String(body.toCharacterId||''),qty=Math.max(1,Math.floor(n(body.quantity,1)));if(!toId||toId===actor.id)return json({ok:false,error:'Choose another party character.'},400);const {data:target}=await admin.from('characters').select('*').eq('campaign_id',campaignId).eq('id',toId).maybeSingle();if(!target)return json({ok:false,error:'Receiving character not found.'},404);const ap=actor.profile=clone(actor.profile||{}),tp=target.profile=clone(target.profile||{}),hit=findItem(ap,body.itemId);if(!hit)return json({ok:false,error:'Item not found.'},404);const have=Math.max(1,n(first(hit.item.quantity,hit.item.qty),1));if(qty>have)return json({ok:false,error:'Not enough quantity to transfer.'},400);const moved={...clone(hit.item),equipped:false};if(qty===have)hit.list.splice(hit.index,1);else hit.item.quantity=have-qty;addItem(tp,hit.group,moved,qty);actor.profile=ap;target.profile=tp;await save(admin,actor);await save(admin,target);await admin.from('story_events').insert({campaign_id:campaignId,actor_user_id:user.id,event_type:'item_transfer',payload:{fromCharacterId:actor.id,toCharacterId:target.id,itemName:moved.name,quantity:qty}});return json({ok:true,item:moved.name,quantity:qty,to:target.display_name||target.name});}
 if(op==='transfer_currency'){const toId=String(body.toCharacterId||''),currency=String(body.currency||'gp').toLowerCase(),amount=Math.max(0,n(body.amount));if(!['cp','sp','ep','gp','pp'].includes(currency)||amount<=0)return json({ok:false,error:'Choose a valid positive currency amount.'},400);const {data:target}=await admin.from('characters').select('*').eq('campaign_id',campaignId).eq('id',toId).maybeSingle();if(!target)return json({ok:false,error:'Receiving character not found.'},404);const ap=actor.profile=clone(actor.profile||{}),tp=target.profile=clone(target.profile||{}),acur=ap.currency=ap.currency||ap.equipment?.currency||{},tcur=tp.currency=tp.currency||tp.equipment?.currency||{};if(n(acur[currency])<amount)return json({ok:false,error:'Not enough currency.'},400);acur[currency]=n(acur[currency])-amount;tcur[currency]=n(tcur[currency])+amount;actor.profile=ap;target.profile=tp;await save(admin,actor);await save(admin,target);return json({ok:true,currency,amount,to:target.display_name||target.name});}
 return json({ok:false,error:'Unknown V2 character operation.'},400);
});