import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const n=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=(v:any)=>Array.isArray(v)?v:[];
const clone=(v:any)=>JSON.parse(JSON.stringify(v??{}));
const clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
function mod(score:any){return Math.floor((n(score,10)-10)/2);}
function dexMod(c:any){const p=c?.profile||{},d=p.abilities?.dexterity||p.abilities?.dex||{};if(Number.isFinite(Number(d.mod)))return Number(d.mod);if(Number.isFinite(Number(d.modifier)))return Number(d.modifier);return mod(d.score);}
function secureDie(sides=20){const a=new Uint32Array(1);crypto.getRandomValues(a);return(a[0]%sides)+1;}
function cleanJsonText(raw:any){let s=String(raw||'').trim();const f=s.match(/```(?:json)?\s*([\s\S]*?)```/i);if(f)s=f[1].trim();const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)s=s.slice(a,b+1);return s;}
function modelNarration(data:any){const p=data?.dm??data?.result??data;return String(typeof p==='string'?p:(p?.narration||p?.response||data?.narration||data?.response||data?.raw||''));}
async function workerJson(workerUrl:string,prompt:string){try{const r=await fetch(workerUrl,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({message:prompt,campaignState:{task:'structured_support'}})}),text=await r.text();if(!r.ok)return null;let data:any;try{data=JSON.parse(text)}catch{return null}const raw=modelNarration(data);return JSON.parse(cleanJsonText(raw));}catch{return null;}}
async function generateEnemies(workerUrl:string,narration:string,avgLevel:number){const prompt=`You are a D&D 5e 2024 encounter stat-block generator for a private game engine. Based only on the visible hostile creatures implied by the scene below, return JSON ONLY in the narration field. Do not add prose. Shape: {"enemies":[{"name":"","count":1,"ac":12,"hp":12,"speed":30,"size":"medium","initiativeBonus":2,"abilities":{"strength":10,"dexterity":10,"constitution":10,"intelligence":8,"wisdom":10,"charisma":8},"saves":{},"attacks":[{"name":"Attack","attackBonus":3,"damage":"1d6+1","damageType":"slashing","range":5}],"resistances":[],"immunities":[],"conditions":[]}]} Keep total enemies appropriate for a party around level ${avgLevel}. Use only creatures actually implied by the scene; if the scene does not imply a hostile creature, return {"enemies":[]}. SCENE: ${narration.slice(0,5000)}`;return await workerJson(workerUrl,prompt);}
async function compressMemory(workerUrl:string,current:any,chat:any[],quests:any[],npcs:any[]){const prompt=`You maintain compact long-term memory for a D&D campaign. Return JSON ONLY in narration. Preserve unresolved promises, clues, consequences, NPC relationships, faction state, destroyed/changed locations, recurring villains, discovered truths, and open plot threads. Do not invent facts. Shape: {"publicSummary":"<=2500 chars, party-safe continuity summary","privateState":{"npcs":{},"factions":{},"threads":[],"promises":[],"consequences":[],"locations":{},"clues":[],"timeline":[]}}. Existing memory: ${JSON.stringify(current).slice(0,10000)} Recent chat: ${JSON.stringify(chat).slice(0,18000)} Quests: ${JSON.stringify(quests).slice(0,6000)} NPC state: ${JSON.stringify(npcs).slice(0,7000)}`;return await workerJson(workerUrl,prompt);}
async function startCombat(admin:any,campaign:any,user:any,narration:string,workerUrl:string){const campaignId=campaign.id,{data:engine}=await admin.from('campaign_engine_state').select('*').eq('campaign_id',campaignId).maybeSingle();if(engine?.state?.combat?.active||engine?.state?.combat?.pendingInitiative||campaign.active_block)return null;const {data:chars}=await admin.from('characters').select('*').eq('campaign_id',campaignId),characters=chars||[];if(!characters.length)return null;const {data:map}=await admin.from('campaign_maps').select('*').eq('campaign_id',campaignId).eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();let {data:enemyRows}=await admin.from('tokens').select('*').eq('campaign_id',campaignId).eq('token_type','enemy').eq('hidden',false);let enemies=enemyRows||[];
 if(!enemies.length){const avg=Math.max(1,Math.round(characters.reduce((a:any,c:any)=>a+n(c.profile?.identity?.level||c.profile?.level,1),0)/characters.length)),g=await generateEnemies(workerUrl,narration,avg),defs=arr(g?.enemies).slice(0,8),rows:any[]=[];let index=0;for(const def of defs){const count=clamp(Math.floor(n(def.count,1)),1,6);for(let i=0;i<count&&rows.length<12;i++){const hp=Math.max(1,Math.floor(n(def.hp,8))),name=count>1?`${String(def.name||'Hostile Creature')} ${i+1}`:String(def.name||'Hostile Creature');rows.push({campaign_id:campaignId,map_id:map?.id||null,token_type:'enemy',name,x:map?Math.max(2,n(map.generated_spec?.widthCells,30)-5-(index%4)*2):70,y:map?4+Math.floor(index/4)*3:55,hidden:false,state:{position_mode:map?'grid':'percent',hp,maxHp:hp,ac:clamp(Math.floor(n(def.ac,12)),5,30),speed:Math.max(0,n(def.speed,30)),size:String(def.size||'medium'),statBlock:{name,ac:clamp(Math.floor(n(def.ac,12)),5,30),hp,maxHp:hp,speed:Math.max(0,n(def.speed,30)),size:String(def.size||'medium'),initiativeBonus:n(def.initiativeBonus,0),abilities:def.abilities||{},saves:def.saves||{},attacks:arr(def.attacks).slice(0,8),resistances:arr(def.resistances).slice(0,12),immunities:arr(def.immunities).slice(0,12)},conditions:[]}});index++;}}
 if(rows.length){const ins=await admin.from('tokens').insert(rows).select('*');if(!ins.error)enemies=ins.data||[];}}
 if(!enemies.length)return null;
 await admin.from('initiative_entries').delete().eq('campaign_id',campaignId);
 const enemyInit=enemies.map((t:any)=>{const sb=t.state?.statBlock||t.state?.stat_block||{},bonus=n(sb.initiativeBonus,mod(sb.abilities?.dexterity?.score??sb.abilities?.dexterity??10));return{campaign_id:campaignId,combatant_key:`enemy:${t.id}`,side:'enemy',user_id:null,token_id:t.id,display_name:t.name||'Enemy',initiative:secureDie(20)+bonus,block_index:null,defeated:false,state:{v2:true,hidden_roll:true}};});
 if(enemyInit.length)await admin.from('initiative_entries').insert(enemyInit);
 const pendingUsers=characters.map((c:any)=>c.user_id);const nextState=clone(engine?.state||{version:2});nextState.combat={...(nextState.combat||{}),active:false,pendingInitiative:true,pendingUsers,requestedAt:new Date().toISOString(),enemyCount:enemies.length};await admin.from('campaign_engine_state').upsert({campaign_id:campaignId,state:nextState},{onConflict:'campaign_id'});await admin.from('encounter_state').upsert({campaign_id:campaignId,active:true,public_state:{round:0,phase:'initiative',effects:[],log:[{at:new Date().toISOString(),kind:'combat_start'}]},hidden_state:{combatants:Object.fromEntries(enemies.map((e:any)=>[e.id,e.state?.statBlock||{}])),pending:[],resources:{}},updated_at:new Date().toISOString()},{onConflict:'campaign_id'});
 for(const c of characters)await admin.from('notification_outbox').insert({campaign_id:campaignId,user_id:c.user_id,kind:'turn',title:'Roll Initiative',body:'Combat is beginning. Open Dungeon Dwellers and roll your initiative.',data:{campaignId,kind:'initiative'},deliver_after:new Date().toISOString()});
 const own=characters.find((c:any)=>c.user_id===user.id),bonus=own?dexMod(own):0;return own?{label:'Initiative',expression:`1d20${bonus>=0?'+':''}${bonus}`,mode:'normal',hiddenDC:false,reason:'Combat has begun; the Dungeon Master called for initiative.'}:null;
}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'POST required'},405);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,workerUrl=Deno.env.get('DUNGEON_AI_WORKER_URL')||'https://dungeon-dwellers-ai.jesse-datema08.workers.dev',auth=req.headers.get('Authorization')||'',uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service),{data:ud}=await uc.auth.getUser(),user=ud?.user;if(!user)return json({ok:false,error:'Authentication required'},401);const body=await req.json().catch(()=>({})),campaignId=String(body.campaignId||''),message=String(body.message||'').slice(0,12000);if(!campaignId||!message)return json({ok:false,error:'campaignId and message required'},400);const {data:campaign}=await admin.from('campaigns').select('*').eq('id',campaignId).maybeSingle(),{data:mem}=await admin.from('campaign_memory').select('*').eq('campaign_id',campaignId).maybeSingle(),{data:member}=await admin.from('campaign_members').select('role').eq('campaign_id',campaignId).eq('user_id',user.id).maybeSingle();if(!campaign||(!member&&campaign.owner_id!==user.id))return json({ok:false,error:'Campaign access denied'},403);
 const director=`DUNGEON DWELLERS V2 DIRECTOR ADDENDUM: Mechanics that have already been applied by APP_RESOLVED_ACTION are authoritative; narrate them without duplicating state effects. If visible hostilities cross the line into structured combat and initiative is genuinely required, explicitly include the exact sentence "Roll initiative." Do not roll initiative for players. Do not start combat for mere suspicion, conversation, threats, exploration, or a single non-hostile creature. Long-term continuity memory, if present, is authoritative but private fields must never be revealed unless discovered in play.\nPUBLIC CONTINUITY MEMORY: ${String(mem?.public_summary||'').slice(0,3500)}\nPLAYER MESSAGE:\n${message}`;
 const edge=await fetch(`${url}/functions/v1/dungeon-ai`,{method:'POST',headers:{Authorization:auth,apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({...body,campaignId,message:director})}),text=await edge.text();let data:any;try{data=text?JSON.parse(text):{}}catch{data={}}if(!edge.ok||data?.ok===false)return json({ok:false,error:data?.error||text||`AI HTTP ${edge.status}`},502);const narration=String(data?.narration||'').trim();let event=data?.event&&typeof data.event==='object'?data.event:{};
 const combatCalled=/\broll initiative\b/i.test(narration);if(combatCalled&&!campaign.active_block){const roll=await startCombat(admin,campaign,user,narration,workerUrl);if(roll)event={...event,rollRequest:event.rollRequest||roll,notify:'turn'};}
 let engine=(await admin.from('campaign_engine_state').select('*').eq('campaign_id',campaignId).maybeSingle()).data;const st=clone(engine?.state||{version:2}),counter=n(st.memoryCounter,0)+1;st.memoryCounter=counter;await admin.from('campaign_engine_state').upsert({campaign_id:campaignId,state:st},{onConflict:'campaign_id'});
 if(narration){const timeline=arr(mem?.private_state?.timeline).slice(-79);timeline.push({at:new Date().toISOString(),summary:narration.slice(0,700)});const priv={...(mem?.private_state||{}),timeline};let publicSummary=String(mem?.public_summary||'');if(event?.sceneSummary)publicSummary=`${publicSummary}\n${String(event.sceneSummary).slice(0,1200)}`.trim().slice(-9000);await admin.from('campaign_memory').upsert({campaign_id:campaignId,public_summary:publicSummary,private_state:priv,updated_at:new Date().toISOString()},{onConflict:'campaign_id'});}
 if(counter%8===0){const [{data:chat},{data:quests},{data:npcs},{data:curMem}]=await Promise.all([admin.from('chat_messages').select('sender_kind,body,visibility,created_at').eq('campaign_id',campaignId).eq('visibility','party').order('created_at',{ascending:false}).limit(36),admin.from('quests').select('title,status,data').eq('campaign_id',campaignId).limit(30),admin.from('npc_state').select('npc_key,public_state,hidden_state').eq('campaign_id',campaignId).limit(50),admin.from('campaign_memory').select('*').eq('campaign_id',campaignId).maybeSingle()]);const compressed=await compressMemory(workerUrl,curMem,chat||[],quests||[],npcs||[]);if(compressed?.publicSummary&&compressed?.privateState)await admin.from('campaign_memory').upsert({campaign_id:campaignId,public_summary:String(compressed.publicSummary).slice(0,12000),private_state:compressed.privateState,updated_at:new Date().toISOString()},{onConflict:'campaign_id'});}
 return json({...data,event});
});